// Smart LC Practice Set 6 — Academic Reading (40 questions, 3 passages).
// Original material authored for Smart LC to the blueprint: P1 factual
// history (completion + TFNG), P2 discursive with lettered paragraphs
// (matching information + summary + people matching with one extra name),
// P3 argumentative psychology (MCQ-4 + YNNG + sentence endings). Key
// quotas: TFNG/YNNG balanced with no runs of three, flat letters, unique
// concrete-noun answers, correct MCQ options paraphrase the text while
// distractors echo its wording.
export const PSET6_READING = {
  id: "pset6-reading",
  bookId: "pset6",
  title: "Practice Set 6 — Reading",
  module: "reading",
  durationMin: 60,
  sections: [
    {
      title: "Passage 1",
      instructions: "You should spend about 20 minutes on Questions 1–13, which are based on Reading Passage 1 below.",
      passageTitle: "The teeth that closed the coat",
      passage: `For most of the nineteenth century, getting dressed took a long time. Coats, boots and dresses were held shut by rows of buttons or by hooks and eyes, and a pair of tall boots might carry twenty fastenings down each side. Wealthy households employed servants partly for this reason, and the buttonhook — a slender steel tool sold in every draper's shop — existed solely to drag small buttons through stiff leather. The idea of a fastening that could be closed in one movement was obviously attractive, but nobody could make one that worked.

The first serious attempt came from Elias Howe, better remembered for his work on the sewing machine. In 1851 he patented what he called an "automatic continuous clothing closure", a row of clasps joined by a cord. Howe never manufactured it, and the design sank without trace; he was busy defending his sewing-machine patents, and the closure looked like a distraction. Forty years passed before anyone tried again.

The man who did was Whitcomb Judson, a Chicago engineer whose real interest was compressed-air street railways. Judson had a friend with a stiff back who found bending down to fasten his boots painful, and in 1893 Judson patented a "clasp locker": two rows of hooks and eyes joined by a slider that pulled them together. He exhibited it at the Chicago World's Fair that same year, where it attracted enormous curiosity and almost no orders. The reason was simple. The clasp locker sprang open without warning, usually at the worst possible moment, and the hooks caught on the fabric around them. Judson's company sold barely twenty of the devices in its first two decades, most of them for mail bags rather than clothing.

The problem was solved by an employee. Gideon Sundback, a Swedish-born electrical engineer who joined Judson's firm in 1906, spent years reconsidering the fastening from first principles, and in 1913 he abandoned hooks entirely. His design used identical metal teeth, each with a small hollow on one face and a matching bulge on the other, mounted on cloth tapes. The slider did not force the teeth together but wedged them so that every bulge dropped into the hollow of the tooth opposite, locking the whole row. Because the teeth were interchangeable, they could be stamped out by machine, and Sundback built the machinery to do it: his automatic S-L machine produced several hundred metres of fastening a day. The new device did not spring open, because no single tooth could release unless the slider passed over it.

Even so, the clothing trade would not touch it. Tailors were paid by the hour and knew how to sew buttonholes; the new fastening required a different technique and unfamiliar machinery, and a garment carrying one could not be pressed with a hot iron in the usual way. Sundback's rescue came from an entirely different quarter. During the First World War, the United States Navy ordered the fastening for flying suits, where a pilot in an open cockpit needed to get in and out of heavy clothing quickly, and money was no object. Wartime orders kept the company alive.

The name that finally sold it was not the inventor's. In 1923 the B. F. Goodrich company used the fastening on a new rubber overshoe, and an executive, demonstrating how quickly the boot could be closed, is said to have remarked that he liked the sound it made — a zip. Goodrich registered the word as a trademark for the boots, but the public attached it to the fastening itself, and within a few years the name had escaped its owner altogether.

Clothing took longer to convert than boots. It was the 1930s before the fashion houses of Paris began using the fastening in dresses, and 1937 before it appeared in men's trousers, where the tailoring trade press debated the change with some seriousness before conceding that it was more reliable than a row of buttons. Children's clothes were an early success for a reason parents appreciated: a child could dress unaided. Manufacturers of luggage and tents adopted it at much the same time, and for the same practical reason — a closure that could be worked with one hand, in the dark, without hunting for a small object in a small hole.

Part of the delay was simply that the fastening had to be sold twice: once to the firm that sewed it into a garment and again to the customer who would have to trust it. Early advertisements dwelt less on speed than on security, showing the closed row of teeth under strain, because the memory of Judson's device springing open in public had outlived the device itself. It was an unusual difficulty for an invention — not persuading people that it worked, but persuading them to forget that something resembling it once had not.

The design has hardly altered since Sundback. A modern fastening still consists of two tapes, interlocking teeth and a slider that wedges them together, and the teeth are still stamped in one continuous operation. What has changed is the material — moulded plastic teeth in place of metal for lighter garments — and the scale, since the fastening now closes tents, luggage, sleeping bags and the protective suits worn in hospitals. It remains one of the few nineteenth-century mechanical problems whose twentieth-century solution nobody has found a reason to improve.`,
      questions: [
        { n: 1, type: "gap", prompt: "Small buttons were pulled through stiff leather using a ______.", note: "ONE WORD ONLY", answer: "buttonhook", explain: "The passage says the buttonhook was a steel tool sold in every draper's shop that existed solely to drag small buttons through stiff leather.", evidence: "existed solely to drag small buttons through stiff leather", vocab: ["drag", "pulled"] },
        { n: 2, type: "gap", prompt: "Howe's 1851 design joined its clasps together with a ______.", note: "ONE WORD ONLY", answer: "cord", explain: "Howe's closure is described as a row of clasps joined by a cord.", evidence: "a row of clasps joined by a cord" },
        { n: 3, type: "gap", prompt: "Judson designed his clasp locker after a friend had difficulty fastening his ______.", note: "ONE WORD ONLY", answer: "boots", explain: "Judson's friend had a stiff back and found bending down to fasten his boots painful.", evidence: "found bending down to fasten his boots painful" },
        { n: 4, type: "gap", prompt: "Most clasp lockers sold in the first twenty years were used on ______.", note: "TWO WORDS ONLY", answer: "mail bags", explain: "The company sold barely twenty devices in two decades, most of them for mail bags rather than clothing.", evidence: "most of them for mail bags rather than clothing" },
        { n: 5, type: "gap", prompt: "In Sundback's design, each tooth has a hollow on one face and a ______ on the other.", note: "ONE WORD ONLY", answer: "bulge", explain: "The teeth are described as having a small hollow on one face and a matching bulge on the other.", evidence: "a small hollow on one face and a matching bulge on the other" },
        { n: 6, type: "gap", prompt: "The fastening was first bought in quantity for ______ supplied to the navy.", note: "TWO WORDS ONLY", answer: "flying suits", explain: "The United States Navy ordered the fastening for flying suits during the First World War.", evidence: "the United States Navy ordered the fastening for flying suits" },
        { n: 7, type: "gap", prompt: "The word 'zip' was first registered as a trademark for a rubber ______.", note: "ONE WORD ONLY", answer: "overshoe", explain: "Goodrich used the fastening on a new rubber overshoe and registered the word as a trademark for the boots.", evidence: "used the fastening on a new rubber overshoe" },
        { n: 8, type: "tfng", prompt: "Howe abandoned his clothing closure in order to concentrate on legal disputes.", answer: "TRUE", explain: "TRUE: the passage says Howe never manufactured it because he was busy defending his sewing-machine patents, which is a legal dispute.", evidence: "he was busy defending his sewing-machine patents", vocab: ["defending his patents", "legal disputes"] },
        { n: 9, type: "tfng", prompt: "Judson's clasp locker was ignored by visitors to the Chicago World's Fair.", answer: "FALSE", explain: "FALSE: it attracted enormous curiosity at the fair — what it failed to attract was orders.", evidence: "it attracted enormous curiosity and almost no orders" },
        { n: 10, type: "tfng", prompt: "Sundback had to design machinery in order to produce his fastening.", answer: "TRUE", explain: "TRUE: because the teeth were interchangeable they could be stamped by machine, and Sundback built the machinery to do it.", evidence: "Sundback built the machinery to do it" },
        { n: 11, type: "tfng", prompt: "Tailors welcomed the new fastening because it was quicker to attach than buttonholes.", answer: "FALSE", explain: "FALSE: the clothing trade would not touch it — it needed a different technique and unfamiliar machinery.", evidence: "the new fastening required a different technique and unfamiliar machinery" },
        { n: 12, type: "tfng", prompt: "The company that registered the name 'zip' kept exclusive use of it.", answer: "FALSE", explain: "FALSE: the public attached the name to the fastening itself, and within a few years it had escaped its owner altogether.", evidence: "the name had escaped its owner altogether" },
        { n: 13, type: "tfng", prompt: "Sundback earned more from the fastening than Judson did.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage compares the two men's designs and their success in the market, but says nothing about what either of them earned.", evidence: "Sundback's rescue came from an entirely different quarter" },
      ],
    },
    {
      title: "Passage 2",
      instructions: "You should spend about 20 minutes on Questions 14–26, which are based on Reading Passage 2 below.",
      passageTitle: "Roofs that grow",
      passage: `A A city seen from the air is mostly roof. In a dense European centre, somewhere between a fifth and a quarter of the whole surface is roofing, and until recently almost all of it was doing a single job: keeping rain out of the building underneath. Planting that surface turns a large idle area into something that works, and cities from Basel to Toronto now require it on new buildings of a certain size. The idea is not new: turf roofs kept Norwegian farmhouses warm for centuries, and the modern version was developed in Germany in the 1960s, where roughly a tenth of all flat roofs are now planted.

B The argument that persuaded most city governments was not about wildlife but about water. A conventional roof sheds almost everything that falls on it within minutes, and in a storm every roof in a district sheds at once, so the drains beneath must be built for a surge that comes a few times a year and sit half empty otherwise. Where sewers carry rainwater and waste in one pipe, a heavy storm can overwhelm them and push untreated water into the nearest river. A planted roof interrupts that surge. Its growing layer absorbs the first rain like a sponge and releases the rest slowly, so the water reaches the drains over hours rather than minutes. Measurements in several cities put the retention at between forty and sixty per cent of annual rainfall, and they delay the peak of a storm by up to an hour — often long enough for the earlier surge to have passed.

C The second argument is heat. Dark roofing absorbs sun all day and re-radiates it into the evening, which is one reason a city centre can be several degrees warmer at night than the countryside around it. A planted roof stays close to air temperature because the plants lose water and cool themselves as they do so. Hanna Reuter, a building physicist who has monitored Stuttgart roofs for a decade, records surface temperatures on bare bitumen of up to eighty degrees on a summer afternoon, against low thirties on a planted roof nearby. That difference matters twice: it reduces the heat leaking into the rooms below, and it slows the ageing of the roof itself, since it is the daily swing between hot and cold that cracks a waterproof membrane. Reuter's view is that the longer life of the covering, rather than any saving on cooling, is what makes the sums work for a building's owner.

D Cost is where the argument becomes complicated. A planted roof costs more to build than a plain one — commonly half as much again — and someone must pay the difference. The benefits, awkwardly, are shared: the owner gets a longer-lasting roof and cooler top-floor rooms, while the city gets the water held back and the heat absorbed. Marek Dolinski, an economist who has studied a subsidy scheme in Warsaw, argues that this split explains why almost nothing is built without a grant. Where cities have simply required planted roofs by regulation rather than paying for them, he notes, the requirement is met at the lowest possible standard: a thin layer of growing material, a single species, and a roof that turns brown in the first dry summer.

E That thin standard is at the centre of a disagreement about what these roofs are for. The cheapest version carries perhaps six centimetres of material planted with sedum, a shallow-rooted succulent that survives drought and needs almost no attention. It holds water and cools the surface, and for a drainage engineer that is the whole point. Ecologists are less content. Ines Carvalho, who surveys roof insects in Lisbon and Porto, has found that sedum roofs support a narrow range of species and that the richest roofs are those with an uneven depth of material, patches of bare gravel and a mixture of local plants — conditions that resemble the dry, disturbed ground many declining insects depend on. Her surveys record several times as many bee species on varied roofs as on uniform sedum, and she argues that the extra depth costs little at the design stage and nothing at all afterwards.

F Against this, structure sets a hard limit. Growing material is heavy, and it is heaviest when saturated, exactly when the roof is also carrying the weight of the water it is holding back. A deep, varied roof of the kind Carvalho recommends can weigh three or four times what a sedum mat does, and most existing buildings were not designed for it. This is why retrofitting, which would matter most since the great majority of a city's roofs already exist, is far rarer than planting new buildings, and why the cheap thin roof, whatever the ecologists think of it, is often the only version an old building can carry.

G What almost everyone agrees on is that the roofs need to be thought of together rather than one at a time. A single planted roof is a small private benefit; a district of them begins to behave like a landscape, holding back enough water to change what the drains below must cope with and forming a chain of habitat that insects can actually move along. Several cities now map their roofs and target grants at districts where the sewers flood, rather than spreading money evenly.`,
      questions: [
        { n: 14, type: "match", prompt: "a reason why planted roofs are seldom added to buildings that already exist", options: ["A", "B", "C", "D", "E", "F", "G"], answer: "F", explain: "Paragraph F explains that a deep planted roof weighs three or four times what a sedum mat does and most existing buildings were not designed for it, which is why retrofitting is rare.", evidence: "most existing buildings were not designed for it" },
        { n: 15, type: "match", prompt: "an explanation of why the benefits and the costs fall to different people", options: ["A", "B", "C", "D", "E", "F", "G"], answer: "D", explain: "Paragraph D says the owner pays but the benefits are shared between the owner and the city.", evidence: "The benefits, awkwardly, are shared" },
        { n: 16, type: "match", prompt: "a description of how a planted roof changes the timing of water reaching the drains", options: ["A", "B", "C", "D", "E", "F", "G"], answer: "B", explain: "Paragraph B describes the growing layer absorbing the first rain and releasing the rest slowly, delaying the storm peak by up to an hour.", evidence: "the water reaches the drains over hours rather than minutes" },
        { n: 17, type: "match", prompt: "a reference to the proportion of a city's surface that is roofing", options: ["A", "B", "C", "D", "E", "F", "G"], answer: "A", explain: "Paragraph A states that between a fifth and a quarter of a dense European centre is roofing.", evidence: "somewhere between a fifth and a quarter of the whole surface is roofing" },
        { n: 18, type: "match", prompt: "an argument for planning planted roofs across a whole area rather than individually", options: ["A", "B", "C", "D", "E", "F", "G"], answer: "G", explain: "Paragraph G argues that a district of planted roofs behaves like a landscape, and that cities target grants where sewers flood.", evidence: "a district of them begins to behave like a landscape" },
        { n: 19, type: "gap", prompt: "Complete the summary. A planted roof stays near air temperature because the plants release ______ and cool as they do so.", note: "ONE WORD ONLY", answer: "water", explain: "Paragraph C explains that the plants lose water and cool themselves as they do so.", evidence: "the plants lose water and cool themselves as they do so" },
        { n: 20, type: "gap", prompt: "On a summer afternoon, bare ______ was measured at up to eighty degrees.", note: "ONE WORD ONLY", answer: "bitumen", explain: "Reuter records surface temperatures on bare bitumen of up to eighty degrees.", evidence: "surface temperatures on bare bitumen of up to eighty degrees" },
        { n: 21, type: "gap", prompt: "A waterproof covering is cracked by the daily ______ between hot and cold.", note: "ONE WORD ONLY", answer: "swing", explain: "The passage says it is the daily swing between hot and cold that cracks a waterproof membrane.", evidence: "it is the daily swing between hot and cold that cracks a waterproof membrane" },
        { n: 22, type: "gap", prompt: "The cheapest planted roofs are usually planted with a drought-resistant succulent called ______.", note: "ONE WORD ONLY", answer: "sedum", explain: "The cheapest version carries about six centimetres of material planted with sedum, a shallow-rooted succulent that survives drought.", evidence: "planted with sedum, a shallow-rooted succulent that survives drought" },
        { n: 23, type: "gap", prompt: "The richest roofs for insects include patches of bare ______.", note: "ONE WORD ONLY", answer: "gravel", explain: "Carvalho found the richest roofs have uneven depth, patches of bare gravel and a mixture of local plants.", evidence: "patches of bare gravel and a mixture of local plants" },
        { n: 24, type: "select", prompt: "Planted roofs are met at the lowest possible standard when cities require them without funding them.", options: ["Hanna Reuter", "Marek Dolinski", "Ines Carvalho"], answer: "Marek Dolinski", explain: "Dolinski notes that where cities require planted roofs by regulation rather than paying for them, the requirement is met at the lowest possible standard.", evidence: "the requirement is met at the lowest possible standard" },
        { n: 25, type: "select", prompt: "The financial case for a building's owner rests on the roof covering lasting longer.", options: ["Hanna Reuter", "Marek Dolinski", "Ines Carvalho"], answer: "Hanna Reuter", explain: "Reuter's view is that the longer life of the covering, rather than any saving on cooling, is what makes the sums work for an owner.", evidence: "the longer life of the covering, rather than any saving on cooling, is what makes the sums work" },
        { n: 26, type: "select", prompt: "Building in more variety adds very little to what a roof costs to design and nothing to its upkeep.", options: ["Hanna Reuter", "Marek Dolinski", "Ines Carvalho"], answer: "Ines Carvalho", explain: "Carvalho argues the extra depth costs little at the design stage and nothing at all afterwards.", evidence: "the extra depth costs little at the design stage and nothing at all afterwards" },
      ],
    },
    {
      title: "Passage 3",
      instructions: "You should spend about 20 minutes on Questions 27–40, which are based on Reading Passage 3 below.",
      passageTitle: "Why we misjudge risk",
      passage: `Ask people to name the things most likely to kill them and the answers will be wrong in a consistent direction. Aeroplane crashes, shark attacks and violent crime are named far more often than they deserve; heart disease, falls in the home and the slow effects of a poor diet are named far less. The pattern is so regular that it cannot be explained by ignorance alone. Something about the way people estimate frequency is systematically tilted, and understanding the tilt turns out to matter a good deal for anyone who has to communicate about danger.

The first and best-supported explanation is that people judge how common something is by how easily an example comes to mind. This shortcut is usually sensible: common events genuinely are easier to recall than rare ones, and a mind that has no time to consult statistics can do worse than ask itself whether it can think of an instance. The trouble is that ease of recall depends on more than frequency. It depends on how recently something happened, how vividly it was described, and above all on whether it was reported. A death in an air crash is described in detail by every news outlet on earth; a death from heart disease is not reported at all, being one of many thousands that day. The mind, asked for an estimate, faithfully reports what it can retrieve, and what it can retrieve is a record of what was memorable rather than what was common.

A second factor is that not all risks feel alike, even when the numbers are identical. Research beginning in the 1970s established that people's sense of how bad a hazard is depends on a small number of qualities that have nothing to do with the death rate. A risk feels worse if it is involuntary — imposed rather than chosen. It feels worse if it is unfamiliar, if its effects are delayed, if it could produce many deaths at once rather than the same number spread over a year, and if the person exposed has no control over the outcome. Driving scores low on almost every one of these: it is chosen, familiar, immediate, distributed, and the driver holds the wheel. Flying scores high on all of them. On the numbers, flying is the safer activity by a wide margin; on these other qualities it is far more frightening, and people's behaviour follows the qualities rather than the numbers.

It is tempting to conclude that the public is simply irrational and should be corrected with better statistics. Several researchers argue that this reading is too quick. Some of the qualities that make a risk feel worse are reasonable things to care about. An accident that kills three hundred people at once damages a community in a way that three hundred separate accidents do not; a hazard imposed on someone without their consent raises a question of fairness that a freely chosen one does not. What looks like an error in arithmetic may be a judgement about something other than arithmetic. On this view the public is not miscounting deaths so much as counting other things as well, and telling people they are wrong about the numbers misses what they are actually objecting to.

Whichever reading is right, the practical consequences are not in doubt. Attention is finite, and effort spent on a vivid small risk is effort not spent on a dull large one. The clearest demonstrations come from what people do after a widely reported disaster. In the months following the attacks of September 2001, many Americans avoided flying and drove instead; because road travel carries a higher risk per kilometre than air travel, several analyses estimate that the additional road deaths over the following year exceeded a thousand — more than the number killed on the four aircraft. Nobody made this trade knowingly. Each traveller simply chose the option that felt safer, and the sum of those choices produced a cost invisible to every individual making it.

What, then, can be done? The instinctive answer — publish the real figures — helps less than expected, partly because large numbers are hard to feel and partly because a statistic arrives without the vividness that made the rival example memorable. Communicators have had more success with comparisons anchored in ordinary experience: expressing a risk as so many kilometres driven, or as a change in the days of life expected, rather than as a probability with several zeros after the decimal point. Presenting the same information as a frequency out of a hundred people, rather than as a percentage, also produces markedly better reasoning, apparently because a hundred people is something the mind can picture and a decimal is not.

None of this makes the tilt disappear. The shortcut that produces it is not a defect that education removes but a feature of a mind built to act quickly on incomplete information, and it operates in the people who study it as readily as in anyone else. The realistic goal is narrower: to notice which risks are being amplified by attention and which are being hidden by familiarity, and to design the choices that matter — where a hospital spends its money, how a road is laid out — so that they do not depend on an intuition that is known in advance to point the wrong way.`,
      questions: [
        { n: 27, type: "mcq", prompt: "What does the writer say about the pattern of mistakes people make in judging risk?", options: ["A It occurs too consistently to be blamed on a simple lack of knowledge.", "B It is confined to hazards that receive news coverage.", "C It has grown more pronounced as reporting has increased.", "D It disappears once people are shown the relevant figures."], answer: "A", explain: "The writer says the pattern is so regular that it cannot be explained by ignorance alone — option A paraphrases 'so regular' as 'too consistently' and 'ignorance' as 'a simple lack of knowledge'.", evidence: "The pattern is so regular that it cannot be explained by ignorance alone" },
        { n: 28, type: "mcq", prompt: "According to the passage, why is judging frequency by ease of recall normally a reasonable strategy?", options: ["A Vivid events are usually the most dangerous ones.", "B Things that happen often really are easier to remember.", "C People rarely have access to reliable statistics.", "D The mind recalls recent events more accurately than old ones."], answer: "B", explain: "The passage says the shortcut is usually sensible because common events genuinely are easier to recall than rare ones.", evidence: "common events genuinely are easier to recall than rare ones", vocab: ["common events", "things that happen often"] },
        { n: 29, type: "mcq", prompt: "What point does the writer make by contrasting driving with flying?", options: ["A Familiar activities are usually more dangerous than unfamiliar ones.", "B People's choices track the character of a hazard rather than its death rate.", "C Drivers underestimate how much control they actually have.", "D Risks that are chosen freely tend to be reported less often."], answer: "B", explain: "After listing the qualities on which driving and flying differ, the writer says people's behaviour follows the qualities rather than the numbers.", evidence: "people's behaviour follows the qualities rather than the numbers" },
        { n: 30, type: "mcq", prompt: "Why does the writer mention travel in the months after September 2001?", options: ["A To show that official warnings can make a risk worse.", "B To illustrate how quickly public fear subsides.", "C To demonstrate that avoiding one risk can create a larger one unnoticed.", "D To argue that road safety was neglected during that period."], answer: "C", explain: "The example shows travellers choosing what felt safer and producing over a thousand extra road deaths — a cost invisible to every individual making the choice.", evidence: "the sum of those choices produced a cost invisible to every individual making it" },
        { n: 31, type: "ynng", prompt: "The writer accepts that some of the qualities making a hazard feel worse are worth caring about.", answer: "YES", explain: "YES: the writer states that some of the qualities that make a risk feel worse are reasonable things to care about, giving the examples of concentrated deaths and consent.", evidence: "Some of the qualities that make a risk feel worse are reasonable things to care about" },
        { n: 32, type: "ynng", prompt: "The writer believes the public should simply be given more accurate statistics.", answer: "NO", explain: "NO: the writer calls the instinctive answer of publishing the real figures less helpful than expected, and says correcting the public is 'too quick' a reading.", evidence: "The instinctive answer — publish the real figures — helps less than expected" },
        { n: 33, type: "ynng", prompt: "Expressing a risk as a frequency out of a hundred people improves how well people reason about it.", answer: "YES", explain: "YES: the passage says presenting information as a frequency out of a hundred rather than a percentage produces markedly better reasoning.", evidence: "produces markedly better reasoning" },
        { n: 34, type: "ynng", prompt: "Researchers who study these shortcuts are themselves protected from them.", answer: "NO", explain: "NO: the writer says the shortcut operates in the people who study it as readily as in anyone else.", evidence: "it operates in the people who study it as readily as in anyone else" },
        { n: 35, type: "ynng", prompt: "News organisations have deliberately changed how they report rare disasters.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage describes how reporting affects recall, but says nothing about news organisations changing their practices.", evidence: "A death in an air crash is described in detail by every news outlet on earth" },
        { n: 36, type: "ynng", prompt: "The tilt in risk judgement can be removed by education.", answer: "NO", explain: "NO: the writer says the shortcut is not a defect that education removes but a feature of the mind.", evidence: "not a defect that education removes but a feature of a mind" },
        { n: 37, type: "select", prompt: "Complete the sentence: A hazard feels more threatening when the person exposed to it", options: ["has no say over whether they face it.", "has encountered it many times before.", "sees its effects immediately.", "shares it with very few others."], answer: "has no say over whether they face it.", explain: "The passage says a risk feels worse if it is involuntary — imposed rather than chosen — and if the person has no control over the outcome.", evidence: "A risk feels worse if it is involuntary — imposed rather than chosen", vocab: ["involuntary", "has no say"] },
        { n: 38, type: "select", prompt: "Complete the sentence: Deaths from heart disease are underestimated largely because they", options: ["are not individually reported.", "happen mainly to older people.", "develop over many years.", "are difficult for doctors to record."], answer: "are not individually reported.", explain: "The passage says a death from heart disease is not reported at all, being one of many thousands that day.", evidence: "a death from heart disease is not reported at all" },
        { n: 39, type: "select", prompt: "Complete the sentence: Some researchers argue that the public's response to risk reflects", options: ["a concern with matters beyond the death toll.", "a misunderstanding of basic arithmetic.", "the influence of recent news coverage.", "an unwillingness to accept expert advice."], answer: "a concern with matters beyond the death toll.", explain: "The passage says the public is not miscounting deaths so much as counting other things as well.", evidence: "not miscounting deaths so much as counting other things as well" },
        { n: 40, type: "select", prompt: "Complete the sentence: The writer's realistic aim is to make important decisions", options: ["independent of an intuition known to mislead.", "subject to public consultation.", "based on the vividness of each hazard.", "reviewed whenever a disaster occurs."], answer: "independent of an intuition known to mislead.", explain: "The closing sentence calls for designing the choices that matter so they do not depend on an intuition known in advance to point the wrong way.", evidence: "so that they do not depend on an intuition that is known in advance to point the wrong way" },
      ],
    },
  ],
};
