// Smart LC Pre-IELTS Set 8 — Academic Reading (40 questions, 3 passages).
// Original material authored for Smart LC to the blueprint: P1 factual
// history (completion + TFNG), P2 discursive with lettered paragraphs
// (matching paragraph-information + summary + people matching with one
// extra name), P3 argumentative (MCQ-4 + YNNG + wordlist summary).
// Key quotas: TFNG/YNNG balanced with no runs of three, flat letters,
// unique concrete-noun answers, correct MCQ options paraphrase the text
// while distractors echo its wording.
export const UPSET8_READING = {
  id: "upset8-reading",
  bookId: "upset8",
  title: "Pre-IELTS Set 8 — Reading",
  module: "reading",
  durationMin: 60,
  sections: [
    {
      title: "Passage 1",
      instructions: "You should spend about 20 minutes on Questions 1–13, which are based on Reading Passage 1 below.",
      passageTitle: "Older than the alphabet: a history of board games",
      passage: `People were pushing counters around boards long before they could write about it. Archaeologists have found game boards scratched into the stone benches of ancient gateways, carved into temple roofs, packed into merchants' luggage and buried beside kings. Give human beings a flat surface, a handful of pebbles and an opponent, it seems, and a game will follow. Board games are among the oldest surviving artefacts of organised leisure, and they are also among the most revealing: follow their history and you trace changing ideas about luck, war, morality and, eventually, mass production.

The oldest games we can still recognise come from the river valleys of Egypt and Mesopotamia. The Egyptian favourite was Senet, a race game played on a grid of thirty squares, in which two players moved their pieces according to throws of flat casting sticks. Boards for Senet have been found in Egyptian tombs, including that of Tutankhamun, who was buried with four of them, and wall paintings show both labourers and queens absorbed in play. Over the centuries the game gathered religious weight: crossing the board came to stand for the soul's dangerous journey into the afterlife, and a board in the grave was equipment for that journey. Mesopotamia's masterpiece was the Royal Game of Ur, named after the city where beautifully inlaid boards of shell and coloured stone were excavated from a royal cemetery; the game is around 4,500 years old. Its rules would have remained a mystery had a museum curator in London not deciphered them from a clay tablet written by a Babylonian astronomer more than two thousand years after the game first appeared — probably the world's oldest surviving rulebook. Nor was the game reserved for palaces: boards scratched by bored guards into the stone slabs of city gateways show that ordinary soldiers played it too.

Asia produced the great games of strategy. Go, played with black and white stones on a wooden grid, has been played in China for well over two thousand years; its rules can be learned in minutes, yet its possibilities are so vast that players study it for a lifetime. Chess had a later and better-documented birth. It emerged in India around the sixth century AD as a game representing an army, with pieces for infantry, cavalry, chariots and elephants. Merchants and conquerors carried it westwards into Persia, where players learned to announce an attack on the enemy's most important piece with a warning cry; our word 'checkmate' descends from a Persian expression describing a helpless king. Arab scholars wrote the first collections of chess problems, and by the year 1000 the game had spread across Europe. For centuries it remained slow and stately. Then, at the end of the fifteenth century in southern Europe, the rules were dramatically revised: the feeblest piece on the board was granted sweeping new powers of movement and became the queen, the strongest — a change some historians connect with the powerful reigning queens of the period. The faster game swept the old one aside within a generation, and modern chess was born.

Games have always been used to teach as well as to amuse. In India, a game of ladders and snakes carried an openly spiritual lesson: the ladders stood for virtues such as generosity and faith, which raised the player towards liberation, while the snakes were vices that dragged the soul back down through rebirth. When British families adopted it in the nineteenth century as Snakes and Ladders, the vices and virtues were relabelled to suit Victorian nurseries — industry lifted a child upwards, idleness slid them back. The same century industrialised the pastime itself. A printing technique called lithography made cheap colour reproduction possible for the first time, and boards that had once been painted by hand could suddenly be produced by the thousand. Publishers competed to sound improving: their games taught geography, history and household economy, and the box lid promised parents that the family's fun would not be wasted time.

The twentieth century turned games into big business, and a handful of family titles sold in the tens of millions to become fixtures of domestic life. But near the century's end the hobby was quietly reinvented in Germany, where designers began producing games with short, clear rules, play lasting under an hour, no player eliminated before the end, and victory decided more by planning than by dice. These designs found an international audience, and the designers' names on the box — a novelty in itself, since game inventors had traditionally been anonymous — began to sell copies the way authors' names sell novels.

The digital age was widely expected to finish the board game off; instead, it has presided over a revival. Sales have risen year after year for roughly two decades, dedicated board-game cafes have opened in cities from Toronto to Seoul, and thousands of new titles are financed annually by their future players through online crowdfunding. Part of the attraction is precisely what a screen cannot supply: a board game must be played face to face, at one table and at one speed, by people who can see each other think. Five thousand years after Senet, the world's oldest social technology is doing rather well.`,
      questions: [
        { n: 1, type: "gap", prompt: "Boards for Senet have been discovered in Egyptian ______, including Tutankhamun's.", note: "ONE WORD ONLY", answer: "tombs", explain: "The second paragraph states this directly: Senet boards have been found in Egyptian tombs, and Tutankhamun was buried with four of them.", evidence: "Boards for Senet have been found in Egyptian tombs" },
        { n: 2, type: "gap", prompt: "The rules of the Royal Game of Ur were worked out from a clay ______ written by an astronomer.", note: "ONE WORD ONLY", answer: "tablet", explain: "'Worked out' in the question paraphrases 'deciphered' in the passage: a London curator deciphered the rules from a clay tablet by a Babylonian astronomer.", evidence: "deciphered them from a clay tablet written by a Babylonian astronomer", vocab: ["deciphered", "worked out"] },
        { n: 3, type: "gap", prompt: "Chess originally portrayed an ______, complete with chariots and elephants.", note: "ONE WORD ONLY", answer: "army", explain: "'Portrayed' in the question paraphrases 'representing' in the passage: chess emerged in India as a game representing an army with four kinds of pieces.", evidence: "as a game representing an army", vocab: ["representing", "portrayed"] },
        { n: 4, type: "gap", prompt: "The word 'checkmate' comes from a Persian expression about a helpless ______.", note: "ONE WORD ONLY", answer: "king", explain: "The passage explains the word's origin: 'checkmate' descends from a Persian expression describing a helpless king — the enemy's most important piece.", evidence: "a Persian expression describing a helpless king" },
        { n: 5, type: "gap", prompt: "Chess became a much faster game after new powers were given to the ______.", note: "ONE WORD ONLY", answer: "queen", explain: "At the end of the fifteenth century the feeblest piece was granted sweeping new powers and became the queen, and the faster game replaced the old one.", evidence: "granted sweeping new powers of movement and became the queen" },
        { n: 6, type: "gap", prompt: "In the Indian original, ladders represented ______ that raised the player upwards.", note: "ONE WORD ONLY", answer: "virtues", explain: "'Represented' in the question paraphrases 'stood for' in the passage: the ladders stood for virtues such as generosity and faith, which raised the player.", evidence: "the ladders stood for virtues such as generosity and faith", vocab: ["stood for", "represented"] },
        { n: 7, type: "gap", prompt: "Colour boards could be produced cheaply for the first time thanks to a printing method called ______.", note: "ONE WORD ONLY", answer: "lithography", explain: "The passage names the technique: lithography made cheap colour reproduction possible, so hand-painted boards could suddenly be produced by the thousand.", evidence: "A printing technique called lithography made cheap colour reproduction possible" },
        { n: 8, type: "tfng", prompt: "Some Senet boards were buried with the dead for use in the next world.", answer: "TRUE", explain: "TRUE: crossing the board stood for the soul's journey into the afterlife, and a board placed in the grave was equipment for that journey.", evidence: "a board in the grave was equipment for that journey", vocab: ["the afterlife", "the next world"] },
        { n: 9, type: "tfng", prompt: "Only members of royal families played the Royal Game of Ur.", answer: "FALSE", explain: "FALSE: the passage directly contradicts this — boards scratched into city gateways by bored guards show that ordinary soldiers played it too.", evidence: "ordinary soldiers played it too" },
        { n: 10, type: "tfng", prompt: "Go was introduced to Europe earlier than chess.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage says Go was played in China and traces chess's route to Europe, but never says when, or whether, Go reached Europe.", evidence: "has been played in China for well over two thousand years" },
        { n: 11, type: "tfng", prompt: "The modern form of chess appeared at the end of the fifteenth century.", answer: "TRUE", explain: "TRUE: the rules were dramatically revised in southern Europe at the end of the fifteenth century, and the passage says modern chess was born then.", evidence: "the rules were dramatically revised" },
        { n: 12, type: "tfng", prompt: "Victorian publishers presented their games as pure entertainment.", answer: "FALSE", explain: "FALSE: the opposite is stated — publishers competed to sound improving, and their games taught geography, history and household economy.", evidence: "Publishers competed to sound improving" },
        { n: 13, type: "tfng", prompt: "Interest in board games has grown during the digital era.", answer: "TRUE", explain: "TRUE: instead of killing the hobby, the digital age has presided over a revival, with sales rising year after year for about two decades.", evidence: "Sales have risen year after year for roughly two decades", vocab: ["risen year after year", "grown"] },
      ],
    },
    {
      title: "Passage 2",
      instructions: "You should spend about 20 minutes on Questions 14–26, which are based on Reading Passage 2 below.",
      passageTitle: "The cooperative behind the wheel",
      passage: `A — The private car is an oddly wasteful possession. It is, after the home, the most expensive thing most households ever buy, yet the average car spends about ninety-five per cent of its life parked and doing nothing, quietly losing value in the rain. For a century the standard response to this arithmetic was to ignore it. Over the past few decades, however, millions of drivers have joined car-sharing schemes of one kind or another, paying for cars by the hour instead of owning them outright. Alongside the commercial operators, with their bright logos and venture capital, stands an older and quieter model: the car-sharing cooperative, a fleet owned not by a company but by the very people who drive it.

B — The idea long predates the smartphone. In Zurich in 1948, a group of residents who could not each afford a vehicle of their own formed a cooperative to buy and share cars, booking them in a paper diary and collecting the key from a hook in a shared stairwell. Similar clubs appeared and disappeared across post-war Europe. The modern movement took shape in Switzerland and Germany in the late 1980s, when small neighbourhood groups discovered one another and began to merge; today the largest Swiss operator is a cooperative with well over one hundred thousand members, and member-owned fleets run in cities across Europe and North America.

C — What distinguishes a cooperative from a commercial operator is not technology — both sides use booking apps, smart locks and telematics — but ownership. A cooperative is owned by its members: each buys a share to join, and each has a single vote at the annual meeting, whether they drove five hundred hours last year or five. Decisions about tariffs, new vehicles and new locations are taken by a board the members elect, and any surplus is not paid out to outside investors but returned to the fleet as newer cars, more parking bays and cheaper rates. The transport economist Lena Vogel sees this structure as a natural fit for the underlying economics. 'A car is the second-largest purchase most households make, and it is idle almost all its life,' she notes. 'Paying by the hour turns an expensive possession into a cheap service. A cooperative simply makes sure the savings stay with the drivers.'

D — The behavioural effects are measurable. The transport researcher Marco Ribeiro followed two thousand households for three years after they joined urban cooperatives. On average, he found, each cooperative car had replaced eleven privately owned vehicles, as members sold cars they rarely used or shelved plans to buy one. Driving itself changed even more: members covered roughly forty per cent fewer kilometres than before joining, walked and cycled more, and reserved a car only for the journeys that genuinely required one — the bulk shopping trip, the visit to relatives in the country. 'When every trip has a visible price,' Ribeiro writes, 'people discover how many trips they never really needed to make.' Owning a car invites you to use it; borrowing one invites you to think.

E — Commercial operators concentrate where the sums are safest: dense city districts where each vehicle is booked many times a day. They are unwilling to place cars in villages and small towns, where a car might sit untouched from Monday to Friday. Yet it is precisely there that the cooperative version has proved most resilient. Ingrid Halvorsen, who studies rural transport, has documented dozens of village car-sharing schemes in Norway and Scotland: typically two or three cars parked beside the community hall, insured collectively and administered by volunteers on a rota. 'What looks like a marginal market to a company is a lifeline to a village,' she observes. In several of the communities she studied, the shared cars allowed older residents to give up vehicles of their own years earlier than planned, without losing their access to hospitals, shops and grandchildren.

F — None of this makes the cooperative invulnerable. Insurance premiums have climbed steeply; venture-funded rivals can sell below cost for years while they chase market share; and members raised on polished commercial apps expect the same finish from an organisation run partly by volunteers. Yet the historian of the cooperative movement Peter Aldridge is unsurprised that the model persists, pointing to a pattern repeated across two centuries of cooperative shops, banks and dairies: such enterprises grow slowly, but they are remarkably hard to kill. 'Customers leave the moment a cheaper offer appears,' he says. 'Members stay, because the thing being kept alive is partly theirs.' The policy adviser Sofia Duran argues that local government could tip the balance, urging councils to reserve on-street parking bays for shared vehicles and to write car-sharing into their transport plans. Whether or not that happens, the cooperative car club has already made its quiet point: transport can be owned like a library rather than sold like a luxury.`,
      questions: [
        { n: 14, type: "match", group: "minfo", letters: "ABCDEF",
          rubric: "Reading Passage 2 has six paragraphs, A–F. Which paragraph contains the following information? Write the correct letter, A–F. NB You may use any letter more than once.",
          prompt: "a description of how decisions are taken within a cooperative", answer: "C",
          explain: "Paragraph C explains the governance: each member has a single vote at the annual meeting, and an elected board decides tariffs, vehicles and locations.",
          evidence: "each has a single vote at the annual meeting" },
        { n: 15, type: "match", group: "minfo", prompt: "a figure showing how little the typical private car is actually used", answer: "A", explain: "Paragraph A gives the statistic: the average car spends about ninety-five per cent of its life parked, quietly losing value while it stands.", evidence: "ninety-five per cent of its life parked and doing nothing", vocab: ["parked and doing nothing", "little used"] },
        { n: 16, type: "match", group: "minfo", prompt: "examples of places where commercial operators choose not to work", answer: "E", explain: "Paragraph E states that commercial firms are unwilling to place cars in villages and small towns, where a vehicle might stand idle for days.", evidence: "unwilling to place cars in villages and small towns", vocab: ["unwilling", "choose not to"] },
        { n: 17, type: "match", group: "minfo", prompt: "research results showing changes in how members travel", answer: "D", explain: "Paragraph D reports Ribeiro's findings: members drove roughly forty per cent fewer kilometres, walked and cycled more, and booked cars more selectively.", evidence: "covered roughly forty per cent fewer kilometres" },
        { n: 18, type: "gap", group: "sum2", note: "ONE WORD ONLY",
          notes: {
            title: "Summary — How a cooperative differs",
            lines: [
              "A car-sharing cooperative belongs to its {{18}}, each of whom holds a share and casts one {{19}} at the annual meeting, however much or little they drive.",
              "Surpluses are not distributed to outside {{20}}; they are returned to the fleet as newer cars and lower rates.",
              "The economist Lena Vogel argues that paying by the hour turns a costly possession into a cheap {{21}},",
              "and research by Marco Ribeiro shows members reserve cars only for the {{22}} that truly need one, walking and cycling more instead.",
            ],
          },
          answer: "members",
          explain: "'Belongs to' in the summary paraphrases 'is owned by' in the passage: a cooperative is owned by its members, who each buy a share to join.",
          evidence: "A cooperative is owned by its members", vocab: ["owned by", "belongs to"] },
        { n: 19, type: "gap", group: "sum2", answer: "vote", explain: "Every member has exactly one vote at the annual meeting, whether they drove five hundred hours last year or five — usage makes no difference.", evidence: "each has a single vote at the annual meeting" },
        { n: 20, type: "gap", group: "sum2", answer: "investors", explain: "'Distributed' in the summary paraphrases 'paid out' in the passage: any surplus is not paid out to outside investors but returned to the fleet.", evidence: "not paid out to outside investors", vocab: ["paid out", "distributed"] },
        { n: 21, type: "gap", group: "sum2", answer: "service", explain: "Vogel's phrase supplies the noun: paying by the hour turns an expensive possession into a cheap service; 'costly' in the summary paraphrases 'expensive'.", evidence: "turns an expensive possession into a cheap service", vocab: ["expensive", "costly"] },
        { n: 22, type: "gap", group: "sum2", answer: "journeys", explain: "'Truly need' in the summary paraphrases 'genuinely required': members reserved a car only for the journeys that genuinely required one.", evidence: "only for the journeys that genuinely required one", vocab: ["genuinely required", "truly need"] },
        { n: 23, type: "match", group: "people", boxTitle: "List of People",
          box: [
            "Marco Ribeiro",
            "Peter Aldridge",
            "Lena Vogel",
            "Ingrid Halvorsen",
            "Sofia Duran",
          ],
          rubric: "Look at the following statements (Questions 23–26) and the list of people below. Match each statement with the correct person, A–E. NB There is one more person than you need.",
          prompt: "A machine that mostly stands unused is a poor way to spend money.", answer: "C",
          explain: "Vogel makes the economic point: a car is the second-largest purchase most households make, yet it is idle almost all its life.",
          evidence: "it is idle almost all its life" },
        { n: 24, type: "match", group: "people", prompt: "Putting a price on each trip changes people's decisions about travelling.", answer: "A", explain: "Ribeiro writes that when every trip has a visible price, people discover how many trips they never really needed to make at all.", evidence: "people discover how many trips they never really needed to make", vocab: ["a visible price", "a price"] },
        { n: 25, type: "match", group: "people", prompt: "Schemes can matter most in exactly the places firms find unprofitable.", answer: "D", explain: "Halvorsen contrasts the two views of rural schemes: a marginal market to a company, but a lifeline to the village that runs them.", evidence: "a marginal market to a company is a lifeline to a village", vocab: ["a lifeline", "matter most"] },
        { n: 26, type: "match", group: "people", prompt: "Part-owners stay committed where ordinary customers would walk away.", answer: "B", explain: "Aldridge draws the distinction: customers leave when a cheaper offer appears, but members stay because the organisation is partly their own property.", evidence: "the thing being kept alive is partly theirs", vocab: ["Members stay", "stay committed"] },
      ],
    },
    {
      title: "Passage 3",
      instructions: "You should spend about 20 minutes on Questions 27–40, which are based on Reading Passage 3 below.",
      passageTitle: "Why the years accelerate",
      passage: `Ask a child how long a year lasts and the answer, in effect, is 'forever': the gap between one birthday and the next is an ocean of time. Ask a sixty-year-old and the same interval has shrunk to a brisk walk between one December and the next. The feeling that time moves faster as we age is one of the most widely shared observations about human experience: it turns up in surveys of every age group, and in diaries and letters from every century that has left us any. As early as 1890 the psychologist William James was noting that the years seem to contract as life goes on, each one emptier of the 'firsts' that once filled them. The complaint is so familiar that it is easy to miss how strange it is. Clocks do not run faster for the old. What, exactly, is speeding up?

The oldest answer is arithmetical. In 1877 the French philosopher Paul Janet proposed that we feel duration as a proportion of the life we have already lived. To a ten-year-old, a year is a tenth of everything; to a fifty-year-old, it is a fiftieth, and so the years genuinely should seem to shrink as their relative weight falls. The idea is appealingly neat, and it matches the broad curve of the complaint. The difficulty is that it says almost nothing about experience. Nobody perceives a year as a fraction of their biography; we live it as mornings, queues, conversations and meals. Nor can the formula explain why time is lumpy — why a dull February can vanish without trace while one eventful week abroad looms in memory like a whole season. A tidy equation, critics conclude, is not the same thing as a mechanism.

A more productive approach separates time as it is lived from time as it is remembered, because the two routinely disagree. Psychologists call the clearest case the holiday paradox. A week somewhere unfamiliar races by while it is happening, yet in memory it stretches, crowded with detail; a fortnight of ordinary work does the opposite, dragging at the desk and then collapsing to almost nothing when we look back. The explanation lies in how retrospection works. Looking back, we do not consult a stopwatch; we estimate a period by the number of distinct memories it left behind. Novelty is the raw material of such memories: first days, new streets and unfamiliar faces are recorded in dense detail, while the three-hundredth commute leaves no trace at all. Childhood is one long sequence of first times, which is why it occupies such enormous space in the remembered past. Adult life, by contrast, settles into routine, and routine is a kind of amnesia: the weeks are full while they happen and empty in the retelling. On this account the years do not accelerate at all — they are simply recorded at ever lower resolution.

Biology may contribute too. The brain contains no single clock, but it has networks that behave like one, and their pace appears to change with age. In one much-repeated experiment, volunteers are asked to say when three minutes have passed while counting silently to themselves. Young adults tend to stop close to the mark, while people in their sixties often let significantly more time slip by before calling out — as though an internal pacemaker had slowed, so that the world streams past a slower drumbeat. Some researchers connect this with the gradual decline of dopamine, a brain chemical central to the circuits with which we track short intervals. A slowing inner clock would make external events appear to flow faster, which is at least consistent with the universal complaint.

These laboratory results, however, should be handled with care. The tasks involve intervals of seconds or minutes, far shorter than the years about which people actually complain, and there is no guarantee that the mechanisms scale up. Retrospective judgements bring their own distortions: someone asked how fast the last decade felt is also being asked, implicitly, how memorable their life has been, and few people answer that question coldly. And the acceleration is not universal: studies find the effect strongest when people judge long spans — years and decades — and weak or absent for short ones, since an ordinary afternoon feels much the same at twenty as at seventy. Any complete account has to explain that pattern, and none of the current theories does so perfectly.

Still, the candidates are not equally persuasive, and the most convincing of them is the one grounded in memory. It explains the holiday paradox, the endless summers of childhood and the vanishing Februaries of middle age with a single idea — remembered time is measured in memories — and it does so without contradicting the laboratory work. It also carries a genuinely hopeful implication: subjective time is not fixed. We cannot slow the clock, but we can thicken the record. Learn something difficult, change the route to work, go somewhere unvisited; seek novelty deliberately, and the months regain their texture. A life packed with new experiences adds nothing to the calendar, but it lengthens the past we actually possess — and that, in the end, is the only past there is.`,
      questions: [
        { n: 27, type: "mcq", prompt: "What criticism of Janet's proportional theory does the writer report?", options: ["A It does not match the broad curve of the complaint", "B It describes the pattern without explaining what people actually feel", "C It was proposed too long ago to be tested", "D It applies only to people over fifty"], answer: "B", explain: "Critics accept the neat arithmetic but object that it says almost nothing about experience. Option A echoes the passage's words while reversing what it states.", evidence: "it says almost nothing about experience" },
        { n: 28, type: "mcq", prompt: "The holiday paradox describes a period of time that", options: ["A passes slowly both during and after the event", "B is forgotten as soon as it ends", "C contains too much detail to remember", "D feels brief as it passes but long in retrospect"], answer: "D", explain: "A week somewhere unfamiliar races by while happening yet stretches in memory; the correct option paraphrases this, while the others distort or reverse it.", evidence: "races by while it is happening, yet in memory it stretches", vocab: ["races by", "feels brief"] },
        { n: 29, type: "mcq", prompt: "What reservation does the writer express about the timing experiments?", options: ["A They measure much shorter periods than the ones people complain about", "B Volunteers are rarely tested more than once", "C Older participants find counting silently difficult", "D The results have never been repeated"], answer: "A", explain: "The tasks involve seconds or minutes, far shorter than years and decades, and the mechanisms may not scale up. Option D contradicts 'much-repeated experiment'.", evidence: "intervals of seconds or minutes, far shorter than the years", vocab: ["handled with care", "reservation"] },
        { n: 30, type: "mcq", prompt: "In the final paragraph, the writer concludes that", options: ["A subjective time cannot be altered", "B childhood memories become less reliable with age", "C deliberately seeking new experiences lengthens remembered time", "D the timing experiments disprove the memory account"], answer: "C", explain: "The closing advice is to seek novelty so that the months regain their texture: new experiences lengthen the past we possess in memory.", evidence: "seek novelty deliberately, and the months regain their texture", vocab: ["novelty", "new experiences"] },
        { n: 31, type: "ynng", prompt: "The sense that time accelerates with age is reported by many different groups of people.", answer: "YES", explain: "YES: the writer calls it one of the most widely shared observations, appearing in surveys of every age group and in writing from every century.", evidence: "one of the most widely shared observations about human experience", vocab: ["widely shared", "reported by many"] },
        { n: 32, type: "ynng", prompt: "Janet's formula fully accounts for the way time is experienced.", answer: "NO", explain: "NO: the writer reports and endorses the criticism that the formula is a description, not a mechanism — a tidy equation that explains nothing about experience.", evidence: "A tidy equation, critics conclude, is not the same thing as a mechanism" },
        { n: 33, type: "ynng", prompt: "Modern technology has made time seem to pass more quickly.", answer: "NOT GIVEN", explain: "NOT GIVEN: the writer blames adult routine and memory density for the effect, but never mentions technology or its influence on how fast time feels.", evidence: "Adult life, by contrast, settles into routine" },
        { n: 34, type: "ynng", prompt: "The writer regards the memory-based explanation as the strongest available.", answer: "YES", explain: "YES: 'strongest' paraphrases 'most convincing' — of the candidate theories, the writer picks the one grounded in memory as the most persuasive.", evidence: "the most convincing of them is the one grounded in memory", vocab: ["most convincing", "strongest"] },
        { n: 35, type: "ynng", prompt: "The writer believes nothing can change how long life feels in memory.", answer: "NO", explain: "NO: the writer states the opposite — subjective time is not fixed, and seeking novelty thickens the record and lengthens the remembered past.", evidence: "subjective time is not fixed" },
        { n: 36, type: "gap", group: "wl",
          box: ["routine", "memories", "novelty", "proportion", "childhood", "attention", "clocks", "evidence", "adulthood"],
          boxTitle: "List of Words",
          notes: {
            title: "Summary — Why time seems to speed up",
            lines: [
              "As we age, each year forms a smaller {{36}} of the life we have lived, though this arithmetic explains little by itself.",
              "Looking back, we judge the length of a period by the {{37}} it left behind,",
              "and adult life, dominated by {{38}}, leaves very few.",
              "First experiences are recorded in unusual detail, which is why {{39}} takes up so much space in the remembered past.",
              "The writer's advice is to pursue {{40}}: it cannot slow the clock, but it thickens the record.",
            ],
          },
          answer: "D",
          explain: "Janet's theory is the arithmetic in question: we feel duration as a proportion of the life already lived, so each new year weighs less.",
          evidence: "we feel duration as a proportion of the life we have already lived" },
        { n: 37, type: "gap", group: "wl", answer: "B", explain: "Retrospection uses no stopwatch: we estimate a period by the number of distinct memories it left, so 'memories' is the noun the summary needs.", evidence: "we estimate a period by the number of distinct memories it left behind" },
        { n: 38, type: "gap", group: "wl", answer: "A", explain: "Adult life settles into routine, which the writer calls a kind of amnesia — full weeks that leave almost nothing behind in memory.", evidence: "settles into routine, and routine is a kind of amnesia" },
        { n: 39, type: "gap", group: "wl", answer: "E", explain: "'First experiences' in the summary paraphrases 'first times' in the passage: childhood is one long sequence of them, so it dominates remembered time.", evidence: "Childhood is one long sequence of first times", vocab: ["first times", "first experiences"] },
        { n: 40, type: "gap", group: "wl", answer: "C", explain: "The advice is to seek novelty deliberately; the clock cannot be slowed, but the record can be thickened with new, memorable experiences.", evidence: "We cannot slow the clock, but we can thicken the record" },
      ],
    },
  ],
};
