// Smart LC Upper-Inter Set 10 — Academic Reading (40 questions, 3 passages).
// Original material authored for Smart LC to the blueprint: P1 factual
// history (completion + TFNG), P2 discursive with lettered paragraphs
// (matching paragraph-information + summary + people matching with one
// extra name), P3 argumentative psychology (MCQ-4 + YNNG + wordlist
// summary). Key quotas: TFNG/YNNG balanced with no runs of three, flat
// letters, unique concrete-noun answers, correct MCQ options paraphrase
// the text while distractors echo its wording.
export const UPSET10_READING = {
  id: "upset10-reading",
  bookId: "upset10",
  title: "Upper-Inter Set 10 — Reading",
  module: "reading",
  durationMin: 60,
  sections: [
    {
      title: "Passage 1",
      instructions: "You should spend about 20 minutes on Questions 1–13, which are based on Reading Passage 1 below.",
      passageTitle: "The daily record: a history of the newspaper",
      passage: `Long before the printing press, governments had already discovered the power of publishing the news themselves. From 59 BC, the Roman state produced the Acta Diurna, or 'daily acts': a bulletin of official business written out by clerks and displayed on whitened boards in the forum and other public places. Its contents ranged far beyond politics. Alongside decrees of the senate and the verdicts of the courts, the Acta recorded births, marriages and deaths, notable omens, and the results of gladiatorial games. Citizens who could read gathered round the boards; those who could not listened while somebody read aloud. Professional scribes copied the bulletins and sent them to officials and wealthy families across the empire, so that a governor on a distant frontier could follow events in the capital a few weeks after they happened. The Acta was not a newspaper in the modern sense — it had no independence of any kind — but it established an idea of remarkable durability: that a city's news could be gathered in one place, regularly, for anyone who cared to look.

The next great step was commercial rather than political. In the sixteenth century, Venice sat at the centre of Mediterranean trade, and its merchants lived or died by information: the price of pepper, the safety of a sea route, the health of a foreign king. To feed this appetite, professional writers produced handwritten sheets of news, compiled from travellers' reports and correspondents' letters and copied out again and again by teams of scribes. According to a durable tradition, a sheet was sold for a small coin known as a gazetta, and the coin's name gradually attached itself to the product: 'gazette' survives as a name for a newspaper in many languages to this day. The Venetian sheets were quick, irregular and frequently wrong, but they demonstrated something new — that news itself could be a commodity, gathered and sold for profit like cloth or spice.

Printing turned this trade into an industry. In Strasbourg in 1605, a dealer in news named Johann Carolus had a modest business copying newsletters by hand for a circle of wealthy subscribers. Copying was slow, and every additional customer meant hours of extra labour; so Carolus bought a printing workshop and, instead of copying his weekly newsletter, printed it. His publication is generally regarded as the world's first printed weekly, and the model spread with extraordinary speed: within half a century, printed weeklies were appearing in German, Dutch and English cities. The early papers were sober productions — dense columns of foreign dispatches, printed in the order the letters arrived, with no headlines and no comment — but they came out regularly, and regularity changed their readers. For the first time, ordinary people could expect the news.

In England, the young press soon collided with the state. Alarmed by the trade in printed opinion, Parliament imposed a stamp duty on newspapers in 1712: every legal copy had to carry a red tax stamp, and the charge was raised repeatedly over the following century. Campaigners against the duty called it a 'tax on knowledge', and its effect was precisely what its authors intended: with the tax added, a daily paper cost more than most working people could possibly pay. Readers responded by sharing. A single copy bought by a London coffee house might be read, or heard, by dozens of customers in a day, and papers were passed from hand to hand until they fell to pieces.

The nineteenth century removed, one by one, every obstacle standing between the press and a mass public. In 1814, The Times of London was printed for the first time on a press driven by steam — the first newspaper in the world to be produced this way — and output leapt from a few hundred sheets an hour to more than a thousand. A little later, the electric telegraph abolished distance: a battle, a shipwreck or a market crash could now reach an editor's desk within hours rather than weeks, and news agencies were founded whose entire business was to collect reports by wire and sell them to any paper that would pay.

Costs fell as quickly as speed rose. Britain abolished the stamp duty in 1855, and cheap paper made from wood pulp replaced the costly kind made from rags. A newspaper could now be sold for a penny and still enrich its owner, because much of its income came from advertising rather than from the cover price. Publishers chased circulation with everything they had — bold headlines, illustrations, interviews, sport and crime, and boys on every corner shouting the evening edition — and by the end of the century, papers selling hundreds of thousands of copies a day were read by city crowds that state schools had only recently taught to read.

The twentieth century gave the newspaper its golden age and then, one by one, its rivals: radio could announce in seconds what a paper could not print until morning, television added moving pictures, and the internet finally separated news from paper altogether. Yet the forms the newspaper invented — the headline, the correspondent, the interview, the daily record of the world — survive inside every news application on every phone. The whitened boards of the forum have become glowing screens; the promise they make has not changed at all.`,
      questions: [
        { n: 1, type: "gap", prompt: "In Rome, official news was displayed on whitened ______ in public places.", note: "ONE WORD ONLY", answer: "boards", explain: "The opening paragraph says the Acta Diurna was written out by clerks and displayed on whitened boards in the forum and other public places.", evidence: "displayed on whitened boards in the forum" },
        { n: 2, type: "gap", prompt: "The Venetian news sheets were named after the ______ used to buy one.", note: "ONE WORD ONLY", answer: "coin", explain: "A sheet was sold for a small coin called a gazetta, and the coin's name gradually became the name of the product itself.", evidence: "sold for a small coin known as a gazetta", vocab: ["sold for", "used to buy"] },
        { n: 3, type: "gap", prompt: "Before turning to printing, Carolus had produced his newsletters by ______.", note: "ONE WORD ONLY", answer: "hand", explain: "Carolus ran a business copying newsletters by hand for wealthy subscribers before he bought a printing workshop and printed his weekly instead.", evidence: "copying newsletters by hand" },
        { n: 4, type: "gap", prompt: "Opponents of the stamp duty described it as a tax on ______.", note: "ONE WORD ONLY", answer: "knowledge", explain: "Campaigners against the duty called it a 'tax on knowledge' because it deliberately priced daily newspapers beyond ordinary readers.", evidence: "called it a 'tax on knowledge'" },
        { n: 5, type: "gap", prompt: "From 1814, The Times used a printing press powered by ______.", note: "ONE WORD ONLY", answer: "steam", explain: "'Powered by' in the question paraphrases 'driven by' in the passage: in 1814 The Times was first printed on a press driven by steam.", evidence: "printed for the first time on a press driven by steam", vocab: ["driven by", "powered by"] },
        { n: 6, type: "gap", prompt: "Thanks to the electric ______, distant events could reach an editor quickly.", note: "ONE WORD ONLY", answer: "telegraph", explain: "The electric telegraph abolished distance: battles and shipwrecks could reach an editor's desk within hours instead of weeks.", evidence: "the electric telegraph abolished distance", vocab: ["within hours", "quickly"] },
        { n: 7, type: "gap", prompt: "Penny papers were profitable because much of their income came from ______.", note: "ONE WORD ONLY", answer: "advertising", explain: "A paper could sell for a penny and still enrich its owner because advertising, not the cover price, supplied much of the income.", evidence: "income came from advertising rather than from the cover price" },
        { n: 8, type: "tfng", prompt: "The Acta Diurna included information about sporting events.", answer: "TRUE", explain: "TRUE: among its contents the Acta recorded the results of gladiatorial games, which 'sporting events' paraphrases.", evidence: "the results of gladiatorial games", vocab: ["gladiatorial games", "sporting events"] },
        { n: 9, type: "tfng", prompt: "The Venetian news sheets were produced on printing presses.", answer: "FALSE", explain: "FALSE: the sheets were handwritten and copied out again and again by teams of scribes; printing only entered the story later, with Carolus.", evidence: "professional writers produced handwritten sheets of news" },
        { n: 10, type: "tfng", prompt: "Carolus became wealthy as a result of printing his newsletter.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage says his weekly was the first printed one and that the model spread fast, but says nothing about his personal fortune.", evidence: "Carolus bought a printing workshop" },
        { n: 11, type: "tfng", prompt: "The stamp duty made daily newspapers too expensive for most workers.", answer: "TRUE", explain: "TRUE: with the tax added, a daily paper cost more than most working people could possibly pay - exactly the effect its authors intended.", evidence: "cost more than most working people could possibly pay", vocab: ["could possibly pay", "too expensive"] },
        { n: 12, type: "tfng", prompt: "Several other newspapers used steam printing before The Times adopted it.", answer: "FALSE", explain: "FALSE: the passage states The Times was the first newspaper in the world to be produced this way, so no paper used steam printing before it.", evidence: "the first newspaper in the world to be produced this way" },
        { n: 13, type: "tfng", prompt: "Early radio news was less accurate than newspaper reporting.", answer: "NOT GIVEN", explain: "NOT GIVEN: radio is compared with newspapers only for speed - announcing in seconds what papers printed next morning - never for accuracy.", evidence: "radio could announce in seconds" },
      ],
    },
    {
      title: "Passage 2",
      instructions: "You should spend about 20 minutes on Questions 14–26, which are based on Reading Passage 2 below.",
      passageTitle: "Mending things together",
      passage: `A — On a wet Saturday morning, a queue is forming outside a community hall. The people in it carry toasters, table lamps, laptops, torn trousers, a food mixer and one violin. Inside, at rows of workbenches, volunteers wait with screwdrivers, soldering irons and sewing machines. This is a repair cafe: a free gathering where visitors bring broken possessions and, instead of leaving them at a counter, sit down and mend them together with someone who knows how. Nobody pays, and the one firm rule is that the owner stays at the bench and helps. The first repair cafe opened in Amsterdam in 2009, the idea of a journalist who was troubled by how much her neighbours threw away and who began in a borrowed theatre foyer. It has since spread to more than three thousand locations in over forty countries, and organisers' records suggest that roughly two out of every three objects brought in go home working again.

B — Two generations ago such an event would have been unnecessary, because mending was simply part of life: every high street had its shoe repairer, its tailor and its television man. The economist Sofia Bergström blames an unromantic culprit for their disappearance: arithmetic. Automated factories and global supply chains have made new goods astonishingly cheap, she points out, while repair remains what it has always been - skilled local labour - and the price of an hour of such labour has risen for decades. A moulded kettle now leaves a factory for less than an hour of a trained technician's time. The result is a familiar shock at the repair counter: the quote for mending a washing machine is higher than the price of a new one. 'When repairing costs more than replacing,' Bergström says, 'no amount of guilt about waste will change what people do at the till.'

C — Cost, however, is not the whole story, because many modern products resist repair at any price. The engineer Marcus Deane, who takes consumer electronics apart for an independent testing organisation, keeps a catalogue of the obstacles he meets. Cases held together by glue instead of screws, so that opening a device means breaking it. Batteries sealed deep inside the body of a machine. Screws with heads that no ordinary screwdriver fits. And, increasingly, software locks that stop a device accepting a replacement part the manufacturer has not approved. Repair manuals are often never published, and spare parts, where they exist at all, can cost nearly as much as the product did. Manufacturers reply that glue keeps a phone thin and dry; Deane accepts the trade-off, not the silence about it. 'A factory can glue a phone shut in a second,' Deane says. 'The person who pays for that second is the owner, two years later, when the battery dies.'

D — The sociologist Lena Kovacs spent two years observing repair cafes in three countries, expecting to write about thrift. She found herself writing about company instead. Many visitors, her interviews revealed, could easily have afforded a replacement; they queued in the rain anyway. The broken kettle, she argues, works as an admission ticket - a respectable reason to spend an afternoon among other people. Retired engineers and dressmakers rediscover a use for skills their families stopped asking about years ago; teenagers learn to solder from volunteers sixty years older; visitors stay for tea long after their radios are working. One Rotterdam cafe, she notes, has a waiting list of volunteers, not visitors. When Kovacs asked organisers what their cafes really provided, most ranked company above savings.

E — The movement's arguments have also begun to reach the law, under the banner of the 'right to repair'. The European Union now obliges manufacturers of appliances such as washing machines and refrigerators to keep spare parts available for years after production ends, and to supply them within a fixed time. France has gone further: since 2021, shops there must display a repairability score for products such as phones and laptops, rating each model on a scale of one to ten so that shoppers can compare mendability as easily as price. Retailers must show the figure on the shelf label and online. The policy analyst David Osei calls the scores 'a quiet revolution in the shop window'. Manufacturers resisted them, he notes, citing safety and trade secrets, but early studies suggest some makers are already redesigning products to raise their ratings.

F — None of this will empty the scrapyards by itself. Set against the roughly fifty million tonnes of electronic waste the world now discards every year - a figure still climbing - notes the waste researcher Ruth Calloway, the objects saved in repair cafes are, by weight, a rounding error. But she argues that weighing the movement is the wrong way to judge it. A visitor who has watched their own toaster opened, understood and revived tends to ask new questions in the shop afterwards: can this be opened, are the parts available, how long is it built to last? The cafes' real product, in Calloway's phrase, is not repaired objects but repaired attitudes - and attitudes, unlike toasters, are carried out of the door by everyone who attends.`,
      questions: [
        { n: 14, type: "match", group: "minfo", letters: "ABCDEF",
          rubric: "Reading Passage 2 has six paragraphs, A–F. Which paragraph contains the following information? Write the correct letter, A–F. NB You may use any letter more than once.",
          prompt: "examples of design features that prevent owners from mending products", answer: "C",
          explain: "Paragraph C lists Deane's catalogue of obstacles: glued cases, sealed batteries, non-standard screws and software locks that reject unapproved parts.",
          evidence: "Cases held together by glue instead of screws" },
        { n: 15, type: "match", group: "minfo", prompt: "figures showing how far the repair cafe movement has spread", answer: "A", explain: "Paragraph A gives the numbers: from one Amsterdam cafe in 2009 to more than three thousand locations in over forty countries.", evidence: "more than three thousand locations in over forty countries" },
        { n: 16, type: "match", group: "minfo", prompt: "a claim that repairing something can cost more than replacing it", answer: "B", explain: "Paragraph B contains Bergström's arithmetic: the quote for mending a washing machine is higher than the price of a new machine.", evidence: "higher than the price of a new one", vocab: ["mending", "repairing"] },
        { n: 17, type: "match", group: "minfo", prompt: "details of a rule that lets shoppers compare how easily products can be repaired", answer: "E", explain: "Paragraph E describes the French rule: since 2021 shops must display a repairability score from one to ten, so mendability can be compared like price.", evidence: "shops there must display a repairability score", vocab: ["compare mendability", "compare how easily products can be repaired"] },
        { n: 18, type: "gap", group: "sum2", note: "ONE WORD ONLY",
          notes: {
            title: "Summary — Why mending declined",
            lines: [
              "Repair depends on skilled local {{18}}, whose price has kept rising while factory-made goods have become remarkably cheap.",
              "Design adds further barriers: many cases are now held together by glue rather than {{19}}, and batteries are sealed deep inside.",
              "Increasingly, {{20}} locks prevent a device from accepting parts its maker has not approved,",
              "while repair {{21}} are frequently never published at all.",
              "Law-makers have started to respond: French shops must now display a repairability {{22}} for certain products.",
            ],
          },
          answer: "labour",
          explain: "After 'skilled local', the gap needs the noun the passage itself uses: repair remains skilled local labour, whose hourly price has risen for decades.",
          evidence: "repair remains what it has always been - skilled local labour" },
        { n: 19, type: "gap", group: "sum2", answer: "screws", explain: "Deane's first obstacle is cases held together by glue instead of screws, which means a device must be broken before it can even be opened.", evidence: "held together by glue instead of screws" },
        { n: 20, type: "gap", group: "sum2", answer: "software", explain: "The summary's 'prevent... accepting' paraphrases the passage: software locks stop a device accepting a replacement part the manufacturer has not approved.", evidence: "software locks that stop a device accepting a replacement part", vocab: ["stop", "prevent"] },
        { n: 21, type: "gap", group: "sum2", answer: "manuals", explain: "'Frequently never published' in the summary matches the passage directly: repair manuals are often never published, leaving owners without instructions.", evidence: "Repair manuals are often never published" },
        { n: 22, type: "gap", group: "sum2", answer: "score", explain: "Since 2021, French shops must display a repairability score rating each model from one to ten; 'score' is the concrete noun the gap requires.", evidence: "display a repairability score for products such as phones" },
        { n: 23, type: "match", group: "people", boxTitle: "List of People",
          box: [
            "Sofia Bergström",
            "Marcus Deane",
            "Lena Kovacs",
            "David Osei",
            "Ruth Calloway",
          ],
          rubric: "Look at the following statements (Questions 23–26) and the list of people below. Match each statement with the correct person, A–E. NB There is one more person than you need.",
          prompt: "Products are often built in ways that make mending them impossible.", answer: "B",
          explain: "Deane, who dismantles electronics professionally, catalogues glued cases, sealed batteries and software locks - construction choices that defeat repair.",
          evidence: "opening a device means breaking it", vocab: ["resist repair", "make mending impossible"] },
        { n: 24, type: "match", group: "people", prompt: "Repair events meet a social need as much as a practical one.", answer: "C", explain: "Kovacs expected to write about thrift but found company instead: the broken kettle is an admission ticket, and organisers ranked company above savings.", evidence: "most ranked company above savings", vocab: ["company", "social need"] },
        { n: 25, type: "match", group: "people", prompt: "Legal pressure is already changing how some products are designed.", answer: "D", explain: "Osei notes that although manufacturers resisted the repairability scores, early studies suggest some makers are redesigning products to raise their ratings.", evidence: "already redesigning products to raise their ratings" },
        { n: 26, type: "match", group: "people", prompt: "The movement's true value lies in changing minds rather than saving objects.", answer: "E", explain: "Calloway argues that weighing the movement misses the point: the cafes' real product is repaired attitudes, carried away by everyone who attends.", evidence: "not repaired objects but repaired attitudes", vocab: ["repaired attitudes", "changing minds"] },
      ],
    },
    {
      title: "Passage 3",
      instructions: "You should spend about 20 minutes on Questions 27–40, which are based on Reading Passage 3 below.",
      passageTitle: "The uses of nostalgia",
      passage: `In 1688, a medical student at the University of Basel named Johannes Hofer gave a name to a mysterious illness. Swiss mercenaries serving far from home, in the garrisons of France and Italy, were falling into a decline that no physician could explain: they grew listless and sleepless, refused food, and thought of nothing but the valleys they came from. Hofer assembled a word for their condition from two Greek roots - nostos, the return home, and algos, pain - and classified it as a genuine and dangerous disease. The cause, he suggested, was a single idea wearing a groove in the brain. His successors took the diagnosis entirely seriously. Military doctors attributed deaths in the garrisons to nostalgia; proposed causes ranged from changes in air pressure to, in one memorable theory, the relentless clanging of Alpine cowbells; and since the only reliable cure was to send the sufferer home, some commanders are said to have banned the singing of Alpine herding songs, which were believed to bring the disease on.

Nostalgia remained on the medical books for two centuries, migrating as medicine changed - from the body to the nerves, and from the nerves to the mind. Army surgeons in the American Civil War were still entering it on discharge papers, and Victorian asylums recorded it among their causes of admission. By the twentieth century it had shrunk to a psychiatric symptom, described variously as a form of melancholia or a refusal to grow up, and the word drifted into everyday speech as a mild embarrassment: a weakness for the past, indulged by the sentimental. Its meaning shifted as well. Nostalgia gradually detached itself from geography and attached itself to time. What the nostalgic person longs for today is rarely a place, which could after all be revisited, but a period - a childhood summer, a first friendship, the music of being seventeen - and no ticket can be bought to the past.

The rehabilitation of nostalgia began when psychologists did something surprisingly novel: they asked people about it. When the psychologist Marta Jensen and her colleagues invited hundreds of volunteers to describe nostalgic episodes, the memories that emerged were overwhelmingly social - family meals, weddings, journeys with friends - and although nearly all of them contained a thread of loss, their dominant colour was affection rather than grief. The accounts came readily, most volunteers filling a page within a few minutes, and two independent readers sorted them by theme. Experiments went further. Volunteers prompted to recall a nostalgic event went on to score higher on measures of mood, self-esteem and social connectedness, and reported a stronger sense that life has meaning. In Jensen's reading, nostalgia is not the disease but part of the cure: a psychological resource on which the mind draws precisely when the present runs short, for it is triggered most reliably by loneliness, by sadness and, curiously, by cold.

That last trigger is not a metaphor. In one series of experiments, volunteers seated in a chilled room reported more nostalgic thoughts than volunteers in a comfortable one; and the effect runs in both directions, because people who had just relived a nostalgic memory estimated the same room to be warmer, and kept a hand in icy water for longer, than people who had recalled an ordinary evening. A separate trial found the same with music: a familiar song from a volunteer's teenage years raised fingertip temperature slightly. Nostalgia, in short, produces measurable physical effects. It behaves like an emotional thermostat: when the world turns cold, in either sense, the mind wraps the past around the present like a coat.

None of this makes every form of nostalgia benign, and researchers draw a careful line between two kinds. Personal nostalgia reaches back into a life actually lived. Collective nostalgia, by contrast, is a longing for a past that one's group or nation is imagined to have shared - often a past that no living member ever experienced. Such a past can be assembled from photographs, films and songs, and it improves with every retelling, since nobody alive can contradict it. The second kind is easily manufactured, and history shows how profitably. Political movements have long understood that a promised return to a golden age moves crowds more surely than any programme of facts, and the age in question need never have existed at all. An emotion that restores individuals, it turns out, can also be harnessed to flatter and mislead them in crowds.

Three centuries after Hofer, then, the diagnosis has been almost exactly reversed. What he described as a disease now looks more like part of the mind's immune system: a defence raised against loneliness, emptiness and the cold, and the evidence for this gentler view is difficult to resist. Quite how the defence works is a question the laboratories have only begun to ask. But the reversal comes with a warning attached. A memory of one's own past steadies the person who holds it; a manufactured memory of somebody else's golden age deserves a colder eye. Homesickness, it turns out, can be good for us - provided the home we long for is our own.`,
      questions: [
        { n: 27, type: "mcq", prompt: "What does the writer say about Johannes Hofer?", options: ["A He was the first doctor to cure nostalgia", "B He caught the condition himself while studying abroad", "C He treated a familiar emotion as a physical illness", "D He doubted the reports of the military doctors"], answer: "C", explain: "Hofer named homesickness and classified it as a genuine and dangerous disease - a medical label for an emotion. Option A echoes 'cure' from the passage misleadingly.", evidence: "classified it as a genuine and dangerous disease", vocab: ["disease", "illness"] },
        { n: 28, type: "mcq", prompt: "According to the third paragraph, nostalgic memories are typically", options: ["A centred on other people", "B free of any feeling of loss", "C about places rather than periods", "D difficult for volunteers to describe"], answer: "A", explain: "The memories volunteers described were overwhelmingly social - meals, weddings, journeys with friends - which A paraphrases. B contradicts the 'thread of loss'.", evidence: "the memories that emerged were overwhelmingly social", vocab: ["overwhelmingly social", "centred on other people"] },
        { n: 29, type: "mcq", prompt: "The writer describes the temperature experiments in order to show that", options: ["A cold rooms are bad for the memory", "B volunteers are easily influenced by researchers", "C nostalgia is more common in winter", "D nostalgia affects the body as well as the mind"], answer: "D", explain: "The chilled-room and icy-water studies demonstrate that nostalgia produces measurable physical effects - it changes what the body feels, not just the mood.", evidence: "produces measurable physical effects", vocab: ["physical effects", "affects the body"] },
        { n: 30, type: "mcq", prompt: "In the final paragraph, the writer suggests that nostalgia", options: ["A should once again be treated as an illness", "B is valuable only when the past recalled is genuinely one's own", "C has now been fully explained by psychology", "D is impossible to manufacture deliberately"], answer: "B", explain: "The closing line makes the condition explicit: homesickness can be good for us provided the home we long for is our own - unlike manufactured golden ages.", evidence: "provided the home we long for is our own" },
        { n: 31, type: "ynng", prompt: "Early military doctors believed that nostalgia could kill.", answer: "YES", explain: "YES: the doctors took the diagnosis entirely seriously and attributed actual deaths in the garrisons to nostalgia.", evidence: "attributed deaths in the garrisons to nostalgia" },
        { n: 32, type: "ynng", prompt: "The writer believes that revisiting a place can satisfy modern nostalgia.", answer: "NO", explain: "NO: modern nostalgia longs for a period rather than a place, and the writer states that no ticket can be bought to the past.", evidence: "no ticket can be bought to the past" },
        { n: 33, type: "ynng", prompt: "Jensen's findings have been challenged by other researchers.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage reports Jensen's studies and her reading of them, but never mentions any criticism or challenge from other researchers.", evidence: "the psychologist Marta Jensen and her colleagues" },
        { n: 34, type: "ynng", prompt: "Nostalgia tends to arise when people feel isolated.", answer: "YES", explain: "YES: the writer states that nostalgia is triggered most reliably by loneliness - which 'feeling isolated' paraphrases - as well as by sadness and cold.", evidence: "triggered most reliably by loneliness", vocab: ["loneliness", "isolated"] },
        { n: 35, type: "ynng", prompt: "The writer regards political appeals to a golden age as harmless.", answer: "NO", explain: "NO: the writer says collective nostalgia can be harnessed to flatter and mislead crowds, and that a manufactured golden age deserves a colder eye.", evidence: "deserves a colder eye", vocab: ["mislead", "not harmless"] },
        { n: 36, type: "gap", group: "wl",
          box: ["comfort", "disease", "identity", "memories", "politics", "resource", "soldiers", "threat", "warmth"],
          boxTitle: "List of Words",
          notes: {
            title: "Summary — Nostalgia reconsidered",
            lines: [
              "The word nostalgia was invented in 1688, when Hofer studied homesickness among Swiss {{36}} and classed it as a {{37}}.",
              "Modern psychology has reversed that judgement: experiments suggest nostalgia works as a {{38}} on which the mind draws in difficult moments,",
              "and it can even create a physical sensation of {{39}}.",
              "The writer remains wary, however, of collective nostalgia, especially its use in {{40}}.",
            ],
          },
          answer: "G",
          explain: "The sufferers Hofer studied were Swiss mercenaries - hired soldiers serving abroad in the garrisons of France and Italy - so 'soldiers' fills the gap.",
          evidence: "Swiss mercenaries serving far from home", vocab: ["mercenaries", "soldiers"] },
        { n: 37, type: "gap", group: "wl", answer: "B", explain: "Hofer classified the condition as a genuine and dangerous disease, so 'disease' is the word the summary needs after 'classed it as a'.", evidence: "gave a name to a mysterious illness" },
        { n: 38, type: "gap", group: "wl", answer: "F", explain: "Jensen's reading is that nostalgia is a psychological resource the mind draws on when the present runs short - the summary repeats 'draws' as the clue.", evidence: "a psychological resource on which the mind draws" },
        { n: 39, type: "gap", group: "wl", answer: "I", explain: "People who relived a nostalgic memory judged the room warmer and bore icy water longer, so the physical sensation the summary needs is warmth.", evidence: "estimated the same room to be warmer", vocab: ["warmer", "warmth"] },
        { n: 40, type: "gap", group: "wl", answer: "E", explain: "The collective kind is exploited by political movements promising a return to a golden age, so 'politics' completes the writer's warning.", evidence: "Political movements have long understood" },
      ],
    },
  ],
};
