// Smart LC Upper-Inter Set 12 — Academic Reading (40 questions, 3 passages).
// Original material authored for Smart LC to the blueprint: P1 factual
// history (sentence completion + TFNG), P2 discursive with lettered
// paragraphs (matching paragraph-information + summary + people matching
// with one extra name), P3 argumentative cognition (MCQ-4 + YNNG +
// summary from a lettered wordlist). Key quotas: TFNG/YNNG balanced with
// no runs of three, flat letters, unique concrete-noun answers, correct
// MCQ options paraphrase the text while distractors echo its wording.
export const UPSET12_READING = {
  id: "upset12-reading",
  bookId: "upset12",
  title: "Upper-Inter Set 12 — Reading",
  module: "reading",
  durationMin: 60,
  sections: [
    {
      title: "Passage 1",
      instructions: "You should spend about 20 minutes on Questions 1–13, which are based on Reading Passage 1 below.",
      passageTitle: "The fork's slow victory",
      passage: `Of the three implements on a modern table, the fork is by far the youngest, and it arrived against considerable resistance. Spoons are prehistoric — a shell, a hollowed piece of wood. Knives are older still, since they were tools long before they were tableware. The fork, by contrast, had to argue its way into the European meal over some six hundred years, and for much of that time using one was taken as evidence of vanity, foreign manners or plain stupidity.

Medieval dining assumed a different set of habits altogether. A host supplied the food and the drink but not the equipment, and guests were expected to bring their own knives, worn at the belt beside the purse. Meat arrived already cut into manageable pieces, and diners ate with the knife point, with a spoon for anything liquid, and above all with the fingers — correctly, with the first three fingers of the right hand, since dipping the whole fist into a dish marked a person as badly raised. Thick slices of stale bread served as plates, and bowls of scented water passed round between courses, less decoration than necessity.

Forks did exist, but they belonged in the kitchen. Large two-pronged instruments held a joint steady for carving, and nobody imagined putting one in the mouth. Small eating forks appear first in the wealthy courts of the eastern Mediterranean, and the earliest famous account of one in western Europe is a scandal rather than a recipe. In the eleventh century a Byzantine princess married into the ruling family of Venice and shocked the city by refusing to touch her food, having it cut up by servants and lifting each piece to her lips with a small golden fork. She was condemned by the clergy, one of whom observed that God had provided human beings with natural forks — their fingers — and that to prefer metal ones was an insult to him. When the princess later died of a wasting illness, a chronicler recorded her death as divine punishment.

Italy nevertheless kept the habit, helped by a national dish that defeats the fingers: long pasta rewards a fork as nothing else does. By the sixteenth century the fork was unremarkable in Venice and Florence, and foreign travellers noticed it. The most talkative of them was Thomas Coryat, an English writer who published an account of his walking tour in 1611 and gave several enthusiastic pages to the custom he had seen in Italy. He had adopted it himself, he explained, because his hosts objected to fingers in a shared dish. His friends found this hilarious, and for years afterwards greeted him with a Latin nickname meaning fork-bearer; English opinion held for another century that a man who ate with a fork was affected, effeminate, or both.

What finally forced the change was a decision about knives. In 1637 Cardinal Richelieu, according to a story too neat to be entirely trusted, was so irritated by a guest cleaning his teeth with a blade that he ordered every knife in his household to have its points ground round. Rounded knives spread through French society and then beyond, and they carried an unintended consequence: a blunt knife cannot spear a piece of meat, so something else had to lift food to the mouth. The fork stopped being an affectation and became a necessity. Its design shifted accordingly. Two prongs gripped meat but let peas escape, so makers added a third and then a fourth, and in eighteenth-century Germany the tines were given a slight curve, turning the fork into a shallow scoop and completing the shape we still use today.

Once the fork was accepted, cutlery changed from personal property into household property, and manufacturing followed the change. Sheffield and Birmingham grew rich on it. From the 1740s a cheap imitation silver was produced by fusing a thin sheet of silver onto copper, and after 1840 electroplating — depositing silver from a solution using an electric current — put respectable-looking cutlery within reach of ordinary middle-class families. It also encouraged an extraordinary specialisation: Victorian manufacturers offered fish knives, oyster forks, grape scissors, butter picks and sardine tongs, and a fully equipped dining room might hold several dozen distinct implements, each with rules attached. Etiquette books sold in enormous numbers to households anxious about which one to seize.

One nuisance remained. Ordinary steel rusted, tainted acidic food with a metallic taste, and had to be scoured with brick dust after every meal, which is why good knives kept handles of bone or ivory that hot water destroyed. The nuisance ended in 1913, when Harry Brearley, working in a Sheffield laboratory on the problem of erosion inside gun barrels, noticed that a rejected sample containing a high proportion of chromium had refused to rust. Stainless steel abolished the daily polishing that had occupied kitchen staff for centuries, and made the cheap, permanent, dishwasher-proof cutlery drawer possible.

Even now the fork is neither universal nor settled. Most of humanity eats with chopsticks or with the hand, both older technologies than a metal spike, and among fork users the Americans cut with the knife in the right hand and then move the fork across to it, a switching style that Europeans find comic and that Americans defend as elegant. The youngest implement on the table is still deciding what its manners are.`,
      questions: [
        { n: 1, type: "gap", prompt: "Guests at a medieval meal were expected to bring their own ______.", note: "ONE WORD ONLY", answer: ["knives", "knife"], explain: "The host provided food and drink but no equipment, so each guest carried a knife at the belt; the plural noun fits the gap after 'their own'.", evidence: "guests were expected to bring their own knives", vocab: ["supplied the food", "provided"] },
        { n: 2, type: "gap", prompt: "The Venetian princess's golden fork was condemned by the ______.", note: "ONE WORD ONLY", answer: "clergy", explain: "Churchmen objected that God had given people natural forks in their fingers; the passage names the group as the clergy.", evidence: "She was condemned by the clergy" },
        { n: 3, type: "gap", prompt: "Coryat wrote enthusiastically about a custom he had seen in ______.", note: "ONE WORD ONLY", answer: "Italy", explain: "Coryat's 1611 account of his walking tour devoted several pages to fork use, a habit he had observed in Italy and then copied himself.", evidence: "the custom he had seen in Italy" },
        { n: 4, type: "gap", prompt: "In 1637 Richelieu had the ______ of his household's knives ground round.", note: "ONE WORD ONLY", answer: "points", explain: "Annoyed by a guest picking his teeth with a blade, Richelieu ordered every knife to have its points ground round, which made spearing food impossible.", evidence: "have its points ground round", vocab: ["blade", "knife"] },
        { n: 5, type: "gap", prompt: "A fork with only two ______ could not hold small foods such as peas.", note: "ONE WORD ONLY", answer: "prongs", explain: "'Could not hold' paraphrases 'let peas escape': two prongs gripped meat but lost small items, so a third and fourth were added.", evidence: "Two prongs gripped meat but let peas escape", vocab: ["let peas escape", "could not hold"] },
        { n: 6, type: "gap", prompt: "From 1840, ______ brought silver-looking cutlery within reach of middle-class buyers.", note: "ONE WORD ONLY", answer: "electroplating", explain: "The gap needs the process named in the passage: depositing silver from a solution with an electric current, which is called electroplating.", evidence: "after 1840 electroplating", vocab: ["within reach of", "brought within reach"] },
        { n: 7, type: "gap", prompt: "Stainless steel put an end to the daily ______ of knives and forks.", note: "ONE WORD ONLY", answer: "polishing", explain: "'Put an end to' paraphrases 'abolished': stainless steel removed the daily polishing that had occupied kitchen staff for centuries.", evidence: "abolished the daily polishing", vocab: ["abolished", "put an end to"] },
        { n: 8, type: "tfng", prompt: "Medieval hosts provided their guests with the tools needed to eat.", answer: "FALSE", explain: "FALSE: the passage states the opposite - a host supplied food and drink but not the equipment, so guests brought knives of their own.", evidence: "A host supplied the food and the drink but not the equipment" },
        { n: 9, type: "tfng", prompt: "Eating with the whole hand was regarded as a sign of poor upbringing.", answer: "TRUE", explain: "TRUE: correct practice used only the first three fingers, and dipping the whole fist into a dish marked a person as badly raised.", evidence: "marked a person as badly raised", vocab: ["badly raised", "poor upbringing"] },
        { n: 10, type: "tfng", prompt: "Coryat said he had started using a fork because of his hosts' dislike of fingers in shared food.", answer: "TRUE", explain: "TRUE: he explained that he adopted the custom himself because his Italian hosts objected to fingers being put into a shared dish.", evidence: "because his hosts objected to fingers in a shared dish", vocab: ["objected to", "dislike of"] },
        { n: 11, type: "tfng", prompt: "Coryat's countrymen quickly adopted the habit he described.", answer: "FALSE", explain: "FALSE: his friends laughed at him and English opinion continued for another hundred years to treat fork users as affected or effeminate.", evidence: "English opinion held for another century" },
        { n: 12, type: "tfng", prompt: "Sheffield produced more cutlery than Birmingham.", answer: "NOT GIVEN", explain: "NOT GIVEN: both cities are named as growing rich on cutlery manufacture, but the passage never compares how much each of them produced.", evidence: "Sheffield and Birmingham grew rich on it" },
        { n: 13, type: "tfng", prompt: "Brearley made his discovery while investigating an unrelated problem.", answer: "TRUE", explain: "TRUE: he was studying erosion inside gun barrels, not searching for a cutlery metal, when he noticed the rejected chromium sample had not rusted.", evidence: "on the problem of erosion inside gun barrels", vocab: ["a rejected sample", "discovery"] },
      ],
    },
    {
      title: "Passage 2",
      instructions: "You should spend about 20 minutes on Questions 14–26, which are based on Reading Passage 2 below.",
      passageTitle: "The return of the school garden",
      passage: `A — On a Tuesday morning at a primary school on the edge of a northern city, a class of eight-year-olds is arguing about slugs. Their garden is not much: four raised beds, a water butt, a plastic greenhouse and a compost bin. Yet it occupies an hour of the timetable each week, and the argument — whether the slugs should be moved or left alone — is conducted with the seriousness of a council meeting. Growing space of this kind has spread remarkably over the past twenty years, and surveys in several countries now find some form of garden at a majority of primary schools. The movement presents itself as an innovation. It is in fact a revival.

B — Gardens were attached to schools across Europe from the middle of the nineteenth century, when educationists argued that country children were being taught to despise the work their parents did. In Sweden, Austria and the German states, teacher training colleges taught gardening, and several administrations made a garden a legal requirement for new rural schools. The idea crossed the Atlantic in the 1890s and was adopted by city reformers, who saw in a vegetable bed a cure for idleness. By 1918 school gardens had become a war measure: on both sides of the Atlantic, children grew vegetables to add to a limited national supply, and the same thing happened again in the 1940s. The decline that followed was rapid. After 1950, playing fields and growing plots were sold for classrooms as pupil numbers rose, imported food became cheap and abundant, and a timetable increasingly organised around examined subjects had no obvious room for digging. Marta Lindgren, a historian of education who has traced the movement through school inspection reports, notes that gardens are almost never recorded as having been abolished. They simply stop being mentioned.

C — The modern revival is usually justified on grounds of diet, and this is where the evidence is weakest. Trials do report that children who grow vegetables become markedly more willing to taste unfamiliar ones, which is not a trivial finding: a refusal to try is where most childhood food battles begin. But the effect on how much children actually eat at home is far smaller, and in several studies it disappears within a year. Owen Baptiste, who has reviewed dozens of evaluations for a public health body, is blunt about the literature. Many studies, he points out, have no comparison group, rely on children reporting their own eating, and are published by the organisations that ran the programme being assessed. "The gardens may well work," he says. "But a great deal of what is presented as evidence would not survive a first-year statistics class."

D — Diet may in any case be the wrong thing to measure. Ismail Karimi, an educational researcher who compared attainment across ninety schools, found that the largest measurable effects were academic rather than dietary: pupils who gardened regularly scored higher in science, and the gap was widest on questions about life cycles, soil and food chains — precisely the topics a bed of vegetables demonstrates every week. Maths teachers in his sample used the beds for area, volume and averages. "The garden is a laboratory that costs almost nothing," Karimi argues, "and it is in the science results, not the lunch boxes, that you can watch it working." Teachers also report calmer behaviour and better concentration after outdoor sessions, though such claims are considerably harder to test.

E — Whatever the benefits, school gardens are fragile institutions. They need attention in August, when the school is shut and the crops ripen; they need storage, water and money for replacing tools; and above all they need somebody able to teach with them. Hana Petrov, who has advised local authorities on outdoor learning for fifteen years, found that the strongest predictor of a garden's survival was not the size of its budget but whether it rested on a single individual. "Almost every garden I visited had been created by one enthusiastic teacher," she says, "and almost every abandoned garden had lost that teacher." Her recommendation is deliberately unromantic: gardening should be written into the school timetable and the budget, attached to a named post rather than to a volunteer, with holiday care agreed in advance with parents or a neighbouring allotment association.

F — A final argument sets the measurements aside altogether. Ruth Ackerman, who works with schools in dense inner-city districts, points out that a number of her pupils have no access to private outdoor space of any kind, and that for them the beds are not an enrichment activity but their only encounter with growing things. She values the garden for something the rest of the school day cannot supply: work whose results arrive slowly, cannot be hurried and frequently fail. "Children spend their lives being marked on tasks that finish within the hour," she says. "A carrot takes three months and may still be eaten by something. Learning to wait, and to lose a crop without concluding that you are bad at it, is not a soft extra." Judged purely as a way of increasing vegetable consumption, the school garden looks like an expensive intervention with modest returns. Judged as a place where children meet an unhurried and uncertain world, it may be the cheapest classroom a school owns.`,
      questions: [
        { n: 14, type: "match", group: "minfo", letters: "ABCDEF",
          rubric: "Reading Passage 2 has six paragraphs, A–F. Which paragraph contains the following information? Write the correct letter, A–F. NB You may use any letter more than once.",
          prompt: "the reasons why school gardens were given up in the past", answer: "B",
          explain: "Paragraph B lists the causes of the decline after 1950: plots sold for classrooms, cheap imported food, and a timetable filled with examined subjects.",
          evidence: "growing plots were sold for classrooms as pupil numbers rose", vocab: ["the decline that followed", "given up"] },
        { n: 15, type: "match", group: "minfo", prompt: "an argument that gardens should not be judged by their effect on eating", answer: "F", explain: "Paragraph F sets the dietary measurements aside: Ackerman values the garden as a place where children meet slow, uncertain work.", evidence: "A final argument sets the measurements aside altogether", vocab: ["sets the measurements aside", "should not be judged by"] },
        { n: 16, type: "match", group: "minfo", prompt: "criticism of the way research into school gardens has been carried out", answer: "C", explain: "Paragraph C reports Baptiste's objections to the studies themselves: no comparison group, self-reported eating, and evaluations published by the programmes' own organisers.", evidence: "have no comparison group, rely on children reporting their own eating" },
        { n: 17, type: "match", group: "minfo", prompt: "advice on how a garden can outlast the staff who started it", answer: "E", explain: "Paragraph E gives Petrov's remedy for fragility: put gardening in the timetable and budget and attach it to a named post, not to one volunteer.", evidence: "attached to a named post rather than to a volunteer", vocab: ["a named post", "staff"] },
        { n: 18, type: "gap", group: "sum2", note: "ONE WORD ONLY",
          notes: {
            title: "Summary — The rise, fall and survival of the school garden",
            lines: [
              "School gardens spread across Europe from the mid-nineteenth century, and in some states a garden became a legal {{18}} for any new rural school.",
              "During the two world wars, children grew {{19}} to add to a limited national supply.",
              "The gardens then faded away: growing plots were sold for {{20}}, imported food became cheap, and examined subjects filled the school day.",
              "Where gardens now survive, Petrov argues, it is because the work has been written into the school {{21}} and the {{22}}, instead of depending on one enthusiastic member of staff.",
            ],
          },
          answer: "requirement",
          explain: "After 'a legal', the gap needs a noun: several administrations made a garden a legal requirement for new rural schools.",
          evidence: "made a garden a legal requirement for new rural schools" },
        { n: 19, type: "gap", group: "sum2", answer: "vegetables", explain: "In both wars the gardens were a war measure, with children growing vegetables to add to a limited national supply.", evidence: "children grew vegetables to add to a limited national supply" },
        { n: 20, type: "gap", group: "sum2", answer: "classrooms", explain: "'Sold for' points to the same phrase in paragraph B: as pupil numbers rose, playing fields and growing plots were sold for classrooms.", evidence: "sold for classrooms as pupil numbers rose" },
        { n: 21, type: "gap", group: "sum2", answer: "timetable", explain: "Petrov's recommendation names two places the work must appear; the first is the school timetable, so that gardening is taught in curriculum time.", evidence: "written into the school timetable and the budget" },
        { n: 22, type: "gap", group: "sum2", answer: "budget", explain: "The second half of Petrov's recommendation is money: the garden must sit in the school budget rather than relying on a volunteer's goodwill.", evidence: "the school timetable and the budget", vocab: ["money for replacing tools", "budget"] },
        { n: 23, type: "match", group: "people", boxTitle: "List of People",
          box: [
            "Marta Lindgren",
            "Owen Baptiste",
            "Ismail Karimi",
            "Hana Petrov",
            "Ruth Ackerman",
          ],
          rubric: "Look at the following statements (Questions 23–26) and the list of people below. Match each statement with the correct person, A–E. NB There is one more person than you need.",
          prompt: "Much of the research used to support school gardening is poorly designed.", answer: "B",
          explain: "Baptiste reviewed dozens of evaluations and objects to their design - missing comparison groups, self-reported data, and publication by the programme's own organisers.",
          evidence: "would not survive a first-year statistics class", vocab: ["no comparison group", "poorly designed"] },
        { n: 24, type: "match", group: "people", prompt: "The clearest gains from gardening show up in school subjects rather than in diet.", answer: "C", explain: "Karimi compared ninety schools and found the largest measurable effects were academic: higher science scores, especially on life cycles, soil and food chains.", evidence: "the largest measurable effects were academic rather than dietary", vocab: ["not the lunch boxes", "rather than in diet"] },
        { n: 25, type: "match", group: "people", prompt: "A garden lasts only if the school treats it as part of its ordinary business.", answer: "D", explain: "Petrov found survival depends on not resting on one person: gardening must be written into the timetable and budget and attached to a named post.", evidence: "the strongest predictor of a garden's survival" },
        { n: 26, type: "match", group: "people", prompt: "Gardening teaches children to accept waiting and failure.", answer: "E", explain: "Ackerman values slow, unhurried work: a carrot takes three months, and losing a crop teaches children to wait without deciding they are bad at it.", evidence: "Learning to wait, and to lose a crop", vocab: ["results arrive slowly", "waiting"] },
      ],
    },
    {
      title: "Passage 3",
      instructions: "You should spend about 20 minutes on Questions 27–40, which are based on Reading Passage 3 below.",
      passageTitle: "The pen, the keyboard and the memory",
      passage: `Every September the same argument returns to lecture halls, and it is usually settled by assertion rather than evidence. Should students take notes by hand, or on a laptop? For a decade the question has had a famous answer. In 2014 two American psychologists reported an experiment in which students watched recorded talks and took notes either in longhand or on a keyboard. On simple factual questions the two groups performed about equally. On conceptual questions — those requiring the listener to draw a conclusion rather than retrieve a detail — the laptop users did distinctly worse. The explanation offered had nothing to do with machinery. Typists could keep up with the speaker, and so they transcribed, recording sentences close to word for word; writers by hand could not keep up, and were therefore forced to select, compress and rephrase as they went. Choosing what to leave out is itself a form of understanding.

Psychologists call this a desirable difficulty: extra mental effort during learning that feels unhelpful at the time but improves recall afterwards. The 2014 study contained a detail that made it especially persuasive. One group of typists was explicitly warned not to take verbatim notes and told why. They transcribed anyway, and did no better than the others. Habit, it seemed, was stronger than instruction, and the keyboard's very fluency was the problem.

The finding travelled fast. It produced headlines, university guidance and, in some departments, laptop bans. Then came the slower business of replication. A study published in 2019 repeated the design with larger samples and found no reliable advantage for handwriting; other laboratories reported effects that appeared and vanished depending on the delay before the test, the difficulty of the material and whether students were allowed to review their notes before being examined. Pooled analyses now put the average benefit of longhand at somewhere between small and invisible. The original claim has not been demolished, but it has been narrowed: handwriting appears to help chiefly when notes are never revisited, so that the act of writing is the only processing the material ever receives.

Neuroscience, meanwhile, has approached the question from a different direction. Studies recording electrical activity from the scalp find that writing words by hand produces more widespread coordination between regions involved in movement, vision and memory than typing the same words does. Work with young children points the same way: those who practise forming letters by hand afterwards recognise them more reliably than those who learn the same letters on a keyboard. The suggested reason is that producing a shape through an effortful, slightly different movement each time builds a richer record than pressing an identical key. Whether such measurements translate into remembering a lecture six weeks later is a considerable leap, and the researchers themselves are careful about making it.

The case for the keyboard, meanwhile, is rarely put properly. Typists capture far more material, and for a fast lecture crowded with names, dates and figures a nearly complete record may be worth more than an elegant summary — particularly to a student who intends to reorganise it later. Typed notes can be searched, shared and edited, and for students with motor difficulties or dyslexia a keyboard may be the only route to notes they can use at all. Treating handwriting as morally superior quietly ignores those students. The genuine hazard of the laptop lies elsewhere: studies of classroom multitasking find consistently that students who divide their attention between the lecture and a browser perform worse, and, more awkwardly, that students seated behind an open screen do worse too.

Read together, the literature suggests something less quotable than the headlines. Neither implement possesses a virtue of its own. What matters is whether the note-taker re-expresses the material — turns the speaker's sentences into their own. Handwriting produces that re-expression accidentally, through its slowness; a typist can produce it deliberately, by summarising, or can avoid it entirely by transcribing. Experiments that train typists to summarise rather than copy remove most of the difference between the two groups. The medium, in other words, is a nudge rather than a cause, and a nudge can be overridden in either direction.

That conclusion is unhelpful for policy, because bans are simple and teaching is not. A department can prohibit laptops in an afternoon; instructing several hundred students how to take notes requires curriculum time that nobody has allocated. Yet the practical advice that follows from the research is neither expensive nor mysterious: write less than you hear, ask questions in the margin, revisit the notes within a day while the lecture can still be reconstructed, and condense them into a shorter form afterwards. Every one of these steps forces the re-expression that the original experiment accidentally measured.

The pen may still deserve part of its reputation, though perhaps not for the reason usually given. Its advantage is less what it does to the brain than what it prevents: it cannot keep up, so it compels a choice, and it cannot open a second window.`,
      questions: [
        { n: 27, type: "mcq", prompt: "What was the main finding of the 2014 experiment?", options: ["A Students writing by hand remembered more facts than laptop users", "B Laptop users did worse on questions that required understanding", "C Students writing by hand produced more words than laptop users", "D Typists who were warned about transcribing improved their scores"], answer: "B", explain: "Both groups matched on factual recall, so A is wrong; the gap appeared on conceptual questions. Options C and D echo the passage's wording but reverse its facts.", evidence: "the laptop users did distinctly worse", vocab: ["conceptual questions", "questions that required understanding"] },
        { n: 28, type: "mcq", prompt: "What does the term 'desirable difficulty' refer to?", options: ["A a lecture deliberately delivered at high speed", "B a note-taking method that students dislike at first", "C the frustration of failing to keep up with a speaker", "D extra effort while learning that aids later recall"], answer: "D", explain: "The passage defines it directly as extra mental effort during learning which feels unhelpful at the time but improves recall afterwards.", evidence: "extra mental effort during learning that feels unhelpful at the time", vocab: ["improves recall afterwards", "aids later recall"] },
        { n: 29, type: "mcq", prompt: "What do the later replication studies suggest?", options: ["A The advantage of writing by hand is smaller and less dependable than first reported", "B The 2014 experiment was dishonestly conducted", "C Typing is better than handwriting for difficult material", "D Students have largely stopped taking notes in lectures"], answer: "A", explain: "The 2019 study found no reliable advantage and pooled analyses put the benefit between small and invisible - narrowed, the passage says, but not demolished.", evidence: "between small and invisible", vocab: ["has been narrowed", "less dependable"] },
        { n: 30, type: "mcq", prompt: "Why does the writer mention students with dyslexia?", options: ["A to show that research on handwriting excludes young children", "B to argue that laptops should be banned only in some subjects", "C to identify people disadvantaged by treating handwriting as better", "D to explain why typed notes are easier to search and share"], answer: "C", explain: "For these students a keyboard may be the only route to usable notes, so the passage says a moral preference for handwriting quietly ignores them.", evidence: "Treating handwriting as morally superior quietly ignores those students", vocab: ["quietly ignores", "disadvantaged by"] },
        { n: 31, type: "ynng", prompt: "The writer accepts that writing by hand can sometimes help memory.", answer: "YES", explain: "YES: the writer says the original claim has been narrowed rather than destroyed, and that handwriting helps chiefly when notes are never revisited.", evidence: "handwriting appears to help chiefly when notes are never revisited" },
        { n: 32, type: "ynng", prompt: "The writer believes the 2014 result has been firmly confirmed by later research.", answer: "NO", explain: "NO: the writer reports that a larger 2019 study found no reliable advantage and that pooled analyses shrink the benefit to something between small and invisible.", evidence: "found no reliable advantage for handwriting", vocab: ["no reliable advantage", "firmly confirmed"] },
        { n: 33, type: "ynng", prompt: "The writer thinks universities should record all their lectures for students.", answer: "NOT GIVEN", explain: "NOT GIVEN: the 2014 participants watched recorded talks, but the writer never discusses whether universities ought to record their own lectures.", evidence: "students watched recorded talks" },
        { n: 34, type: "ynng", prompt: "The writer considers divided attention a more serious problem than typing itself.", answer: "YES", explain: "YES: the writer calls the browser the genuine hazard of the laptop, harming both the multitasking student and those sitting behind the open screen.", evidence: "The genuine hazard of the laptop lies elsewhere", vocab: ["divide their attention", "divided attention"] },
        { n: 35, type: "ynng", prompt: "The writer believes the choice of writing tool decides how much students learn.", answer: "NO", explain: "NO: the writer concludes that neither implement has a virtue of its own and that the medium is a nudge rather than a cause of better learning.", evidence: "Neither implement possesses a virtue of its own", vocab: ["a nudge rather than a cause", "decides"] },
        { n: 36, type: "gap", group: "wl",
          box: ["conditional", "connections", "distraction", "meaning", "memory", "selection", "speed", "tool", "training", "verbatim"],
          boxTitle: "List of Words",
          rubric: "Complete the summary using the list of words, A–J, below.",
          notes: {
            title: "Summary — What the note-taking research actually shows",
            lines: [
              "In the 2014 experiment, students using keyboards could keep pace with the speaker and so recorded the talk almost {{36}},",
              "while those writing by hand were too slow and had to make a constant {{37}} of what mattered.",
              "Attempts to repeat the study have often failed, so the advantage is now described as {{38}} rather than automatic.",
              "Recordings of brain activity suggest that forming letters by hand creates wider {{39}} between areas of the brain,",
              "but the writer concludes that the decisive factor is not the {{40}} itself: what counts is whether notes are put into the student's own words.",
            ],
          },
          answer: "J",
          explain: "The passage says typists recorded sentences close to word for word; the box word for that is verbatim, which also appears in the warning given to one group.",
          evidence: "recording sentences close to word for word", vocab: ["word for word", "verbatim"] },
        { n: 37, type: "gap", group: "wl", answer: "F", explain: "Writers by hand could not keep up and were forced to select what to include, so the noun needed is selection.", evidence: "forced to select, compress and rephrase", vocab: ["forced to select", "selection"] },
        { n: 38, type: "gap", group: "wl", answer: "A", explain: "Effects appeared and vanished depending on delay, difficulty and revision, so the advantage holds only under certain conditions - it is conditional.", evidence: "effects that appeared and vanished depending on the delay" },
        { n: 39, type: "gap", group: "wl", answer: "B", explain: "The scalp recordings show more widespread coordination between movement, vision and memory regions, which the summary calls wider connections.", evidence: "more widespread coordination between regions", vocab: ["widespread coordination", "wider connections"] },
        { n: 40, type: "gap", group: "wl", answer: "H", explain: "The writer's conclusion is that neither implement has a virtue of its own and the medium is only a nudge, so the tool is not decisive.", evidence: "The medium, in other words, is a nudge rather than a cause", vocab: ["the medium", "the tool"] },
      ],
    },
  ],
};
