// Smart LC Pre-IELTS Set 5 — Academic Reading (40 questions, 3 passages).
// Original material authored for Smart LC to the blueprint: P1 factual
// history (completion + TFNG), P2 discursive with lettered paragraphs
// (matching paragraph-information + summary + people matching with one
// extra name), P3 argumentative (MCQ-4 + YNNG + sentence endings).
// Key quotas: TFNG/YNNG balanced with no runs of three, flat letters,
// unique concrete-noun answers, correct MCQ options paraphrase the text
// while distractors echo its wording.
export const UPSET5_READING = {
  id: "upset5-reading",
  bookId: "upset5",
  title: "Pre-IELTS Set 5 — Reading",
  module: "reading",
  durationMin: 60,
  sections: [
    {
      title: "Passage 1",
      instructions: "You should spend about 20 minutes on Questions 1–13, which are based on Reading Passage 1 below.",
      passageTitle: "The rise, fall and return of the street market",
      passage: `The street market is older than the street. Long before towns had shops, councils or paved roads, people gathered at agreed places on agreed days to exchange what they had grown, caught or made, and many of the world's cities began as nothing more than a convenient meeting point that refused to disperse. In ancient Greece, the agora was at once a marketplace and the centre of public life, where news and politics changed hands along with olives and cloth; Rome went further and put up purpose-built market halls, with permanent stalls and cool storerooms below. Wherever a market took root, other business followed. Moneylenders set up their tables beside the fish sellers, entertainers worked the crowds, and officials arrived to keep order — and to take their share.

In medieval England, that share was formalised in a remarkable way. Nobody could simply start a market: the right to hold one was a privilege of the Crown, and a lord who wanted a weekly market in his town had to obtain a royal charter, a document for which he paid handsomely. More than two thousand such charters were issued in the thirteenth and early fourteenth centuries alone, and they were worth the price, because the lord collected tolls from every trader who set up a stall. The system even regulated geography. A new market could not lawfully be held too close to an existing one; the customary limit was about ten kilometres, roughly the distance a villager could walk to market and home again in a single day. Many towns owe their very existence to this arrangement: the market frequently came first, and the town grew up around it.

Inside the market, trading was anything but a free-for-all. The day began not when the first trader was ready but when a bell was rung, and the timing protected ordinary households: until the bell sounded, dealers were forbidden to buy, so that local families had first choice of fresh produce before wholesalers could sweep in and empty the stalls. Honesty was policed with equal energy. Traders' scales were tested against official weights kept in the town hall, false measures were broken, and a cheat could expect public shame as well as a fine — a baker who sold underweight loaves might be dragged through the streets with the offending bread tied around his neck. Order extended to the layout itself, for stalls were grouped by trade: butchers in one row, fishmongers in another, corn merchants in a third. The trades have long gone, but in many English towns the street names — Fish Street, Butcher Row, Cornmarket — still mark exactly where each of them stood.

The nineteenth century transformed this ancient institution. Victorian reformers were increasingly troubled by food sold in the open street, exposed to rain, soot and flies, and by the congestion that market days brought to fast-growing towns. Their answer was the covered market hall, and hundreds were built between the 1830s and the 1890s: grand structures of iron and glass, with numbered stalls, proper drainage, gas light and inspectors on the door. At the same time the railways changed what a market could sell. Fish landed on the coast at dawn could be inland and on a stall by the afternoon, and fruit no longer had to come from the surrounding countryside. The market, once fed by a ten-kilometre circle of farmland, could now draw on the whole country.

For the street market, the second half of the twentieth century was a long retreat. The household refrigerator removed the need to shop daily; the car carried shoppers to spacious supermarkets on the edge of town; and hundreds of markets closed between the 1950s and the 1990s. Traders' children chose other work, and several fine Victorian halls were demolished to make way for car parks and shopping centres. To many planners of the period, the market was simply an obsolete machine for distributing food, and its disappearance was progress.

The obituary proved premature. From the 1990s onwards, farmers' markets — at which producers may sell only what they themselves have grown, reared or baked — spread rapidly through Britain, while councils began to restore the historic halls and street markets that had survived. The revival is not mere nostalgia; it has an economic argument behind it. A study of several British towns found that people who came to shop at a market went on to spend money in the surrounding shops, so that a good market raises the takings of an entire street. A market has social uses, too: it is one of the few public places where people can linger, talk and compare without being obliged to buy anything at all. The bell no longer rings, but after a thousand years the street market has, once again, a future.`,
      questions: [
        { n: 1, type: "gap", prompt: "A lord needed to obtain a royal ______ before he could legally hold a market.", note: "ONE WORD ONLY", answer: "charter", explain: "The right to hold a market belonged to the Crown, so a lord had to buy an official document called a royal charter.", evidence: "had to obtain a royal charter" },
        { n: 2, type: "gap", prompt: "Trading could not begin each day until a ______ had been rung.", note: "ONE WORD ONLY", answer: "bell", explain: "The market day had an official start: no trading was allowed until the bell rang, whatever time the traders themselves were ready.", evidence: "began not when the first trader was ready but when a bell was rung" },
        { n: 3, type: "gap", prompt: "Traders' scales were checked against official ______ held by the town.", note: "ONE WORD ONLY", answer: "weights", explain: "'Checked' in the question paraphrases 'tested' in the passage: every trader's scales were compared with the official weights stored in the town hall.", evidence: "tested against official weights kept in the town hall", vocab: ["tested", "checked"] },
        { n: 4, type: "gap", prompt: "In many towns, old street ______ still show where the different trades were located.", note: "ONE WORD ONLY", answer: "names", explain: "Stalls were grouped by trade, and although the trades disappeared, street names such as Fish Street still record exactly where each group stood.", evidence: "street names — Fish Street, Butcher Row, Cornmarket — still mark exactly where each" },
        { n: 5, type: "gap", prompt: "Victorian market halls were built of glass and ______.", note: "ONE WORD ONLY", answer: "iron", explain: "The covered halls of the 1830s to 1890s were grand structures of iron and glass; the question simply reverses the order of the two materials.", evidence: "grand structures of iron and glass" },
        { n: 6, type: "gap", prompt: "The ______ made it possible for markets to sell food from far away.", note: "ONE WORD ONLY", answer: "railways", explain: "Once the railways arrived, coastal fish and distant fruit could reach a stall within hours, so food no longer came only from nearby farmland.", evidence: "the railways changed what a market could sell" },
        { n: 7, type: "tfng", prompt: "Some medieval towns developed around markets rather than the other way round.", answer: "TRUE", explain: "TRUE: the passage says many towns owe their existence to markets — the market frequently came first and the settlement then grew up around it.", evidence: "the market frequently came first, and the town grew up around it", vocab: ["grew up around", "developed around"] },
        { n: 8, type: "tfng", prompt: "The morning bell gave dealers the chance to buy before ordinary families.", answer: "FALSE", explain: "FALSE: the rule worked the opposite way — dealers were forbidden to buy until the bell sounded, so local households had first choice.", evidence: "until the bell sounded, dealers were forbidden to buy", vocab: ["forbidden", "not allowed"] },
        { n: 9, type: "tfng", prompt: "Dishonest traders received the same punishment in every market town.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage describes one possible punishment for a cheating baker, but never says whether punishments were identical from town to town.", evidence: "a baker who sold underweight loaves might be dragged through the streets" },
        { n: 10, type: "tfng", prompt: "Worries about hygiene contributed to the building of covered market halls.", answer: "TRUE", explain: "TRUE: reformers were troubled by food exposed to rain, soot and flies in open streets, and the covered hall was their answer to this.", evidence: "troubled by food sold in the open street, exposed to rain, soot and flies", vocab: ["troubled by", "worries about"] },
        { n: 11, type: "tfng", prompt: "The number of street markets increased during the late twentieth century.", answer: "FALSE", explain: "FALSE: the second half of the century was a long retreat, with hundreds of markets closing between the 1950s and the 1990s.", evidence: "hundreds of markets closed between the 1950s and the 1990s" },
        { n: 12, type: "tfng", prompt: "Farmers' markets sell their goods at lower prices than supermarkets.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage explains what farmers' markets may sell, but it makes no comparison at all between their prices and supermarket prices.", evidence: "producers may sell only what they themselves have grown, reared or baked" },
        { n: 13, type: "tfng", prompt: "A market can increase the income of nearby businesses.", answer: "TRUE", explain: "TRUE: a study found market shoppers went on to spend in the surrounding shops, raising the takings — the income — of the whole street.", evidence: "went on to spend money in the surrounding shops", vocab: ["takings", "income"] },
      ],
    },
    {
      title: "Passage 2",
      instructions: "You should spend about 20 minutes on Questions 14–26, which are based on Reading Passage 2 below.",
      passageTitle: "Rivers out of the dark",
      passage: `A — Beneath the pavements of almost every old city, water is still flowing. London buried the Fleet, once a working river with wharves and mills, inside a brick sewer two centuries ago; Moscow did the same to the Neglinnaya, and New York's Minetta Brook now trickles beneath the apartment blocks of Greenwich Village. The historian Grace Ito, who has spent a decade assembling old maps of these vanished waterways, calls every large city 'a graveyard of streams'. Their traces survive, she points out, for anyone who cares to look: in street names like Brook Lane and Spring Gardens, in the unexpected curve of a road that still follows a valley nobody can see, and in the damp basements of houses whose owners have no idea a river runs beneath them.

B — The burials were not acts of vandalism; at the time, they looked like rescue. By the nineteenth century the small rivers of industrial cities had become open drains, thick with household waste and the outflow of slaughterhouses, tanneries and dye works, and they were blamed — often correctly — for repeated outbreaks of disease. Enclosing a foul stream in a tunnel and building a street on top solved two problems at once: the smell and the sickness went underground, and the city gained valuable land for nothing. Victorian engineers were proud of the work, and their brick culverts, many still in service today, were built to last for centuries.

C — Reversing that logic has a name: daylighting, the deliberate reopening of a buried river to the sky. Its most famous example is the Cheonggyecheon in Seoul. In 2003 the city began demolishing an elevated motorway that carried around 170,000 vehicles a day, and beneath it engineers uncovered the stream the road had entombed. The restored corridor, nearly six kilometres long, opened in 2005 and now draws tens of thousands of visitors a day. The results went well beyond scenery: in summer, air temperatures beside the water are several degrees lower than in the parallel streets, and the channel funnels a cooling breeze through the city centre. Smaller schemes have followed on other continents, from Yonkers in New York State to Sheffield in northern England, where stretches of long-covered rivers now run in the open again.

D — For its advocates, the strongest case for daylighting is not beauty but safety. The hydrologist Ruth Calloway points out that a buried river is simply a pipe, with a capacity fixed on the day it was built. 'A culvert designed for the storms of 1870 is now expected to swallow the storms of a changed climate,' she says. 'When it fails, the water does not wait politely — it comes up through the streets.' An open channel behaves differently: returned to the surface and edged with parkland, a river can slow storm water down and cut flooding downstream, because the water spreads across its floodplain instead of bursting from an overloaded pipe. There are biological rewards as well. The ecologist Ingrid Solberg, who surveys restored streams, expected recolonisation to take decades; instead, she reports, insects arrive within weeks, fish within a year or two, and herons soon after — wildlife returns faster than anyone predicts.

E — The objections are serious, and the first is money: uncovering a river through a dense district can cost tens of millions per kilometre, and the space it needs is space a crowded city rarely has. The economist Daniel Mensah raises a quieter problem. Studying neighbourhoods before and after restoration, he found that property prices near a daylighted river rise well above the city average, and rents rise with them. 'The people who campaigned for the river,' he observes, 'are often the ones who can no longer afford to live beside it.' Mensah does not oppose the projects; he argues that plans must protect existing residents, through affordable housing and controlled rents, from the very success they helped to create.

F — Nor can every river come back. The engineer Tomasz Nowak, who has audited buried watercourses for several European cities, estimates that a large share of them lie many metres down, or run directly beneath buildings and railway lines. 'Those can never be brought to the surface,' he says flatly. 'The honest first step is a map — know what you have, and choose the stretches where daylighting is actually possible.' In practice that usually means starting small: a few hundred metres through a park, a school ground, the edge of a housing estate. Even a modest opening, its supporters argue, changes something larger. A city that has seen one of its streams returned to the light begins to remember what else lies beneath its feet — and to ask, of every buried river, whether it really must stay buried.`,
      questions: [
        { n: 14, type: "match", group: "minfo", letters: "ABCDEF",
          rubric: "Reading Passage 2 has six paragraphs, A–F. Which paragraph contains the following information? Write the correct letter, A–F. NB You may use any letter more than once.",
          prompt: "reasons why cities originally covered their rivers", answer: "B",
          explain: "Paragraph B explains the motives: polluted streams were blamed for disease, and burying them removed the smell and sickness while creating new land.",
          evidence: "the smell and the sickness went underground, and the city gained valuable land" },
        { n: 15, type: "match", group: "minfo", prompt: "a description of a completed project that changed a city centre", answer: "C", explain: "Paragraph C describes the finished Seoul scheme: the motorway came down, the stream reopened in 2005, and the corridor now cools the city centre.", evidence: "The restored corridor, nearly six kilometres long, opened in 2005" },
        { n: 16, type: "match", group: "minfo", prompt: "a warning about who gains and who loses from river restoration", answer: "E", explain: "Paragraph E carries Mensah's warning: prices and rents rise after restoration, and the campaigners themselves may be forced out of the area.", evidence: "are often the ones who can no longer afford to live beside it" },
        { n: 17, type: "match", group: "minfo", prompt: "an explanation of how an open river copes better with heavy rain", answer: "D", explain: "Paragraph D contrasts a fixed-capacity pipe with an open channel, which slows storm water and lets it spread harmlessly across a floodplain.", evidence: "a river can slow storm water down and cut flooding downstream", vocab: ["storm water", "heavy rain"] },
        { n: 18, type: "match", group: "minfo", prompt: "examples of buried rivers that can never be reopened", answer: "F", explain: "Paragraph F gives the impossible cases: rivers lying many metres down or running directly beneath buildings and railway lines cannot be restored.", evidence: "run directly beneath buildings and railway lines" },
        { n: 19, type: "gap", group: "sum2", note: "ONE WORD ONLY",
          notes: {
            title: "Summary — What daylighting can achieve",
            lines: [
              "The best-known scheme is in Seoul, where the city demolished an elevated {{19}} in order to uncover the Cheonggyecheon stream. In summer, air {{20}} beside the restored water are now several degrees lower than in nearby streets.",
              "Supporters also argue that open rivers are safer in storms: they reduce {{21}} further downstream, because rising water is able to spread out across the {{22}} rather than bursting out of an overloaded pipe.",
            ],
          },
          answer: "motorway",
          explain: "Before the stream could be uncovered, the city had to pull down the elevated motorway built on top of it, which carried 170,000 vehicles a day.",
          evidence: "demolishing an elevated motorway that carried around 170,000 vehicles a day" },
        { n: 20, type: "gap", group: "sum2", answer: "temperatures", explain: "After 'air', the gap needs a plural noun: summer air temperatures beside the water are now several degrees lower than in the streets alongside.", evidence: "air temperatures beside the water are several degrees lower", vocab: ["parallel streets", "nearby streets"] },
        { n: 21, type: "gap", group: "sum2", answer: "flooding", explain: "'Reduce' in the summary paraphrases 'cut' in the passage: an open channel slows storm water and cuts flooding further down the river.", evidence: "slow storm water down and cut flooding downstream", vocab: ["cut", "reduce"] },
        { n: 22, type: "gap", group: "sum2", answer: "floodplain", explain: "The water spreads safely across the river's floodplain instead of bursting out of a pipe; the summary keeps the same concrete noun.", evidence: "the water spreads across its floodplain" },
        { n: 23, type: "match", group: "people", boxTitle: "List of People",
          box: [
            "Grace Ito",
            "Ruth Calloway",
            "Ingrid Solberg",
            "Daniel Mensah",
            "Tomasz Nowak",
          ],
          rubric: "Look at the following statements (Questions 23–26) and the list of people below. Match each statement with the correct person, A–E. NB There is one more person than you need.",
          prompt: "Not every buried river can be returned to the surface.", answer: "E",
          explain: "Nowak, who has audited buried watercourses, states flatly that rivers lying deep down or under buildings can never be brought back.",
          evidence: "'Those can never be brought to the surface,' he says flatly" },
        { n: 24, type: "match", group: "people", prompt: "Buried pipes cannot adapt to storms that are growing worse.", answer: "B", explain: "Calloway explains that a culvert's capacity is fixed on the day it is built, yet it now faces the heavier storms of a changed climate.", evidence: "a buried river is simply a pipe, with a capacity fixed", vocab: ["changed climate", "storms growing worse"] },
        { n: 25, type: "match", group: "people", prompt: "Successful restoration can make an area too expensive for its residents.", answer: "D", explain: "Mensah found property prices and rents rising after daylighting, so the local people who wanted the river often cannot afford to stay.", evidence: "property prices near a daylighted river rise well above the city average", vocab: ["can no longer afford", "too expensive"] },
        { n: 26, type: "match", group: "people", prompt: "Animal life comes back to restored rivers sooner than expected.", answer: "C", explain: "Solberg expected recolonisation to take decades, but insects, fish and herons all appeared within a couple of years of restoration.", evidence: "wildlife returns faster than anyone predicts", vocab: ["faster than anyone predicts", "sooner than expected"] },
      ],
    },
    {
      title: "Passage 3",
      instructions: "You should spend about 20 minutes on Questions 27–40, which are based on Reading Passage 3 below.",
      passageTitle: "The myth of multitasking",
      passage: `Job advertisements demand it, smartphones are engineered for it, and most of us quietly congratulate ourselves on it: the ability to do several things at once. The word itself is borrowed flattery — 'multitasking' originally described computer processors, which appear to run many programs simultaneously by switching between them at enormous speed. Applied to people, the term has come to mean something we believe we do every day: writing a report while following a meeting, messaging while watching a lecture, cooking while helping with homework. Cognitive psychologists, however, have reached an awkward consensus. For any two activities that demand conscious attention, the brain does not run them in parallel. It alternates, hopping rapidly between the tasks like a spotlight jumping between two stages, and what we proudly call multitasking is, in almost every case, task-switching in disguise.

The switching is not free. In laboratory studies, participants asked to alternate between two simple jobs — classifying letters, say, and then digits — consistently work more slowly and make more mistakes than people who do the same tasks one block at a time. Each individual switch costs only a fraction of a second, but the fractions accumulate: for someone whose day consists of continual hopping between email, documents and messages, the lost time becomes substantial. Worse, the cost is not paid only at the moment of the switch. Researchers describe a phenomenon called attention residue: after we turn to a new task, part of the mind stays behind, still processing the unfinished one. The report you abandoned mid-sentence keeps running in the background, degrading your concentration on whatever you look at next. Checking a message 'for one second' is never a one-second transaction.

Could practice remove these costs? It seems reasonable: perhaps people who multitask constantly become expert at it. One influential study put the idea to the test, comparing extreme media multitaskers — people who routinely combined several screens and streams at once — with those who rarely mixed their media. The researchers expected the heavy group to show superior mental filters. The opposite emerged. The heavy multitaskers were worse at ignoring irrelevant information, worse at organising material in memory and, most strikingly of all, slower at switching between tasks — they scored worst precisely on the abilities they exercised most. Later work added an uncomfortable footnote: measured ability and self-belief pull in opposite directions, and the people most confident in their own multitasking were, on average, the worst at it.

There are genuine exceptions, and they are instructive. Two activities can share the brain comfortably when one of them has become so automatic that it barely requires conscious supervision: an adult can walk and argue at the same time, because walking looks after itself. The trouble begins when both tasks make demands. Driving is the classic case. A conversation on a mobile phone measurably slows a driver's reactions to hazards, and the impairment is almost identical whether the phone is held in the hand or used hands-free, because the limit is not where the hands are but where the mind is. A small minority — roughly one person in fifty, dubbed 'supertaskers' by the researchers who identified them — show no measurable cost when doing two demanding things at once. Their existence proves the rule rather than breaking it: statistically, almost everyone who believes they belong to this group is mistaken.

Why, then, does multitasking feel so productive? Part of the answer is emotional. Every new message or window delivers a small jolt of novelty, and a day of constant switching therefore feels stimulating, fast and full. Busyness is easily mistaken for effectiveness. But when researchers measure actual output — words written, problems solved, material remembered — the heaviest switchers produce less, and less accurately, than those who work in longer, quieter stretches. The feeling of productivity and the fact of it come apart: the switching brain is entertained, not efficient.

None of this requires abandoning our devices, and the point is not that technology is destroying our minds; the problem lies in a habit, not a machine. The practical lessons are almost embarrassingly simple. Group similar small jobs — messages, administration — into set batches instead of letting them interrupt at will. Protect unbroken blocks of time for work that matters, with notifications silenced. Above all, close one task — or park it deliberately, with a written note of the next step — before opening another, so that no residue is left behind. The genuinely scarce skill of the coming decades will not be the ability to do many things at once. It will be the old-fashioned opposite: the ability to do one thing at a time, completely, and then move on.`,
      questions: [
        { n: 27, type: "mcq", prompt: "In the first paragraph, what does the writer say the brain does with two attention-demanding tasks?", options: ["A It runs them in parallel, like a computer processor", "B It hands one of them over to automatic control", "C It moves quickly back and forth between them", "D It gives most of its attention to the easier one"], answer: "C", explain: "The brain alternates, hopping rapidly between tasks; option A echoes the computing comparison the writer uses only to explain where the word came from.", evidence: "It alternates, hopping rapidly between the tasks like a spotlight", vocab: ["hopping rapidly", "moves quickly"] },
        { n: 28, type: "mcq", prompt: "The study of extreme media multitaskers found that they", options: ["A struggled to filter out unimportant material", "B organised material in memory more effectively", "C switched between tasks faster than light users", "D judged their own performance accurately"], answer: "A", explain: "The heavy group were worse at ignoring irrelevant information — the filtering the researchers expected them to excel at. Options B and C reverse the findings.", evidence: "The heavy multitaskers were worse at ignoring irrelevant information", vocab: ["irrelevant information", "unimportant material"] },
        { n: 29, type: "mcq", prompt: "The writer mentions hands-free phones in order to show that", options: ["A holding a phone is the main danger for drivers", "B experienced drivers can talk safely while driving", "C driving laws have not kept up with research", "D the real limit on drivers is mental, not physical"], answer: "D", explain: "Hands-free calls impair drivers almost as much as hand-held ones, proving the constraint is attention rather than hands — a mental limit, not a physical one.", evidence: "the limit is not where the hands are but where the mind is", vocab: ["where the mind is", "mental"] },
        { n: 30, type: "mcq", prompt: "The writer refers to 'supertaskers' mainly to emphasise that", options: ["A training can eventually make multitasking safe", "B true exceptions to the rule are very rare", "C laboratory findings do not apply to real driving", "D most people refuse to believe the research"], answer: "B", explain: "Only about one person in fifty shows no switching cost, so genuine exceptions exist but are so uncommon that believing you are one is almost always wrong.", evidence: "roughly one person in fifty", vocab: ["one person in fifty", "very rare"] },
        { n: 31, type: "ynng", prompt: "Constant switching between tasks wastes more time than people realise.", answer: "YES", explain: "YES: each switch costs a fraction of a second, but the writer stresses that these fractions accumulate into substantial lost time over a working day.", evidence: "Each individual switch costs only a fraction of a second, but the fractions accumulate" },
        { n: 32, type: "ynng", prompt: "People's confidence in their own multitasking is a reliable guide to their ability.", answer: "NO", explain: "NO: the writer says the opposite — ability and self-belief pull in opposite directions, and the most confident multitaskers score worst of all.", evidence: "the people most confident in their own multitasking were, on average, the worst" },
        { n: 33, type: "ynng", prompt: "Using a hands-free phone removes most of the danger of talking while driving.", answer: "NO", explain: "NO: the writer states the impairment is almost identical with or without hands on the phone, so going hands-free removes very little of the danger.", evidence: "the impairment is almost identical whether the phone is held in the hand" },
        { n: 34, type: "ynng", prompt: "The sense of productivity that multitasking creates is misleading.", answer: "YES", explain: "YES: switching feels stimulating and full, but measured output falls — the feeling of productivity and the fact of it come apart.", evidence: "The feeling of productivity and the fact of it come apart", vocab: ["mistaken for effectiveness", "misleading"] },
        { n: 35, type: "ynng", prompt: "Employers should ban personal phones during working hours.", answer: "NOT GIVEN", explain: "NOT GIVEN: the writer recommends silencing notifications and batching messages, but never expresses any view about employers banning phones at work.", evidence: "Protect unbroken blocks of time for work that matters, with notifications silenced" },
        { n: 36, type: "match", group: "ends", boxTitle: "Sentence endings",
          box: [
            "depends on finishing one task before turning to the next.",
            "remains occupied with work that has not been completed.",
            "allows the brain to develop a larger working memory.",
            "produces slower and less accurate results than taking the tasks in turn.",
            "performed worst at the very things they did most.",
            "one of them makes almost no demand on conscious attention.",
            "proves that technology causes permanent damage to concentration.",
          ],
          rubric: "Complete each sentence with the correct ending, A–G, below.",
          prompt: "Laboratory experiments show that alternating between two simple jobs", answer: "D",
          explain: "Participants who alternated worked more slowly and made more mistakes than those doing one task at a time — slower and less accurate results.",
          evidence: "work more slowly and make more mistakes than people who do the same tasks", vocab: ["make more mistakes", "less accurate"] },
        { n: 37, type: "match", group: "ends", prompt: "Because of attention residue, part of the mind", answer: "B", explain: "Attention residue means part of the mind stays behind with the unfinished task, still processing it while you try to concentrate on the new one.", evidence: "part of the mind stays behind, still processing the unfinished one", vocab: ["stays behind", "remains occupied"] },
        { n: 38, type: "match", group: "ends", prompt: "In one influential study, the heaviest media multitaskers", answer: "E", explain: "The heavy multitaskers scored worst precisely on the abilities they exercised most — filtering, memory organisation and even switching itself.", evidence: "they scored worst precisely on the abilities they exercised most", vocab: ["abilities they exercised", "things they did"] },
        { n: 39, type: "match", group: "ends", prompt: "Two activities can be combined successfully only when", answer: "F", explain: "Sharing the brain works only when one activity is so automatic, like walking, that it barely needs conscious supervision at all.", evidence: "so automatic that it barely requires conscious supervision" },
        { n: 40, type: "match", group: "ends", prompt: "In the writer's view, real productivity", answer: "A", explain: "The writer's closing advice is to complete or deliberately park one task before opening another, and to value doing one thing at a time.", evidence: "before opening another, so that no residue is left behind" },
      ],
    },
  ],
};
