// Smart LC Upper-Inter Set 14 — Academic Reading (40 questions, 3 passages).
// Original material authored for Smart LC to the blueprint: P1 factual
// history (completion + TFNG), P2 discursive with lettered paragraphs
// (matching paragraph-information + summary + people matching with one
// extra name), P3 argumentative psychology (MCQ-4 + YNNG + wordlist
// summary). Key quotas: TFNG/YNNG balanced with no runs of three, flat
// letters, unique concrete-noun answers, correct MCQ options paraphrase
// the text while distractors echo its wording. Enrichment (explain /
// evidence / vocab) authored inline per the Upper-Intermediate addendum.
export const UPSET14_READING = {
  id: "upset14-reading",
  bookId: "upset14",
  title: "Upper-Inter Set 14 — Reading",
  module: "reading",
  durationMin: 60,
  sections: [
    {
      title: "Passage 1",
      instructions: "You should spend about 20 minutes on Questions 1–13, which are based on Reading Passage 1 below.",
      passageTitle: "The instrument that learned to whisper and thunder",
      passage: `In the year 1700, a keyboard player had two instruments to choose between, and neither would do everything. The harpsichord was the glittering machine of the concert room: when a key was pressed, a small quill plucked the string, producing a bright, silvery tone that carried to the back of any hall. But the pluck was always the same, however the player's fingers moved — press gently or strike furiously, and the note emerged at exactly the same volume. The clavichord, its modest cousin, had the opposite character. Because its strings were touched rather than plucked, the player could shade every note, making it swell or sigh — but only in a whisper. A clavichord suited midnight practice in a private chamber; in a large room it could barely be heard at all.

The man who resolved the dilemma was Bartolomeo Cristofori, a craftsman from Padua employed at the Medici court in Florence to look after the family's collection of instruments. Around 1700 he completed the first example of what a court inventory would soon describe as a "harpsichord with soft and loud". Cristofori abandoned plucking altogether: in his mechanism, pressing a key threw a small hammer against the string, and — this was the ingenious part — the hammer rebounded instantly, leaving the string free to sing, while the loudness of the note faithfully followed the pressure of the finger. It was, in all essentials, the piano. Yet the invention attracted remarkably little attention in Cristofori's lifetime. The new instruments were complicated and costly to build, buyers were few, and only three of them survive today. Even the name shrank: the unwieldy gravicembalo col piano e forte was worn down to pianoforte, and finally to piano.

The idea might have died in Florence had it not travelled. A description of Cristofori's mechanism, complete with a diagram, was published in an Italian journal and later translated into German, where it reached Gottfried Silbermann, the most celebrated organ builder of his day. Silbermann began constructing pianos of his own, and in the 1730s he proudly showed one to Johann Sebastian Bach. The great man's verdict stung: the higher notes were too faint, Bach said, and the touch too heavy for fast playing. Silbermann was reportedly furious — and then quietly spent years improving the action until both faults were gone. Bach's conversion was complete: he praised the later instruments warmly and in 1749 even acted as an agent in the sale of a Silbermann piano, his signature surviving on the receipt.

As the piano spread across Europe, it divided into two schools. Viennese instruments, the kind Mozart played, had a light, shallow action that responded to the smallest movement of the fingers, with a clear singing tone suited to elegant passagework. English pianos, led by the London firm of Broadwood, were sturdier and louder, with a deeper touch that demanded real strength. Composers noticed: Beethoven, who received a Broadwood in 1818, played with such force that he regularly left broken strings behind him, and makers spent the following decades building instruments strong enough to survive their own players.

The decisive reinforcement came from industry. A wooden frame can bear only so much string tension before it twists, and by the 1820s the piano had reached that limit. The way forward appeared in Boston in 1825, when the maker Alpheus Babcock patented a full frame of iron, cast in a single piece, strong enough to carry thicker strings stretched far more tightly. Combined with a new layout that crossed the bass strings over the others, the metal frame transformed the instrument's power: notes rang longer and filled larger halls, and the combined pull of the strings in a modern grand — some twenty tonnes — would reduce Cristofori's delicate woodwork to splinters. The hammers changed too: their leather coverings, which hardened with use, gave way to compressed felt, which struck the string with a rounder, warmer sound and lasted far longer.

By the second half of the nineteenth century the piano had become an industry — and a symbol. Factories in Europe and America produced hundreds of thousands of instruments a year, prices fell within reach of ordinary families, and a piano in the parlour announced that a household was respectable and rising in the world. For millions of children, piano lessons were simply part of growing up. The instrument even learned to perform alone: the player piano, driven by pedals and a perforated paper roll, brought music into homes where nobody could read a note.

The twentieth century ended the monopoly. The phonograph and then the radio offered music without practice or tuning, and piano sales, which had peaked around 1910, fell steeply in the decades that followed. Yet the instrument itself endures. Digital keyboards imitate it, concert halls are still built around it, and the mechanism at its heart remains the one a Paduan craftsman devised three centuries ago: the weight of a finger, translated faithfully into the voice of a string.`,
      questions: [
        { n: 1, type: "gap", prompt: "On a harpsichord, each string was plucked by a small ______.", note: "ONE WORD ONLY", answer: "quill", explain: "The first paragraph describes the harpsichord's mechanism directly: pressing a key made a small quill pluck the string, always at the same volume.", evidence: "a small quill plucked the string" },
        { n: 2, type: "gap", prompt: "Cristofori was employed in Florence to care for the Medici family's ______.", note: "ONE WORD ONLY", answer: "instruments", explain: "'Care for' in the question paraphrases 'look after' in the passage: Cristofori looked after the family's collection of instruments at the Medici court.", evidence: "to look after the family's collection of instruments", vocab: ["look after", "care for"] },
        { n: 3, type: "gap", prompt: "In Cristofori's mechanism, each key threw a small ______ against the string.", note: "ONE WORD ONLY", answer: "hammer", explain: "The second paragraph explains the new mechanism: the key threw a small hammer at the string, which rebounded instantly so the string could sing.", evidence: "pressing a key threw a small hammer against the string" },
        { n: 4, type: "gap", prompt: "Bach felt that the ______ of Silbermann's early pianos was too heavy for rapid playing.", note: "ONE WORD ONLY", answer: "touch", explain: "Bach made two complaints: faint high notes, and a touch too heavy for fast playing. 'Rapid' in the question paraphrases 'fast' in the passage.", evidence: "the touch too heavy for fast playing", vocab: ["fast playing", "rapid playing"] },
        { n: 5, type: "gap", prompt: "In 1749, Bach acted as an ______ when one of Silbermann's pianos was sold.", note: "ONE WORD ONLY", answer: "agent", explain: "After Silbermann improved the action, Bach praised the instruments and even acted as an agent in a sale — his signature survives on the receipt.", evidence: "acted as an agent in the sale of a Silbermann piano" },
        { n: 6, type: "gap", prompt: "Babcock patented a piano frame made of ______ and cast in one piece.", note: "ONE WORD ONLY", answer: "iron", explain: "The fifth paragraph gives the date and place: in Boston in 1825, Babcock patented a full iron frame, cast as a single piece.", evidence: "patented a full frame of iron, cast in a single piece", vocab: ["a single piece", "one piece"] },
        { n: 7, type: "gap", prompt: "The leather once used to cover hammers was replaced by ______.", note: "ONE WORD ONLY", answer: "felt", explain: "'Was replaced by' in the question paraphrases 'gave way to' in the passage: hardening leather coverings gave way to compressed felt.", evidence: "gave way to compressed felt", vocab: ["gave way to", "was replaced by"] },
        { n: 8, type: "tfng", prompt: "The clavichord was too quiet to be heard properly in a large room.", answer: "TRUE", explain: "TRUE: the clavichord could shade every note but only in a whisper, and the passage says it could barely be heard in a large room.", evidence: "in a large room it could barely be heard at all", vocab: ["barely be heard", "too quiet"] },
        { n: 9, type: "tfng", prompt: "Cristofori's invention was an immediate commercial success.", answer: "FALSE", explain: "FALSE: the passage says the opposite — the invention attracted little attention in his lifetime, the instruments were costly, and buyers were few.", evidence: "attracted remarkably little attention in Cristofori's lifetime" },
        { n: 10, type: "tfng", prompt: "Cristofori trained other craftsmen to build his new instrument.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage says only three of his pianos survive and that a published description spread the idea; it never mentions him training anyone.", evidence: "only three of them survive today" },
        { n: 11, type: "tfng", prompt: "Viennese pianos needed less pressure from the player than English ones.", answer: "TRUE", explain: "TRUE: Viennese instruments had a light, shallow action responding to the smallest movement, while English pianos had a deeper touch demanding real strength.", evidence: "responded to the smallest movement of the fingers", vocab: ["smallest movement", "less pressure"] },
        { n: 12, type: "tfng", prompt: "The iron frame reduced the volume that pianos could produce.", answer: "FALSE", explain: "FALSE: the metal frame transformed the instrument's power — notes rang longer and filled larger halls — so volume increased rather than fell.", evidence: "notes rang longer and filled larger halls", vocab: ["filled larger halls", "volume"] },
        { n: 13, type: "tfng", prompt: "Piano sales declined after recorded sound became widely available.", answer: "TRUE", explain: "TRUE: 'declined' paraphrases 'fell steeply' — once the phonograph and radio offered music without practice, sales dropped from their 1910 peak.", evidence: "fell steeply in the decades that followed", vocab: ["fell steeply", "declined"] },
      ],
    },
    {
      title: "Passage 2",
      instructions: "You should spend about 20 minutes on Questions 14–26, which are based on Reading Passage 2 below.",
      passageTitle: "The second life of the golf course",
      passage: `A — The late twentieth century built golf courses the way an earlier age had built railways: in a fever, and on the assumption that demand would never stop growing. In the United States, developers opened new courses at a rate of more than one a day through the 1990s, many wrapped around housing estates whose buyers paid extra for a view of the eighteenth green; Britain, Japan and Australia ran booms of their own. Then the players began to disappear. The number of Americans playing golf fell by roughly five million in the fifteen years after 2003, and much of the golfing world followed the same curve. James Trewin, a consultant who has spent three decades advising course owners, is blunt about what went wrong: "We built for a demand that never arrived. There are simply more courses than the remaining players can support." Hundreds now close every year, each leaving behind the same puzzling asset — fifty hectares or so of shaped, watered, half-wooded land, often inside a town that has nothing else like it.

B — For ecologists, that asset is a rare inheritance. Disused courses are large green spaces close to cities — precisely where wild land is scarcest — and they usually arrive with mature trees, hedgerows and a chain of ponds already in place. What they are not, despite appearances, is nature. The playing surfaces are ecologically closer to carpet than to meadow: a fairway is a single species of grass kept at lawn height for decades, its soil compacted by machinery and dosed with fertiliser and pesticide whose residues linger long after the last round is played. The value of a dead course, ecologists argue, lies not in what it is but in what it sits on — buried seed, old trees, water — and in how little it costs to set those assets loose.

C — What that release looks like was demonstrated at Silvermead, a ninety-year-old course on the edge of Bristol that closed in 2016 and was bought by a conservation trust. The trust's first act was to stop the mowing; its second, harder, was to resist doing much else. Sofia Andersson, the ecologist who leads the monitoring there, expected recovery to take decades. Instead, her survey teams watched something closer to a homecoming. Within three summers, orchids were flowering along the old fairways, skylarks were nesting in grass that had been cut short for ninety years, and nine species of dragonfly had claimed the irrigation ponds. "The seed bank had been waiting under the turf the whole time," Andersson says. "It was less a restoration than a release. Nothing in the literature prepared us for the speed of it."

D — The most valuable return, though, may be measured in water rather than in species. Rachel Kovacs, a hydrologist who has surveyed a dozen closed courses, points out that many were laid out on cheap, low-lying ground beside rivers, kept playable only by a buried network of drains that hurries every rainfall off the land and into the nearest stream. That plumbing, useful to golfers, is exactly what a flood-prone town does not want upstream of it. Where the drains are deliberately blocked, the lowest fairways revert to wetland within a season or two, and the new marshes hold floodwater during storms, releasing it slowly over the following days instead of letting it surge downhill at once. Two English towns have already written former courses into their official flood defences, and Kovacs expects more. "A golf course drains water away from itself; a wetland holds it," she says. "From a flood engineer's point of view, closure is an upgrade."

E — The financial case is quieter but just as strong, says Daniel Whitmore, a planner who has costed conversions for several local authorities. Keeping a course in playable condition is startlingly expensive — mowing, watering and chemical treatment can consume several hundred thousand pounds a year — and almost all of that spending stops the day the mowers do. But Whitmore is impatient with the idea that wild land looks after itself. "A rewilded course is cheap, not free," he warns. Invasive plants advance quickly down abandoned fairways; paths, car parks and fences still need repair; litter does not collect itself. His rule for councils is simple: the money once spent on mowing is better spent on rangers — staff who manage the visitors, watch the habitats and keep the project honest.

F — The final obstacle is rarely ecological. Amina Diallo, who has led the public consultations for three conversion projects, says every one began with anger: former members grieving a club that had anchored their weekends, and neighbours convinced the abandoned land would attract fires and dumped rubbish. What turns opposition into ownership, she has found, is being asked early enough for the answers to count. Residents on her projects chose where the trails would run, named the new meadows, and now lead the volunteer work parties themselves. "People protect what they helped to make," she says. There is a neat symmetry in the whole story. A golf course was, by design, a landscape for the few; handled well, its second life can be the opposite — the same green acres, open at last to everyone.`,
      questions: [
        { n: 14, type: "match", group: "minfo", letters: "ABCDEF",
          rubric: "Reading Passage 2 has six paragraphs, A–F. Which paragraph contains the following information? Write the correct letter, A–F. NB You may use any letter more than once.",
          prompt: "figures showing a fall in the number of people playing golf", answer: "A",
          explain: "Paragraph A gives the numbers: American golfers fell by roughly five million in the fifteen years after 2003, and other countries followed the same curve.",
          evidence: "fell by roughly five million in the fifteen years after 2003", vocab: ["fell by", "a fall in"] },
        { n: 15, type: "match", group: "minfo", prompt: "an explanation of how a former course can protect homes from flooding", answer: "D", explain: "Paragraph D explains the mechanism: blocking the buried drains turns low fairways into marshes that hold floodwater during storms and release it slowly.", evidence: "releasing it slowly over the following days" },
        { n: 16, type: "match", group: "minfo", prompt: "examples of wildlife recorded at a converted course", answer: "C", explain: "Paragraph C lists the species Andersson's teams recorded at Silvermead: orchids on the fairways, nesting skylarks, and nine species of dragonfly in the ponds.", evidence: "nine species of dragonfly had claimed the irrigation ponds", vocab: ["survey teams", "recorded"] },
        { n: 17, type: "match", group: "minfo", prompt: "a warning that a rewilded course still needs money spent on it", answer: "E", explain: "Paragraph E carries Whitmore's warning that a rewilded course is 'cheap, not free': invasive plants, repairs and litter all still demand spending.", evidence: "A rewilded course is cheap, not free", vocab: ["cheap, not free", "still needs money"] },
        { n: 18, type: "gap", group: "sum2", note: "ONE WORD ONLY",
          notes: {
            title: "Summary — Why rewilders want dead golf courses",
            lines: [
              "Disused golf courses are promising sites because they are large green spaces near {{18}}, usually complete with mature trees and ponds.",
              "Their playing surfaces, however, are poor habitat: one species of grass cut short for decades, over soil dosed with {{19}} and pesticide.",
              "At Silvermead, restoration began when the new owners simply stopped the {{20}}; within three summers, {{21}} were flowering on the old fairways.",
              "Elsewhere, blocking buried drains lets low-lying fairways become wetlands that store {{22}} after heavy rain.",
            ],
          },
          answer: "cities",
          explain: "'Near' in the summary paraphrases 'close to' in the passage: disused courses are large green spaces close to cities, exactly where wild land is scarcest.",
          evidence: "large green spaces close to cities", vocab: ["close to", "near"] },
        { n: 19, type: "gap", group: "sum2", answer: "fertiliser", explain: "The summary pairs the gap with 'pesticide', and the passage names the same pair: fairway soil was dosed with fertiliser and pesticide whose residues linger.", evidence: "dosed with fertiliser and pesticide whose residues linger" },
        { n: 20, type: "gap", group: "sum2", answer: "mowing", explain: "'Restoration began' in the summary points to the trust's first act in the passage: it stopped the mowing, and then resisted doing much else.", evidence: "The trust's first act was to stop the mowing", vocab: ["first act", "began"] },
        { n: 21, type: "gap", group: "sum2", answer: "orchids", explain: "The summary keeps the passage's timeframe of three summers; the flowers that appeared on the fairways in that time were orchids.", evidence: "orchids were flowering along the old fairways" },
        { n: 22, type: "gap", group: "sum2", answer: "floodwater", explain: "'Store' in the summary paraphrases 'hold' in the passage: the new marshes hold floodwater during storms and release it slowly afterwards.", evidence: "hold floodwater during storms", vocab: ["hold", "store"] },
        { n: 23, type: "match", group: "people", boxTitle: "List of People",
          box: [
            "James Trewin",
            "Sofia Andersson",
            "Rachel Kovacs",
            "Daniel Whitmore",
            "Amina Diallo",
          ],
          rubric: "Look at the following statements (Questions 23–26) and the list of people below. Match each statement with the correct person, A–E. NB There is one more person than you need.",
          prompt: "Money saved on maintaining turf should pay for staff who look after the site.", answer: "D",
          explain: "Whitmore's rule for councils is exactly this: the money once spent on mowing is better spent on rangers who manage visitors and watch the habitats.",
          evidence: "the money once spent on mowing is better spent on rangers", vocab: ["rangers", "staff"] },
        { n: 24, type: "match", group: "people", prompt: "Local people should help shape a conversion from its earliest stage.", answer: "E", explain: "Diallo found that opposition becomes ownership when residents are asked early enough to matter — hers chose the trails and named the meadows.", evidence: "being asked early enough for the answers to count", vocab: ["early enough", "earliest stage"] },
        { n: 25, type: "match", group: "people", prompt: "More courses were built than the remaining players could support.", answer: "A", explain: "Trewin says the industry built for a demand that never arrived, leaving more courses than the shrinking number of players can sustain.", evidence: "We built for a demand that never arrived" },
        { n: 26, type: "match", group: "people", prompt: "Nature returned to a converted course faster than expected.", answer: "B", explain: "Andersson expected recovery to take decades; instead orchids, skylarks and dragonflies returned within three summers, a speed no literature had prepared her for.", evidence: "Nothing in the literature prepared us for the speed of it", vocab: ["the speed of it", "faster than expected"] },
      ],
    },
    {
      title: "Passage 3",
      instructions: "You should spend about 20 minutes on Questions 27–40, which are based on Reading Passage 3 below.",
      passageTitle: "The deep end of attention",
      passage: `Ask a rock climber halfway up a cliff, a surgeon deep in an operation or a pianist in the middle of a difficult concerto what the best hours of their lives feel like, and the answers converge with uncanny regularity. The task fills awareness completely, leaving no room for worry or self-doubt; action and decision melt into each other; and time misbehaves, so that whole hours pass like minutes. The Hungarian-American psychologist Mihaly Csikszentmihalyi spent fifty years mapping this state. He called it flow, taking the word from the people he interviewed, who described being carried along by the activity "as if by a current".

That such moments exist was never controversial; the problem was studying them. Memory is a poor witness — asked in the evening how the day felt, people smooth, polish and misremember. Csikszentmihalyi's answer was the experience sampling method. Participants carried electronic pagers that sounded at random moments throughout the day; at each signal they stopped and recorded what they were doing and how they felt at that instant. The design's whole purpose was to capture life as it is lived rather than as it is remembered, and over the decades it accumulated hundreds of thousands of snapshots of ordinary experience — the raw material for nearly everything now known about flow.

The snapshots showed that flow is not a matter of luck but of conditions. The challenge of the moment must sit at the edge of the performer's ability: too far below it, and the mind drifts towards anything more interesting; too far above, and anxiety crowds out everything else. The activity must offer clear goals — the climber always knows where the next hold is — and it must return rapid feedback, so that every action announces its own success or failure at once. Where these conditions hold, concentration deepens until self-consciousness disappears, the sense of time becomes unreliable, and the activity becomes what Csikszentmihalyi called autotelic: worth doing for its own sake, whatever it happens to produce.

Sampling ordinary weeks produced the theory's most famous surprise. Adults reported flow far more often at work than in free time; yet the same adults, asked what they wanted, said more leisure. Evenings in front of the television — the largest single use of free time in the records — produced relaxation but almost no flow at all. The paradox has a simple reading: a job, whatever its irritations, arrives with goals, deadlines and feedback already built in, while an empty evening must be given structure by its owner, and structuring an evening is precisely the kind of effort tired people avoid. We are, the data quietly suggest, worse at leisure than we believe.

The theory has attracted serious criticism, and some of it is hard to answer. Everything rests on self-report: no instrument measures flow directly, so researchers must take people's word for a state whose defining feature is that those inside it are not watching themselves. The pager method has an awkward circularity of its own, since the signal that samples the state also interrupts it. And the headline associations — people who report frequent flow are happier, more productive, more satisfied — are correlations only; it may simply be that skilled and secure people both enter flow easily and flourish for unrelated reasons. Research has not proved that flow causes the good outcomes that accompany it, and some psychologists suspect the concept is ordinary concentration wearing a grander name.

A deeper worry has nothing to do with method. Flow is indifferent to the value of whatever produces it. The designers of gambling machines understand its conditions with professional precision — small adjustable challenges, instant results, an unbroken rhythm of play — and the players they capture describe a trance, sometimes called the machine zone, in which money and hours vanish unnoticed. The state that carries a violinist through a concerto will hold a gambler on a stool until dawn. Flow attaches itself to empty or harmful pursuits exactly as readily as to admirable ones, and this neutrality, not any flaw in the data, is the concept's real danger.

None of this has stopped the idea earning its keep. Schools have redesigned lessons so that difficulty rises with the learner and every exercise reports its result at once; workplaces have learned to defend long, uninterrupted stretches of the day, on the evidence that a mind needs twenty minutes to sink back into a task after every disturbance. Used carelessly, flow is a slogan; used carefully, it is a design brief — a checklist of the conditions under which human beings do difficult things well. Whatever its rough edges, the concept endures because it describes people operating at their best, and because it offers teachers, designers and performers a practical recipe for arranging more such hours.`,
      questions: [
        { n: 27, type: "mcq", prompt: "Why did researchers give their participants electronic pagers?", options: ["A to remind them to complete a diary every evening", "B to record how people felt at the moment of the signal", "C to measure how long they could concentrate on a task", "D to test how quickly they responded to interruptions"], answer: "B", explain: "The pagers captured life as it is lived, not as remembered: at each random signal people recorded their activity and feelings at that instant. A echoes the 'evening' trap.", evidence: "capture life as it is lived rather than as it is remembered", vocab: ["at that instant", "at the moment"] },
        { n: 28, type: "mcq", prompt: "According to the third paragraph, flow requires a challenge that", options: ["A has never been attempted by the performer before", "B sits far above what the performer can currently manage", "C is well matched to the performer's present ability", "D promises a worthwhile reward on completion"], answer: "C", explain: "The challenge must sit at the edge of the performer's ability — neither so low the mind drifts nor so high anxiety takes over. B echoes 'too far above', which destroys flow.", evidence: "sit at the edge of the performer's ability", vocab: ["at the edge of", "well matched to"] },
        { n: 29, type: "mcq", prompt: "The writer explains the work–leisure paradox by saying that", options: ["A jobs contain the conditions for flow ready-made", "B people secretly enjoy their jobs more than they admit", "C television is deliberately designed to prevent concentration", "D tired people are unable to experience flow at all"], answer: "A", explain: "A job arrives with goals, deadlines and feedback already built in, while an empty evening must be structured by its owner — 'ready-made' paraphrases 'already built in'.", evidence: "arrives with goals, deadlines and feedback already built in", vocab: ["already built in", "ready-made"] },
        { n: 30, type: "mcq", prompt: "What does the writer conclude about the idea of flow in the final paragraph?", options: ["A It has been quietly abandoned by most schools", "B It cannot be turned into practical advice", "C It is nothing more than a fashionable slogan", "D It remains a useful guide for designing tasks"], answer: "D", explain: "Used carefully, flow is 'a design brief' — a practical recipe for schools, workplaces and performers. C echoes 'slogan', which the writer applies only to careless use.", evidence: "used carefully, it is a design brief", vocab: ["a design brief", "a useful guide"] },
        { n: 31, type: "ynng", prompt: "People in a state of flow may lose track of time.", answer: "YES", explain: "YES: the writer says time misbehaves in flow — whole hours pass like minutes — and later that the sense of time becomes unreliable.", evidence: "time misbehaves, so that whole hours pass like minutes", vocab: ["time misbehaves", "lose track of time"] },
        { n: 32, type: "ynng", prompt: "Flow has been shown to be the cause of people's higher productivity.", answer: "NO", explain: "NO: the writer insists the links are correlations only, and states directly that research has not proved flow causes the good outcomes that accompany it.", evidence: "Research has not proved that flow causes the good outcomes" },
        { n: 33, type: "ynng", prompt: "Csikszentmihalyi objected to gambling designers using his findings.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage says machine designers understand flow's conditions, but reports nothing about Csikszentmihalyi's reaction to that use of his work.", evidence: "The designers of gambling machines understand its conditions with professional precision" },
        { n: 34, type: "ynng", prompt: "Flow can accompany activities that have little real worth.", answer: "YES", explain: "YES: flow is indifferent to value and attaches itself to empty or harmful pursuits — the gambler's machine zone — as readily as to admirable ones.", evidence: "attaches itself to empty or harmful pursuits", vocab: ["empty or harmful pursuits", "little real worth"] },
        { n: 35, type: "ynng", prompt: "The idea of flow has had no influence on how schools organise learning.", answer: "NO", explain: "NO: the final paragraph contradicts this — schools have redesigned lessons so that difficulty rises with the learner and results are reported at once.", evidence: "Schools have redesigned lessons" },
        { n: 36, type: "gap", group: "wl",
          box: ["danger", "skill", "memory", "feedback", "leisure", "time", "pleasure", "work", "effort"],
          boxTitle: "List of Words",
          rubric: "Complete the summary using the list of words, A–I, below.",
          notes: {
            title: "Summary — The anatomy of deep focus",
            lines: [
              "Flow appears when a challenge is well matched to a person's {{36}}, and when the activity offers clear goals and rapid {{37}}.",
              "Those absorbed in it stop watching themselves, and their judgement of {{38}} becomes unreliable.",
              "Pager studies revealed a paradox: the state is reported more often at {{39}} than in free time.",
              "And because a gambling machine can produce it as easily as a concerto, the writer treats flow's blindness to value as its greatest {{40}}.",
            ],
          },
          answer: "B",
          explain: "'Ability' in the passage becomes 'skill' in the summary: the challenge must sit at the edge of what the performer can do — a good match, not a mismatch.",
          evidence: "at the edge of the performer's ability", vocab: ["ability", "skill"] },
        { n: 37, type: "gap", group: "wl", answer: "D", explain: "The passage's second condition fills the gap verbatim: the activity must return rapid feedback, so each action announces its success or failure at once.", evidence: "it must return rapid feedback" },
        { n: 38, type: "gap", group: "wl", answer: "F", explain: "In deep flow, self-consciousness disappears and the sense of time becomes unreliable — so the summary's 'judgement of time' is what fails.", evidence: "the sense of time becomes unreliable" },
        { n: 39, type: "gap", group: "wl", answer: "H", explain: "The famous surprise was where flow lives: adults reported it far more often at work than in the leisure they claimed to want. 'Leisure' (E) is the trap.", evidence: "Adults reported flow far more often at work" },
        { n: 40, type: "gap", group: "wl", answer: "A", explain: "The writer's own word closes the argument: flow's neutrality — its blindness to the value of what produces it — is the concept's real danger.", evidence: "is the concept's real danger", vocab: ["neutrality", "blindness to value"] },
      ],
    },
  ],
};
