// Smart LC Upper-Inter Set 11 — Academic Reading (40 questions, 3 passages).
// Original material authored for Smart LC to the blueprint: P1 factual
// history (completion + TFNG), P2 discursive with lettered paragraphs
// (matching paragraph-information + summary + people matching with one
// extra name), P3 argumentative psychology (MCQ-4 + YNNG + sentence
// endings). Key quotas: TFNG/YNNG balanced with no runs of three, flat
// letters, unique concrete-noun answers, correct MCQ options paraphrase
// the text while distractors echo its wording.
export const UPSET11_READING = {
  id: "upset11-reading",
  bookId: "upset11",
  title: "Upper-Inter Set 11 — Reading",
  module: "reading",
  durationMin: 60,
  sections: [
    {
      title: "Passage 1",
      instructions: "You should spend about 20 minutes on Questions 1–13, which are based on Reading Passage 1 below.",
      passageTitle: "Seeing clearly: a history of eyeglasses",
      passage: `Human eyes wear out on a schedule. From around the age of forty-five, the lens inside the eye begins to stiffen, and close work — reading, sewing, fine carving — slides slowly out of focus. For most of human history there was nothing to be done: craftsmen gave up their trades, and scholars hired young men to read to them. The problem was felt most sharply in the monasteries of medieval Europe, where books were copied entirely by hand and a scribe whose near sight had faded was a serious loss. It was there that the first practical aid appeared: the reading stone, a polished dome of quartz or clear glass laid flat on the page, magnifying the letters beneath it. It worked, but awkwardly — the stone enlarged only a few words at a time and had to be slid along every line.

The decisive step was taken in northern Italy, probably in the 1280s. Some unknown craftsman ground two small convex lenses, set each in a ring of metal, bone or leather, and joined the two rings with a rivet, producing a device that could sit — however unsteadily — in front of both eyes at once. These earliest spectacles had no arms at all: the wearer pinched them onto the nose or simply held them up while reading. As for the inventor, history came tantalisingly close to recording him. In 1306 a friar preaching in Florence told his congregation that the making of spectacles, one of the most useful arts on earth, was not yet twenty years old, and added that he had personally met the man who invented it. He did not, however, mention a name, and no document has ever supplied one.

Those first lenses were all convex, which meant they could do only one job: they helped older people whose close vision had faded, and a short-sighted child was no better off. Lenses ground the other way — concave, thinner at the centre than at the edge — correct the sight of people who cannot see clearly at a distance, and they did not appear until the middle of the fifteenth century. They arrived at a suggestive moment. Printing was spreading across Europe in exactly those decades, and as cheap books created millions of new readers, enormous numbers of people discovered for the first time just how weak their eyes were. Demand exploded. Pedlars carried trays of ready-made spectacles from town to town, and a buyer simply tried pair after pair until the print came sharp.

Quality varied wildly. The finest lenses required exceptionally clear glass, and in Venice, whose glassmakers led Europe, the guild laid down strict rules about the materials from which lenses could be made. Frames were another matter — leather, horn, bone and whalebone were all used — but their great weakness was simpler: they would not stay on. For four centuries, wearers balanced their spectacles on the bridge of the nose, clamped them there with sprung frames that pinched, or, as in Spain, looped cords of silk around each ear. Portraits of the period show scholars holding their spectacles in place with one hand while they turned pages with the other, which rather defeated the point.

The obvious solution took an astonishingly long time. Only in about 1727 did Edward Scarlett, a London optician, begin advertising frames with rigid side pieces that pressed against the head just above the ears — more than four hundred years after spectacles themselves had been invented. Later makers added hinges so that the arms could fold, and curved the ends to hook behind the ear, and with that the modern spectacle frame was essentially complete.

The eighteenth century also produced the bifocal — a lens divided horizontally, with the distance correction above and the reading correction below — usually credited to Benjamin Franklin, who wore such glasses and praised them warmly in his letters. The nineteenth century added science: eye charts, standardised tests and written prescriptions turned lens-fitting from lucky guessing into careful measurement. What changed far more slowly was the image of glasses. For centuries they were treated as an emblem of age and weakness: actors refused to wear them on stage, and public figures took them off to be painted. Only in the twentieth century, when film stars and designers adopted bold frames as a matter of style, did spectacles become fashion — an object chosen as deliberately as a hat.

The materials moved on as well. Most lenses today are made of lightweight plastic rather than glass: it does not shatter, weighs half as much, and accepts coatings that resist scratches and glare. Contact lenses and laser surgery now compete for the same eyes. Yet the story is not finished, because the invention has still not reached everyone. Hundreds of millions of people, most of them in poorer countries, still lack the simple spectacles they need to read, sew, drive or farm safely — a correctable problem, seven centuries old, waiting on nothing more advanced than a pair of lenses in a frame.`,
      questions: [
        { n: 1, type: "gap", prompt: "A reading stone was placed directly on the ______ of a book.", note: "ONE WORD ONLY", answer: "page", explain: "The first paragraph describes the reading stone as a dome of quartz or glass laid flat on the page; 'placed directly on' paraphrases 'laid flat on'.", evidence: "laid flat on the page, magnifying the letters beneath it", vocab: ["laid flat on", "placed directly on"] },
        { n: 2, type: "gap", prompt: "The two lenses of the first spectacles were connected by a ______.", note: "ONE WORD ONLY", answer: "rivet", explain: "The unknown craftsman set each lens in a ring and joined the two rings with a rivet; 'connected' in the question paraphrases 'joined'.", evidence: "joined the two rings with a rivet", vocab: ["joined", "connected"] },
        { n: 3, type: "gap", prompt: "Concave lenses helped people who could not see clearly at a ______.", note: "ONE WORD ONLY", answer: "distance", explain: "Concave lenses correct the sight of people who cannot see clearly at a distance; 'helped' in the question paraphrases 'correct the sight of'.", evidence: "people who cannot see clearly at a distance", vocab: ["correct the sight", "helped"] },
        { n: 4, type: "gap", prompt: "The spread of ______ created millions of new readers in the fifteenth century.", note: "ONE WORD ONLY", answer: "printing", explain: "Printing was spreading across Europe in those decades, and the cheap books it produced created millions of new readers who then discovered their weak eyes.", evidence: "cheap books created millions of new readers" },
        { n: 5, type: "gap", prompt: "Scarlett's frames had side pieces which pressed on the head above the ______.", note: "ONE WORD ONLY", answer: "ears", explain: "Scarlett advertised frames with rigid side pieces pressing against the head just above the ears — the first spectacles that stayed on by themselves.", evidence: "pressed against the head just above the ears" },
        { n: 6, type: "gap", prompt: "Most modern lenses are made from ______ instead of glass.", note: "ONE WORD ONLY", answer: "plastic", explain: "The final paragraph states that most lenses today are made of lightweight plastic rather than glass; 'instead of' paraphrases 'rather than'.", evidence: "made of lightweight plastic rather than glass", vocab: ["rather than", "instead of"] },
        { n: 7, type: "tfng", prompt: "The earliest spectacles had nothing to fix them to the wearer's head.", answer: "TRUE", explain: "TRUE: the passage says these earliest spectacles had no arms at all — wearers pinched them onto the nose or held them up by hand.", evidence: "the wearer pinched them onto the nose or simply held them up", vocab: ["no arms at all", "nothing to fix them"] },
        { n: 8, type: "tfng", prompt: "The name of the person who invented spectacles was recorded at the time.", answer: "FALSE", explain: "FALSE: the friar who claimed to have met the inventor never mentioned his name, and no document has ever supplied one.", evidence: "He did not, however, mention a name" },
        { n: 9, type: "tfng", prompt: "Venetian craftsmen who broke the guild's rules were punished.", answer: "NOT GIVEN", explain: "NOT GIVEN: the guild laid down strict rules about lens materials, but the passage says nothing about what happened to craftsmen who ignored them.", evidence: "the guild laid down strict rules" },
        { n: 10, type: "tfng", prompt: "Frames with side arms appeared more than four centuries after spectacles were invented.", answer: "TRUE", explain: "TRUE: Scarlett's side pieces arrived in about 1727, and the passage states this was more than four hundred years after spectacles were invented.", evidence: "more than four hundred years after spectacles themselves had been invented", vocab: ["four hundred years", "four centuries"] },
        { n: 11, type: "tfng", prompt: "Spectacles were considered attractive accessories from the moment they were invented.", answer: "FALSE", explain: "FALSE: for centuries glasses were an emblem of age and weakness, avoided by actors and removed for portraits; fashion status came only in the twentieth century.", evidence: "treated as an emblem of age and weakness" },
        { n: 12, type: "tfng", prompt: "Many people in the world still do not have the glasses they need.", answer: "TRUE", explain: "TRUE: hundreds of millions of people, mostly in poorer countries, still lack the simple spectacles they need; 'do not have' paraphrases 'lack'.", evidence: "still lack the simple spectacles they need", vocab: ["lack", "do not have"] },
        { n: 13, type: "tfng", prompt: "Contact lenses are now more widely used than spectacles.", answer: "NOT GIVEN", explain: "NOT GIVEN: contact lenses and laser surgery are said to compete with glasses, but the passage never compares how widely each option is used.", evidence: "Contact lenses and laser surgery now compete for the same eyes" },
      ],
    },
    {
      title: "Passage 2",
      instructions: "You should spend about 20 minutes on Questions 14–26, which are based on Reading Passage 2 below.",
      passageTitle: "Painting the town white",
      passage: `A — On a summer afternoon, a large city is a machine for storing heat. Dark asphalt roads, tar-covered roofs and bare concrete absorb sunlight all day and release it slowly through the night, which is why the centre of a big city can be several degrees warmer than the fields around it — a phenomenon known as the urban heat island. The extra heat is not just uncomfortable: it drives up energy use, worsens air quality and, in heat waves, kills. Rooftops matter more than most surfaces, partly because they catch the full force of the midday sun and partly because there are so many of them — roofs make up roughly a quarter of a typical city's surface. As summers intensify, engineers have returned to an idea of almost childlike simplicity: if dark surfaces soak up the sun, paint them white.

B — The idea is far older than the research. Around the Mediterranean, villages have whitewashed their walls and roofs for centuries, renewing the coating each spring before the hot season. The physics is straightforward: a dark roof may reflect only five per cent of the sunlight that strikes it, while a bright white coating can reflect eighty per cent or more, returning most of the sun's energy to the sky before it ever becomes heat. The urban climate scientist Elif Kaya has spent a decade measuring what this means in practice, fixing sensors to rooftops across three cities. 'On a summer afternoon, a black roof in our study reached eighty degrees Celsius,' she says. 'The identical roof next door, coated white, stayed more than thirty degrees cooler. I know of no other climate measure where the effect is so large, so cheap and so easy to see.'

C — Cooler roofs mean cooler rooms, and cooler rooms mean smaller bills. The energy analyst Joana Ferreira has studied apartment buildings before and after coating: directly under the roof, air-conditioning use falls by up to twenty per cent in the hottest weeks. Scaled up to a whole city, the effect reaches the power system itself. On hot afternoons thousands of air conditioners switch on together, and this peak demand strains the power grid to its limits; reflective roofs shave the top off that peak precisely when the strain is greatest. Ferreira stresses that the gains are not only for the wealthy. 'In a flat with no cooling at all, a white roof can bring the indoor temperature down by two or three degrees. The families who can least afford electricity are exactly the ones who get their relief free.'

D — There are, inevitably, complications. A white roof does not stay white: within a few years a coating of dirt and soot dulls the surface, and studies find that reflectivity can fall by a fifth in the first year alone. The materials engineer Samuel Adeyemi regards this as a solvable problem. His laboratory has developed a coating that stays clean by itself: its glassy surface holds dirt so weakly that an ordinary shower of rain washes the particles away. Cold climates raise a different objection, because a roof that reflects the winter sun rejects warmth a building actually wants, slightly raising heating bills in winter. The penalty is real but small — winter days are short and the sun sits low — and in most climates the summer saving outweighs it several times over.

E — Other specialists warn against treating white paint as a miracle cure. The urban planner Ingrid Halvorsen points out that roofs are invisible from the street: cooling them helps the buildings beneath, but does far less for the pedestrian waiting at a bus stop between walls of hot brick. Modelling studies suggest that painting every roof in a large city might lower the average air temperature by only a fraction of a degree, even though the surfaces themselves are dramatically cooler. Her conclusion is not that cool roofs fail, but that they are one instrument in an orchestra: cities should combine reflective roofs with street trees, shaded squares and lighter road surfaces. 'No single surface will cool a city,' she says. 'The tools work together, or they barely work at all.'

F — The approach is nevertheless spreading fast. In New York, volunteers have painted millions of square metres of rooftops under a city programme; Ahmedabad, in India, wrote cool roofs into its official heat plan after a deadly heat wave, starting with the tin-roofed homes of its poorest districts, where indoor temperatures can exceed anything recorded outdoors. For the public-health researcher David Tran, this is the point of the whole idea. Dangerous heat, he notes, does its worst work indoors, at night, among the elderly and the unwell. 'Bring the bedroom temperature down a few degrees and you cut deaths in a heat wave,' he says. 'White paint is not glamorous. It is simply one of the cheapest public-health tools a hot city has.' A century from now, the white roofscapes of the world's cities may seem as obvious as street lighting — and people may wonder why, with the paint already sitting on the shelf, we waited so long.`,
      questions: [
        { n: 14, type: "match", group: "minfo", letters: "ABCDEF",
          rubric: "Reading Passage 2 has six paragraphs, A–F. Which paragraph contains the following information? Write the correct letter, A–F. NB You may use any letter more than once.",
          prompt: "figures showing the temperature difference between a dark roof and a white one", answer: "B",
          explain: "Paragraph B gives Kaya's measurements: a black roof reached eighty degrees Celsius while the identical white-coated roof stayed more than thirty degrees cooler.",
          evidence: "stayed more than thirty degrees cooler", vocab: ["thirty degrees cooler", "temperature difference"] },
        { n: 15, type: "match", group: "minfo", prompt: "a reason why a roof's performance declines over time", answer: "D", explain: "Paragraph D explains that a coating of dirt and soot dulls the surface within a few years, cutting reflectivity by a fifth in the first year.", evidence: "a coating of dirt and soot dulls the surface", vocab: ["dulls the surface", "performance declines"] },
        { n: 16, type: "match", group: "minfo", prompt: "examples of cities that have carried out large-scale roof-painting schemes", answer: "F", explain: "Paragraph F names New York, where volunteers painted millions of square metres, and Ahmedabad, which wrote cool roofs into its official heat plan.", evidence: "volunteers have painted millions of square metres of rooftops", vocab: ["millions of square metres", "large-scale"] },
        { n: 17, type: "match", group: "minfo", prompt: "an explanation of why cities stay warmer than the surrounding countryside", answer: "A", explain: "Paragraph A explains the urban heat island: dark city surfaces absorb sunlight all day and release it at night, keeping the centre warmer than nearby fields.", evidence: "absorb sunlight all day and release it slowly through the night", vocab: ["the fields around it", "surrounding countryside"] },
        { n: 18, type: "match", group: "minfo", prompt: "an argument that reflective roofs should be used together with other measures", answer: "E", explain: "Paragraph E carries Halvorsen's argument: cool roofs are one instrument in an orchestra, to be combined with trees, shaded squares and lighter roads.", evidence: "combine reflective roofs with street trees, shaded squares and lighter road surfaces" },
        { n: 19, type: "gap", group: "sum2", note: "ONE WORD ONLY",
          notes: {
            title: "Summary — How cool roofs help",
            lines: [
              "A dark roof soaks up the sun, but a white surface returns most of that energy to the sky, so the rooms below stay cooler and buildings use less {{19}} for air conditioning.",
              "Because thousands of coolers switch on together on hot afternoons, reflective roofs also cut the peak {{20}} that strains a city's power grid.",
              "The benefit weakens as a roof ages, because a layer of {{21}} slowly dulls the surface.",
              "In cold regions there is a small cost too, since a reflective roof slightly increases heating bills in {{22}}.",
            ],
          },
          answer: "electricity",
          explain: "Air-conditioning use falls by up to a fifth under a coated roof, and Ferreira notes that families who can least afford electricity gain most.",
          evidence: "air-conditioning use falls by up to twenty per cent", vocab: ["air-conditioning use falls", "use less electricity"] },
        { n: 20, type: "gap", group: "sum2", answer: "demand", explain: "When thousands of air conditioners start at once, peak demand strains the grid; cool roofs shave the top off that peak at the worst moment.", evidence: "this peak demand strains the power grid" },
        { n: 21, type: "gap", group: "sum2", answer: "dirt", explain: "The summary's 'layer' matches the passage's 'coating': within a few years dirt and soot dull a white roof and its reflectivity falls.", evidence: "within a few years a coating of dirt and soot dulls the surface", vocab: ["as a roof ages", "within a few years"] },
        { n: 22, type: "gap", group: "sum2", answer: "winter", explain: "A roof that reflects the winter sun rejects warmth the building wants, so heating bills rise slightly — a real but small penalty in cold regions.", evidence: "slightly raising heating bills in winter" },
        { n: 23, type: "match", group: "people", boxTitle: "List of People",
          box: [
            "Elif Kaya",
            "Joana Ferreira",
            "Samuel Adeyemi",
            "Ingrid Halvorsen",
            "David Tran",
          ],
          rubric: "Look at the following statements (Questions 23–26) and the list of people below. Match each statement with the correct person, A–E. NB There is one more person than you need.",
          prompt: "Cooling homes can prevent deaths during periods of extreme heat.", answer: "E",
          explain: "Tran argues that dangerous heat kills indoors, among the elderly and unwell, and that lowering bedroom temperatures cuts deaths in a heat wave.",
          evidence: "you cut deaths in a heat wave", vocab: ["cut deaths", "prevent deaths"] },
        { n: 24, type: "match", group: "people", prompt: "A surface has been created that cleans itself when it rains.", answer: "C", explain: "Adeyemi's laboratory developed a coating whose glassy surface holds dirt so weakly that ordinary rain washes the particles away — it stays clean by itself.", evidence: "a coating that stays clean by itself", vocab: ["washes the particles away", "cleans itself"] },
        { n: 25, type: "match", group: "people", prompt: "Measurements show that a reflective roof stays far cooler than a dark one.", answer: "A", explain: "Kaya fixed sensors to rooftops for a decade: her black study roof reached eighty degrees while the white-coated twin stayed thirty degrees cooler.", evidence: "The identical roof next door, coated white, stayed more than thirty degrees cooler", vocab: ["coated white", "reflective"] },
        { n: 26, type: "match", group: "people", prompt: "White roofs alone will make only a small difference to a city's temperature.", answer: "D", explain: "Halvorsen cites modelling: painting every roof might lower a city's average air temperature by only a fraction of a degree, so other tools are needed.", evidence: "No single surface will cool a city", vocab: ["a fraction of a degree", "a small difference"] },
      ],
    },
    {
      title: "Passage 3",
      instructions: "You should spend about 20 minutes on Questions 27–40, which are based on Reading Passage 3 below.",
      passageTitle: "The planning fallacy",
      passage: `Ask anyone who has renovated a kitchen, written a thesis or launched a piece of software, and you will hear the same story: it took longer than planned — usually much longer — and cost more too. In the 1970s the psychologists Daniel Kahneman and Amos Tversky gave the pattern a name, the planning fallacy: our systematic tendency to underestimate the time, costs and risks of our own future actions, even when we know perfectly well that similar projects have overrun in the past. The definition's sting is in its final clause. We are not ignorant of history; we simply behave as though it does not apply to us. The error is also oddly one-sided: forecasts miss in one direction far more often than the other.

The textbook example stands on the harbour at Sydney. When the Opera House was approved in the late 1950s, planners announced that it would open in 1963 at a cost of seven million Australian dollars. A scaled-down version of the building finally opened in 1973 — a decade late and more than fourteen times over budget. The winning design had been chosen before anyone knew how to build its curved shells. What makes the case instructive is not the size of the error but who made it: professional planners with full information, political pressure to be right and every reason for care, who still underestimated on a heroic scale. The fallacy, in other words, is not a beginner's mistake. It survives expertise, incentives and embarrassment.

It also survives self-knowledge, as a famous study of students showed. Researchers asked final-year students to predict when they would submit their theses, and then to give a worst-case date — an estimate assuming that everything went as poorly as it possibly could. The average student predicted about thirty-four days; the true average turned out to be over fifty-five. More striking still, fewer than half had finished even by their most pessimistic date: a forecast explicitly designed to be gloomy was still, for most people, too hopeful. Curiously, the optimism vanished when the forecast concerned somebody else. Asked to estimate a fellow student's finishing date, observers predicted a friend's delays with uncomfortable accuracy. We are optimists, it seems, only about ourselves. The same optimism turns up well outside the laboratory, in tax returns filed late and in kitchen refits that outrun their quotations.

Why should this be? Kahneman's explanation rests on a distinction between two ways of thinking about a task. The inside view fixes attention on the particular task ahead: we picture the steps of the plan unfolding smoothly, and because obstacles are by nature hard to imagine — the flu, the failed delivery, the colleague who resigns — they are left out of the mental film. The outside view asks a colder question: how long did similar projects take, whoever attempted them? Almost everyone possesses this information, and almost no one consults it, because our own project always feels like a special case. Kahneman liked to tell the story against himself: a team he led once judged its own textbook eighteen months from completion, and took eight years over it. Memory conspires in the trick. Rather than learning from past overruns, we file each one away as an exception, the product of bad luck that will not strike twice, and so experience, on its own, teaches surprisingly little. The bias appears wherever plans are made — among students, engineers, film producers and governments alike.

The remedies follow from the diagnosis. The most direct is known as reference-class forecasting: before trusting an inside estimate, place the project in a class of similar completed projects and let their actual outcomes anchor the forecast. The method has moved from journals into law — governments in Britain and Denmark now require major transport projects to be assessed this way before public money is committed. Humbler tools work at a personal scale. Estimates improve when people unpack a project into its parts and put a time against each one, because the unpacking forces neglected steps into view; the gain is largest for dull stages nobody pictures, such as permissions and deliveries. And commitments made to other people carry unusual force: a deadline set by someone else binds us more tightly than a promise we make privately, which is why writers acquire editors and students discover the strange productivity of the night before a seminar.

It is tempting to conclude that planners should simply be forced into pessimism, but an honest account must concede optimism's uses. If founders, reformers and doctoral students saw the true distribution of outcomes at the start, many valuable things would never be attempted; misplaced confidence is also what gets worthwhile projects started, and the enthusiasm it generates recruits the help that eventually rescues them. The planning fallacy, on this reading, is not a disease to be eradicated but a force to be managed. Keep the hopeful goal, but correct the timetable: aim like an optimist and schedule like a statistician. Holding both habits at once is harder than it sounds. The kitchen will still take longer than you expect. You will merely, for once, have expected it.`,
      questions: [
        { n: 27, type: "mcq", prompt: "The writer uses the Sydney Opera House to show that", options: ["A governments conceal the true cost of public buildings", "B experienced professionals still badly misjudge time and money", "C ambitious buildings should be reduced in scale", "D errors of this size no longer happen today"], answer: "B", explain: "The case matters because professional planners with full information still underestimated hugely; 'misjudge' paraphrases 'underestimated'. Option C echoes the passage's 'scaled-down' wording.", evidence: "underestimated on a heroic scale", vocab: ["underestimated", "misjudge"] },
        { n: 28, type: "mcq", prompt: "What was most striking about the study of students' theses?", options: ["A Most students finished by the date they first predicted", "B Students refused to imagine everything going poorly", "C Predictions became more accurate with practice", "D Even deliberately gloomy forecasts were usually too hopeful"], answer: "D", explain: "Fewer than half the students finished even by their worst-case date, so a forecast designed to be gloomy still proved too hopeful for most.", evidence: "fewer than half had finished even by their most pessimistic date", vocab: ["worst-case", "deliberately gloomy"] },
        { n: 29, type: "mcq", prompt: "According to the writer, people fall into the planning fallacy because they", options: ["A concentrate on the details of the task in front of them", "B possess no information about similar projects", "C enjoy working under the pressure of deadlines", "D remember every past overrun too vividly"], answer: "A", explain: "The inside view fixes attention on the particular task ahead. Option B reverses the text — people possess the information but fail to consult it.", evidence: "we picture the steps of the plan unfolding smoothly", vocab: ["fixes attention on", "concentrate on"] },
        { n: 30, type: "mcq", prompt: "The writer's final position is that", options: ["A optimistic planning should be abandoned entirely", "B accurate schedules discourage ambitious projects", "C hopeful aims should be combined with realistic timetables", "D the fallacy will disappear as forecasting improves"], answer: "C", explain: "The conclusion is to keep the hopeful goal but correct the timetable — aim like an optimist, schedule like a statistician. Option A overstates it.", evidence: "Keep the hopeful goal, but correct the timetable", vocab: ["correct the timetable", "realistic timetables"] },
        { n: 31, type: "ynng", prompt: "People forecast other people's delays more accurately than their own.", answer: "YES", explain: "YES: asked about a fellow student's thesis, observers predicted the delays with uncomfortable accuracy — the optimism applies only to ourselves.", evidence: "predicted a friend's delays with uncomfortable accuracy", vocab: ["uncomfortable accuracy", "more accurately"] },
        { n: 32, type: "ynng", prompt: "The writer believes repeated experience of overruns gradually cures the fallacy.", answer: "NO", explain: "NO: because each overrun is remembered as an exception caused by bad luck, experience on its own teaches surprisingly little — it does not cure the bias.", evidence: "experience, on its own, teaches surprisingly little", vocab: ["teaches surprisingly little", "does not cure"] },
        { n: 33, type: "ynng", prompt: "The planning fallacy affects some professions more severely than others.", answer: "NOT GIVEN", explain: "NOT GIVEN: the bias appears among students, engineers, film producers and governments, but the writer never compares how severely different professions suffer.", evidence: "The bias appears wherever plans are made" },
        { n: 34, type: "ynng", prompt: "Breaking a project into smaller parts can lead to better time estimates.", answer: "YES", explain: "YES: estimates improve when people unpack a project into its parts, because the unpacking forces neglected steps into view; 'breaking' paraphrases 'unpack'.", evidence: "unpack a project into its parts", vocab: ["unpack", "breaking into parts"] },
        { n: 35, type: "ynng", prompt: "The writer thinks optimism serves no useful purpose in planning.", answer: "NO", explain: "NO: the writer concedes optimism's uses — misplaced confidence gets worthwhile projects started and recruits the help that later rescues them.", evidence: "misplaced confidence is also what gets worthwhile projects started" },
        { n: 36, type: "match", group: "ends", boxTitle: "Sentence endings",
          box: [
            "treats a new project as one case within a class of similar ones.",
            "is quietly rewritten so that every overrun seems exceptional.",
            "pictures the current plan unfolding without its obstacles.",
            "shows that every estimate should simply be doubled.",
            "is now compulsory for some large publicly funded projects.",
            "influences behaviour more than a commitment we make privately.",
            "proves that pessimists make the most reliable planners.",
          ],
          rubric: "Complete each sentence with the correct ending, A–G, below.",
          prompt: "The inside view", answer: "C",
          explain: "The inside view imagines the steps of the plan going smoothly; obstacles are hard to imagine, so they are left out of the mental film.",
          evidence: "The inside view fixes attention on the particular task ahead", vocab: ["left out", "without its obstacles"] },
        { n: 37, type: "match", group: "ends", prompt: "The outside view", answer: "A", explain: "The outside view asks how long similar projects took, whoever attempted them — treating the new project as one case among many rather than a special one.", evidence: "how long did similar projects take, whoever attempted them", vocab: ["similar projects", "class of similar ones"] },
        { n: 38, type: "match", group: "ends", prompt: "Reference-class forecasting", answer: "E", explain: "The method has moved into law: Britain and Denmark now require major transport projects — large publicly funded schemes — to be assessed this way.", evidence: "now require major transport projects to be assessed this way", vocab: ["require", "compulsory"] },
        { n: 39, type: "match", group: "ends", prompt: "The memory of earlier projects", answer: "B", explain: "Instead of teaching us, memory files each overrun away as an exception caused by bad luck — the record is quietly rewritten, so nothing is learned.", evidence: "file each one away as an exception", vocab: ["file away as an exception", "seems exceptional"] },
        { n: 40, type: "match", group: "ends", prompt: "A deadline imposed by another person", answer: "F", explain: "A deadline set by someone else binds us more tightly than a private promise, which is why editors and seminar dates produce sudden productivity.", evidence: "binds us more tightly than a promise we make privately", vocab: ["binds us more tightly", "influences behaviour more"] },
      ],
    },
  ],
};
