// Smart LC Pre-IELTS Set 13 — Academic Reading (40 questions, 3 passages).
// Original material authored for Smart LC to the blueprint: P1 factual
// history (completion + TFNG), P2 discursive with lettered paragraphs
// (matching paragraph-information + summary + people matching with one
// extra name), P3 argumentative science (MCQ-4 + YNNG + sentence
// endings). Key quotas: TFNG/YNNG balanced with no runs of three, flat
// letters, unique concrete-noun answers, correct MCQ options paraphrase
// the text while distractors echo its wording.
export const UPSET13_READING = {
  id: "upset13-reading",
  bookId: "upset13",
  title: "Pre-IELTS Set 13 — Reading",
  module: "reading",
  durationMin: 60,
  sections: [
    {
      title: "Passage 1",
      instructions: "You should spend about 20 minutes on Questions 1–13, which are based on Reading Passage 1 below.",
      passageTitle: "A short history of the crossword",
      passage: `People have played games with letters for as long as they have written them. Word squares — small grids that read the same across and down — were scratched onto walls in Roman towns, medieval monks hid names inside acrostic verses, and Victorian magazines entertained their readers with riddles, anagrams and word puzzles of every description. Yet the crossword itself, the interlocking grid with numbered clues that now appears daily in almost every written language, is surprisingly young. It has a precise birthday and a known inventor, and it was created not as a work of art but to fill an awkward empty corner of a newspaper page in a hurry.

The inventor was Arthur Wynne, a journalist who had emigrated from Liverpool to the United States as a young man and eventually took charge of the 'fun' pages of the New York World, a popular Sunday newspaper. In December 1913, needing a fresh novelty for the Christmas issue and short of time, he put together in a single afternoon a puzzle he called a 'word-cross': a diamond-shaped grid of interlocking words, with a numbered clue for each and the word FUN already filled in to start solvers off. A few weeks later a typesetter accidentally reversed the two halves of the name, the puzzle appeared as a 'cross-word', and the mistake stuck. Wynne tinkered with his invention over the following months, introducing black squares and symmetrical grids, and the form we know today quickly settled into place.

The World treated the puzzle as light filler; its readers did not. When the editors tried to leave it out one week, the volume of protest letters persuaded them never to try again. Through the early 1920s other American papers took up the puzzle, and in 1924 two young publishers, gambling the savings of their new firm, produced the first book of crosswords, sold with a sharpened pencil attached. The first printing sold out almost immediately, reprint followed reprint, and the book climbed the bestseller lists. The craze that followed touched every corner of American life. Sales of dictionaries soared, and some libraries rationed the time readers could spend with theirs, so heavy was the demand from solvers. Commuters bent over grids on every train, songwriters produced a hit about a man who lost his sweetheart to the puzzle habit, and doctors warned solemnly of eyestrain. Critics were confident the fad would be forgotten within a year.

Britain caught the infection almost at once, with one grand exception. Most British newspapers were printing crosswords by the mid-1920s, but The Times held out longest, dismissing the puzzle as a childish American fad unworthy of serious readers. In 1930 it finally surrendered and printed a crossword of its own, which has appeared ever since; within a few years its readers were timing themselves against it daily. British setters also transformed the clue itself. In the cryptic crossword, which became the national style, every clue is a miniature riddle containing both a definition and a piece of wordplay, and solving becomes a contest of wit between setter and solver rather than a test of vocabulary alone.

The Second World War gave the crossword its strangest chapter. In 1942 a British newspaper, the Daily Telegraph, organised a competition in which readers tried to solve its daily puzzle in under twelve minutes, under supervision in the paper's own offices. Most of those who managed it assumed the event was nothing more than a publicity stunt. But some of the fastest solvers later received discreet letters inviting them to an interview, and found themselves recruited for wartime codebreaking: the reasoning, never stated publicly at the time, was that a mind quick to untangle clues might untangle enemy ciphers just as well.

Two years later the puzzle fell under official suspicion. In the weeks before the Normandy landings of June 1944, security officers noticed that several of the invasion's most secret code words had appeared, one after another, as answers in the Telegraph's puzzles. It looked alarmingly like espionage in plain sight. The puzzles were traced to a schoolmaster who had compiled them for the paper for many years, and the explanation proved innocent: he often invited his pupils to suggest words for his grids, and the boys had picked up the strange terms from soldiers camped near their school, repeating them with no idea of what they meant. The officers went away satisfied.

A century after Wynne's improvisation, the crossword shows no sign of tiring. Millions of people still begin or end the day with one, competitive solvers race the clock at tournaments, and researchers study whether the habit helps keep ageing memories sharp. Computers can now fill a grid in seconds, and many setters use them, yet the puzzles people love best are still composed, clue by clue, by human beings with a taste for mischief. The empty corner of a holiday page, filled in an afternoon, became the most popular word puzzle in history.`,
      questions: [
        { n: 1, type: "gap", prompt: "Wynne was in charge of the 'fun' pages of a Sunday ______ in New York.", note: "ONE WORD ONLY", answer: "newspaper", explain: "'In charge of' in the question paraphrases 'took charge of' in the passage: Wynne ran the fun pages of the New York World, a Sunday newspaper.", evidence: "the New York World, a popular Sunday newspaper", vocab: ["took charge of", "in charge of"] },
        { n: 2, type: "gap", prompt: "Wynne's first puzzle used a grid in the shape of a ______.", note: "ONE WORD ONLY", answer: "diamond", explain: "The passage describes the 1913 'word-cross' directly: it was a diamond-shaped grid of interlocking words, quite unlike today's square grids.", evidence: "a diamond-shaped grid of interlocking words" },
        { n: 3, type: "gap", prompt: "Each copy of the 1924 crossword book was sold with a ______ attached.", note: "ONE WORD ONLY", answer: "pencil", explain: "The publishers' famous selling idea is stated directly: the first book of crosswords came with a sharpened pencil attached to it.", evidence: "sold with a sharpened pencil attached" },
        { n: 4, type: "gap", prompt: "During the craze, some ______ limited the time solvers could spend with their dictionaries.", note: "ONE WORD ONLY", answer: "libraries", explain: "'Limited' in the question paraphrases 'rationed' in the passage: demand from solvers was so heavy that some libraries rationed dictionary time.", evidence: "some libraries rationed the time readers could spend with theirs", vocab: ["rationed", "limited"] },
        { n: 5, type: "gap", prompt: "Winners of the 1942 competition were secretly recruited for wartime ______.", note: "ONE WORD ONLY", answer: "codebreaking", explain: "'Secretly' in the question matches the discreet letters and the reasoning 'never stated publicly'; the fast solvers were recruited for codebreaking.", evidence: "recruited for wartime codebreaking", vocab: ["discreet letters", "secretly"] },
        { n: 6, type: "gap", prompt: "The Telegraph puzzles containing the code words had been compiled by a ______.", note: "ONE WORD ONLY", answer: "schoolmaster", explain: "The suspicious 1944 puzzles were traced back to their author, a schoolmaster whose pupils had unknowingly supplied the secret words.", evidence: "traced to a schoolmaster who had compiled them for the paper" },
        { n: 7, type: "tfng", prompt: "Games involving letters and words existed long before the twentieth century.", answer: "TRUE", explain: "TRUE: the opening lists Roman word squares, medieval acrostics and Victorian word puzzles — letter games are as old as writing itself.", evidence: "People have played games with letters for as long as they have written them" },
        { n: 8, type: "tfng", prompt: "Wynne spent several months designing his first puzzle.", answer: "FALSE", explain: "FALSE: he was short of time and produced the puzzle in a single afternoon; the months of tinkering came only after it was published.", evidence: "put together in a single afternoon a puzzle" },
        { n: 9, type: "tfng", prompt: "Wynne earned a large amount of money from his invention.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage covers what Wynne created and how he refined it, but says nothing at all about any money he made.", evidence: "Wynne tinkered with his invention over the following months" },
        { n: 10, type: "tfng", prompt: "The first book of crosswords was an immediate commercial success.", answer: "TRUE", explain: "TRUE: 'immediate commercial success' paraphrases the passage — the first printing sold out almost immediately and the book climbed the bestseller lists.", evidence: "The first printing sold out almost immediately", vocab: ["sold out", "commercial success"] },
        { n: 11, type: "tfng", prompt: "The Times printed a crossword before any other British newspaper.", answer: "FALSE", explain: "FALSE: the opposite is stated — most British papers had crosswords by the mid-1920s, while The Times held out longest, until 1930.", evidence: "The Times held out longest" },
        { n: 12, type: "tfng", prompt: "The 1942 competition led to some solvers being offered secret war work.", answer: "TRUE", explain: "TRUE: 'secret war work' paraphrases 'wartime codebreaking' — the fastest solvers received discreet letters and were recruited after interviews.", evidence: "received discreet letters inviting them to an interview", vocab: ["wartime codebreaking", "secret war work"] },
        { n: 13, type: "tfng", prompt: "The schoolmaster stopped compiling puzzles after being investigated.", answer: "NOT GIVEN", explain: "NOT GIVEN: the officers left satisfied with his explanation, but the passage never says whether he carried on compiling puzzles or gave up.", evidence: "The officers went away satisfied" },
      ],
    },
    {
      title: "Passage 2",
      instructions: "You should spend about 20 minutes on Questions 14–26, which are based on Reading Passage 2 below.",
      passageTitle: "Sheep in the city",
      passage: `A — On spring mornings in a growing number of cities, park visitors arrive to find that the mowing has been handed over to sheep. Paris introduced a small flock in 2013 to trim the grass around a public archive building, and flocks now graze parks and roadside banks in Munich, Rotterdam and a string of smaller European towns; several university campuses in the United States have followed. The practice has acquired a name — eco-grazing — and a professional niche: shepherds who move compact flocks from site to site through the year, renting out their animals as living lawnmowers. What began as a piece of municipal theatre has settled, in many places, into ordinary maintenance policy.

B — The economic case is less straightforward than enthusiasts suggest. Ruth Calder, an agricultural economist who has audited grazing schemes in three countries, points out that sheep are routinely advertised as the cheap option and rarely are: a flock needs a shepherd's wages, electric fencing, transport between sites, veterinary care and somewhere to spend the winter, and once these are added up, a season of grazing usually costs a city roughly what a mowing contract would. Where sheep win decisively, she says, is on ground that machines cannot work: they graze steep slopes and banks too dangerous for ride-on mowers, slip between memorials and under benches that blades cannot reach, and do it all without noise or fuel. For steep cemeteries and flood embankments, Calder argues, the real question is not whether sheep are cheaper than machines, but that machines were never truly an option.

C — The ecological case is easier to make. The ecologist Marco Bianchi has spent five years comparing mown and grazed plots in the same parks. A mower, he notes, cuts an entire meadow to the same height in a single afternoon — an instant catastrophe for the insects living in it. Sheep remove the grass gradually and selectively, leaving patches of longer growth, so wildflowers survive to flower and set seed instead of being beheaded in June. The uneven turf they leave offers shelter at every height, and their dung supports beetles that in turn feed birds. In Bianchi's plots the number of butterflies more than doubled within three seasons of the switch. Grazing, he concludes, does not merely maintain a green surface; it slowly rebuilds a habitat.

D — The social effects have surprised even the schemes' supporters. The social researcher Anneke Visser spent two summers observing and interviewing in city parks that host flocks. Visitors linger noticeably longer when the sheep are present, she found; strangers fall into conversation at the fence, and children who ignore flowerbeds will watch a flock for an hour. The shepherd becomes a minor public figure, greeted and questioned by people who have never once spoken to a park keeper. In several parks the flock's arrival each spring is now treated as a small festival. Early complaints about smell and droppings faded within weeks, her interviews suggest. Sheep, Visser argues, change what a park is for: a space people cross becomes a place where they stay.

E — Patrick Doyle, a parks officer who manages flocks for a large northern city, supplies the caution. By far the greatest danger to an urban flock, he says, is dogs: a single dog off its lead can injure or kill a sheep in seconds, and owners routinely insist that their pet would never do such a thing until the moment it does. Most of his losses have happened this way, and every flock in his care now grazes behind double electric fencing. The animals need checking every day, fresh water through the summer, and moving before the grass is worn bare; discarded litter is dangerous if swallowed; and thefts, though rare, are not unknown. Urban grazing, Doyle says, is not a service you switch on but animal husbandry conducted in public, and a city that forgets this will soon own a field of sick sheep.

F — And then there is the wool. The textile researcher Naomi Tanaka studies what happens to the fleeces city flocks produce, because animal welfare requires that sheep be shorn every year whether anyone wants the result or not. Wool prices have fallen so far that shearing a sheep generally costs more than the fleece will fetch: the wool of a city flock is, commercially, almost worthless. Tanaka's response has been to look for value elsewhere. Pilot projects have turned park fleeces into insulation panels for garden buildings, mulch mats that suppress weeds around newly planted trees, and blankets sold as souvenirs of a named park and its flock — products that sell on their story rather than their fibre. The income is small but real, and it completes a satisfying circle. The urban sheep, Tanaka suggests, earns its place not by any single service but by the sum of them: it cuts the grass, feeds the soil, gathers a crowd, and may yet furnish the picnic blanket too.`,
      questions: [
        { n: 14, type: "match", group: "minfo", letters: "ABCDEF",
          rubric: "Reading Passage 2 has six paragraphs, A–F. Which paragraph contains the following information? Write the correct letter, A–F. NB You may use any letter more than once.",
          prompt: "examples of cities where sheep already graze public spaces", answer: "A",
          explain: "Paragraph A names Paris, Munich and Rotterdam, plus American campuses — the places where eco-grazing is already ordinary maintenance policy.",
          evidence: "flocks now graze parks and roadside banks in Munich, Rotterdam" },
        { n: 15, type: "match", group: "minfo", prompt: "an explanation of why mowing is more harmful to insects than grazing", answer: "C", explain: "Paragraph C contrasts the two directly: a mower flattens a whole meadow in an afternoon, while sheep feed gradually and selectively.", evidence: "an instant catastrophe for the insects living in it", vocab: ["catastrophe", "harmful"] },
        { n: 16, type: "match", group: "minfo", prompt: "a description of the threat that dogs pose to urban flocks", answer: "E", explain: "Paragraph E carries Doyle's warning: dogs are the greatest danger, and most of his losses have come from attacks by pets off the lead.", evidence: "a single dog off its lead can injure or kill a sheep in seconds", vocab: ["danger", "threat"] },
        { n: 17, type: "match", group: "minfo", prompt: "examples of ground where machines cannot safely operate", answer: "B", explain: "Paragraph B lists the places where sheep beat machines: steep slopes and banks, and the awkward spaces between memorials and under benches.", evidence: "slip between memorials and under benches that blades cannot reach", vocab: ["too dangerous for", "cannot safely"] },
        { n: 18, type: "match", group: "minfo", prompt: "attempts to find uses for the wool of city flocks", answer: "F", explain: "Paragraph F describes Tanaka's pilot projects: insulation panels, mulch mats and souvenir blankets made from the fleeces of park flocks.", evidence: "Pilot projects have turned park fleeces into insulation panels", vocab: ["fleeces", "wool"] },
        { n: 19, type: "gap", group: "sum2", note: "ONE WORD ONLY",
          notes: {
            title: "Summary — What sheep offer a city",
            lines: [
              "Grazing is often no cheaper than machine mowing, but sheep can feed on the steep {{19}} that are dangerous for mowers, and they work without engine noise or {{20}}.",
              "Unlike a machine, which cuts a whole meadow in one afternoon, sheep eat slowly and selectively, so {{21}} are able to flower and set seed.",
              "In one five-year comparison of mown and grazed plots, the number of {{22}} more than doubled within three seasons.",
            ],
          },
          answer: "slopes",
          explain: "After 'steep', the gap needs a plural noun for ground: sheep graze the steep slopes and banks that ride-on mowers cannot safely reach.",
          evidence: "they graze steep slopes and banks too dangerous for ride-on mowers" },
        { n: 20, type: "gap", group: "sum2", answer: "fuel", explain: "The summary pairs 'engine noise' with the other thing sheep need none of; the passage says they do the work without noise or fuel.", evidence: "do it all without noise or fuel" },
        { n: 21, type: "gap", group: "sum2", answer: "wildflowers", explain: "Because sheep feed gradually, wildflowers escape the fate a mower deals them and get the chance to flower and set seed.", evidence: "wildflowers survive to flower and set seed", vocab: ["survive", "are able to"] },
        { n: 22, type: "gap", group: "sum2", answer: "butterflies", explain: "The doubling figure comes from Bianchi's plots: after the switch to grazing, butterflies more than doubled in number within three seasons.", evidence: "the number of butterflies more than doubled within three seasons" },
        { n: 23, type: "match", group: "people", boxTitle: "List of People",
          box: [
            "Ruth Calder",
            "Marco Bianchi",
            "Anneke Visser",
            "Patrick Doyle",
            "Naomi Tanaka",
          ],
          rubric: "Look at the following statements (Questions 23–26) and the list of people below. Match each statement with the correct person, A–E. NB There is one more person than you need.",
          prompt: "The presence of sheep changes how long people spend in a park.", answer: "C",
          explain: "Visser's observation research found visitors linger noticeably longer when the flock is present — the park becomes a place where people stay.",
          evidence: "Visitors linger noticeably longer when the sheep are present", vocab: ["linger", "spend longer"] },
        { n: 24, type: "match", group: "people", prompt: "Grazing does not necessarily cost a city less than machine mowing.", answer: "A", explain: "Calder's audits show the supposed savings usually vanish once wages, fencing, transport and winter housing are counted against a mowing contract.", evidence: "usually costs a city roughly what a mowing contract would" },
        { n: 25, type: "match", group: "people", prompt: "The fleeces of urban flocks currently have very little market value.", answer: "E", explain: "Tanaka points out that shearing generally costs more than the fleece will fetch, making city wool commercially almost worthless at present.", evidence: "the wool of a city flock is, commercially, almost worthless", vocab: ["almost worthless", "very little value"] },
        { n: 26, type: "match", group: "people", prompt: "Urban flocks require constant practical attention.", answer: "D", explain: "Doyle stresses the daily reality: checking the animals, providing water, moving fences and guarding against litter and theft — husbandry in public.", evidence: "The animals need checking every day", vocab: ["checking every day", "constant attention"] },
      ],
    },
    {
      title: "Passage 3",
      instructions: "You should spend about 20 minutes on Questions 27–40, which are based on Reading Passage 3 below.",
      passageTitle: "The urge to know",
      passage: `Of all the mental appetites, curiosity has had the strangest reputation. For centuries it was treated as a vice: moralists ranked the hunger to know other people's business alongside greed and envy, the proverb still insists that curiosity killed the cat, and for a long time scientists themselves dismissed the subject as too trivial, or too vague, to study. Over the past three decades that neglect has ended. Curiosity is now the object of serious research by psychologists, neuroscientists and economists, and the picture emerging from their work is of a force far more central to learning — and far easier to manipulate — than its reputation ever suggested.

The most influential modern account describes curiosity as the feeling produced by an information gap. We become curious, on this view, when we become aware of a gap between what we know and what we want to know — when a question has been opened in the mind and left unanswered. The feeling has more in common with hunger or thirst than with idle amusement: it is an itch to obtain something specific, and it is triggered not by ignorance itself but by noticing the ignorance. Nobody is curious about the things they do not know they do not know.

The account explains an otherwise puzzling pattern: curiosity is weakest at the two extremes of knowledge. People who know nothing about a subject have no hooks to hang a question on, while people who believe they know everything have no questions left; curiosity peaks in between, when we know enough to ask but not enough to answer. A chess beginner shrugs at a famous position, a grandmaster finds it obvious, and the club player in the middle cannot stop thinking about it. Teachers meet this curve daily: a lesson that opens gaps — that walks students to the edge of what they can currently explain, and pauses there — reliably generates more questions than a lesson that simply delivers information in finished form.

The consequences for memory are striking. In a series of experiments, volunteers read trivia questions and rated how curious they were about each answer while their brains were scanned. During the wait for each answer, photographs of faces — completely unrelated to the questions — were flashed on the screen. The next day, the volunteers remembered best not only the answers they had been most curious about, but also the faces that had happened to appear while their curiosity was high. Curiosity, the researchers concluded, opens a window in which the brain absorbs whatever arrives, related or not; the scans showed the brain's reward circuitry anticipating information much as it anticipates food. A curious mind, for a few seconds, is simply a better recorder.

Not all curiosity feels the same, however. Researchers distinguish an open, pleasurable form — the unhurried interest that keeps a person browsing in a library — from a deprivation form: the nagging, almost irritating need to close one specific gap, familiar to anyone who has lain awake trying to retrieve an actor's name. Deprivation curiosity feels closer to discomfort than to pleasure, and it is much the stronger motivator of the two: people will pay, queue and click to make it stop.

It is often claimed that schooling extinguishes this appetite — that children arrive as question machines and leave as answer machines. The evidence is murkier than the slogan. What is well documented is that question-asking becomes rare in classrooms, and that classrooms reward producing correct answers far more than asking good ones; a child learns quickly which behaviour earns approval. Whether the underlying appetite shrinks, or merely goes quiet where it is not welcome, is far harder to measure, and the widely repeated image of a steady decline from infancy onwards may be too neat a story to trust.

Nor is the appetite always benign. People choose to look at disturbing images even when they accurately predict that they will regret it — a phenomenon researchers call morbid curiosity — because the pull of an open gap can override the preference for comfort. And what research can describe, commerce can exploit. The clickbait headline is information-gap theory applied for profit: it deliberately opens a gap — 'what happened next will surprise you' — and is in no hurry to close it, since the click, not the answer, is the point. Curiosity, like any appetite, can be fed junk.

The conclusion now emerging is that curiosity behaves less like a fixed trait than like an appetite in another sense too: it grows with feeding. Environments that pose questions, tolerate wrong turns and give people time to explore produce more of it; environments that punish uncertainty produce less. That is an optimistic finding, since it means nobody is condemned to incuriosity, and at the same time a warning, because appetites can be starved as easily as fed. The researchers who once thought curiosity too trivial to study have arrived somewhere close to the opposite view: that the urge to know is one of the most valuable resources a mind possesses — and, like most valuable resources, it repays careful management.`,
      questions: [
        { n: 27, type: "mcq", prompt: "What does the writer say about curiosity in the first paragraph?", options: ["A Moralists were the first to study it systematically", "B Scientists have always regarded it as central to learning", "C A quality once condemned has become a respectable subject of research", "D The proverb about the cat has been proved wrong"], answer: "C", explain: "Curiosity was treated as a vice and dismissed as trivial, but three decades of serious research have ended that neglect. Options A, B and D echo words without matching the point.", evidence: "For centuries it was treated as a vice", vocab: ["treated as a vice", "once condemned"] },
        { n: 28, type: "mcq", prompt: "According to the passage, curiosity about a subject is strongest in people who", options: ["A know nothing at all about it", "B believe they know everything about it", "C have no questions left to ask", "D know something about it but cannot yet explain everything"], answer: "D", explain: "Curiosity peaks between the two extremes of knowledge — the club player, not the beginner or the grandmaster. Options A, B and C describe the low points of the curve.", evidence: "curiosity peaks in between, when we know enough to ask but not enough to answer" },
        { n: 29, type: "mcq", prompt: "The trivia experiments showed that a state of curiosity", options: ["A improves memory even for unrelated material", "B makes people forget the original questions", "C is weakened by brain scanning", "D depends on photographs of faces"], answer: "A", explain: "The faces had nothing to do with the questions, yet those shown during high curiosity were remembered better — the brain briefly absorbs everything.", evidence: "the brain absorbs whatever arrives, related or not", vocab: ["related or not", "unrelated"] },
        { n: 30, type: "mcq", prompt: "The writer mentions clickbait headlines as an example of", options: ["A journalism that answers questions quickly", "B the information gap being exploited for profit", "C morbid curiosity in the digital age", "D environments that punish uncertainty"], answer: "B", explain: "A clickbait headline is described as information-gap theory applied commercially: it opens a gap to harvest the click, not to deliver the answer.", evidence: "information-gap theory applied for profit", vocab: ["for profit", "exploited commercially"] },
        { n: 31, type: "ynng", prompt: "Curiosity requires an awareness that a specific piece of knowledge is missing.", answer: "YES", explain: "YES: the writer states that curiosity is triggered not by ignorance itself but by noticing it — nobody wonders about unknown unknowns.", evidence: "triggered not by ignorance itself but by noticing the ignorance", vocab: ["noticing the ignorance", "awareness"] },
        { n: 32, type: "ynng", prompt: "Teachers would like more training in how to encourage curiosity.", answer: "NOT GIVEN", explain: "NOT GIVEN: teachers are mentioned only as people who meet the curiosity curve daily; nothing is said about what training they want.", evidence: "Teachers meet this curve daily" },
        { n: 33, type: "ynng", prompt: "Schools reward correct answers more than good questions.", answer: "YES", explain: "YES: the writer states this as well documented — classrooms reward producing correct answers far more than asking good ones.", evidence: "classrooms reward producing correct answers far more than asking good ones" },
        { n: 34, type: "ynng", prompt: "Curiosity always benefits the person who feels it.", answer: "NO", explain: "NO: the writer says the appetite is not always benign — morbid curiosity draws people to things they correctly predict they will regret.", evidence: "Nor is the appetite always benign", vocab: ["benign", "benefits"] },
        { n: 35, type: "ynng", prompt: "The writer believes a person's level of curiosity cannot be changed.", answer: "NO", explain: "NO: the conclusion argues the opposite — curiosity behaves like an appetite that grows with feeding, so nobody is condemned to incuriosity.", evidence: "curiosity behaves less like a fixed trait than like an appetite", vocab: ["fixed trait", "cannot be changed"] },
        { n: 36, type: "match", group: "ends", boxTitle: "Sentence endings",
          box: [
            "were remembered although they had no connection with the questions.",
            "can be fed and strengthened like an appetite.",
            "notice a gap between what they know and what they want to know.",
            "declines steadily once children start school.",
            "feels closer to discomfort than to pleasure.",
            "deliberately opens a gap that it is slow to close.",
            "depends mainly on how much a person already knows.",
          ],
          rubric: "Complete each sentence with the correct ending, A–G, below.",
          prompt: "On the information-gap account, people become curious when they", answer: "C",
          explain: "The theory's core claim: curiosity is the feeling produced when a gap opens between present knowledge and desired knowledge.",
          evidence: "a gap between what we know and what we want to know" },
        { n: 37, type: "match", group: "ends", prompt: "In the trivia experiments, photographs of faces", answer: "A", explain: "The faces were completely unrelated to the trivia, yet those shown during moments of high curiosity were still remembered better the next day.", evidence: "the faces that had happened to appear while their curiosity was high", vocab: ["unrelated to", "no connection with"] },
        { n: 38, type: "match", group: "ends", prompt: "Deprivation curiosity, unlike simple interest,", answer: "E", explain: "The two forms are contrasted directly: open interest is pleasurable, while the deprivation form is a nagging itch nearer to discomfort.", evidence: "Deprivation curiosity feels closer to discomfort than to pleasure" },
        { n: 39, type: "match", group: "ends", prompt: "The writer says a clickbait headline", answer: "F", explain: "'Slow to close' in the ending paraphrases 'in no hurry to close it': the headline profits from the open gap, not from answering it.", evidence: "is in no hurry to close it", vocab: ["in no hurry", "slow"] },
        { n: 40, type: "match", group: "ends", prompt: "The writer concludes that curiosity", answer: "B", explain: "'Fed and strengthened' paraphrases the final image of an appetite that grows with feeding — and can equally be starved by unwelcoming environments.", evidence: "it grows with feeding", vocab: ["grows with feeding", "fed and strengthened"] },
      ],
    },
  ],
};
