// Smart LC Upper-Inter Set 9 — Academic Reading (40 questions, 3 passages).
// Original material authored for Smart LC to the blueprint: P1 factual
// history (completion + TFNG), P2 discursive with lettered paragraphs
// (matching paragraph-information + summary + people matching with one
// extra name), P3 argumentative psychology (MCQ-4 + YNNG + sentence
// endings). Key quotas: TFNG/YNNG balanced with no runs of three, flat
// letters, unique concrete-noun answers, correct MCQ options paraphrase
// the text while distractors echo its wording.
export const UPSET9_READING = {
  id: "upset9-reading",
  bookId: "upset9",
  title: "Upper-Inter Set 9 — Reading",
  module: "reading",
  durationMin: 60,
  sections: [
    {
      title: "Passage 1",
      instructions: "You should spend about 20 minutes on Questions 1–13, which are based on Reading Passage 1 below.",
      passageTitle: "The invention of the alphabet",
      passage: `Writing was invented from scratch at least three times — in Mesopotamia, in China and in Central America — but the alphabet, as far as scholars can tell, was invented only once. Every alphabet in use today, from the Latin letters on this page to Greek, Arabic, Hebrew and the many scripts of South Asia, descends from a single ancestor devised about four thousand years ago. And when the evidence of its origin finally came to light, it held a genuine surprise: the most successful writing system in history appears to have been created not by scholars but by workers who could barely read at all.

The writing systems that came first were powerful but punishing. Mesopotamian cuneiform, pressed into damp clay with the cut end of a reed, and Egyptian hieroglyphs, painted onto temple walls and rolls of papyrus, each used many hundreds of signs. Some signs stood for whole words, some for syllables, and others were silent markers that showed what kind of word had been written. Mastering such a system meant memorising them all, and the training lasted years. Those who completed it — the scribes — formed a small professional class on whom kings, priests and merchants depended, and they guarded the status that their rare skill brought. For its first fifteen centuries, writing belonged to specialists.

The alphabet rests on a different and far more economical idea: a sign should record neither a word nor a syllable but a single speech sound. Any language uses only a few dozen of these, so a complete writing system suddenly requires not eight hundred characters but roughly twenty-five. Learning to read stops being a career and becomes a winter's project. It is the kind of simplification that looks obvious once it exists — and people had been writing for well over a thousand years before anyone made it.

The earliest known alphabetic inscriptions come from the Sinai desert, at a place called Serabit el-Khadim, where Egyptian expeditions worked remote turquoise mines around 1900 BC. Among the workforce were labourers from Canaan, to the north-east, and on rocks and small stone objects they carved short messages in their own language. They were not trained scribes; most of them, Egyptologists believe, could not read Egyptian at all. But they had seen hieroglyphs on monuments and offerings, and they borrowed the appearance of that writing for an entirely new purpose.

Their method was beautifully simple. Each letter was a small picture of a familiar object, and it stood for the first sound of that object's name. A drawing of an ox — aleph in their language — meant the sound at the beginning of aleph; a drawing of a house, bet, meant b; a wavy line of water, mem, meant m. Once the rule is grasped, anyone who can speak the language can sound out a written word, which is exactly what made the invention so difficult to contain.

The script found its great carriers in the Phoenicians, the sea-going merchants of the eastern Mediterranean coast. By around 1000 BC they had trimmed the letters down to a brisk practical set of twenty-two — all consonants, since their language allowed the vowels to be guessed — and Phoenician traders spread the system to every harbour they visited, from Cyprus to North Africa and Spain. Writing travelled not with armies or priests but with cargoes of cloth, glass and purple dye. Remarkably, the sequence of the letters was already fixed by this time: ancient practice tablets survive that list them in an order whose beginning any modern child would recognise.

The Greeks, who met the script through trade, made the change that completed it. Greek words could not be read from consonants alone, so Greek adapters, probably in the eighth century BC, took over Phoenician letters for sounds their own language did not use and turned them into a, e, i, o and u. The result was the first alphabet to record vowels as fully as consonants — the first, in other words, that could show more or less exactly how a sentence sounded. Early Greek writing ran right to left, as Phoenician did, and for a while it was written boustrophedon, 'as the ox turns' — one line running rightward and the next back leftward, the way a field is ploughed. Only gradually did the left-to-right habit win.

From Greece the letters passed to Italy — reaching Rome not directly but by way of the Etruscans, the older civilisation of central Italy, whose version of the Greek letters the Romans reshaped to fit Latin. The capital forms the Romans chiselled into stone monuments have scarcely changed in two thousand years. Our small letters have a humbler origin: written quickly with a pen on papyrus and parchment, the stately capitals softened, looped and shrank, until by the early Middle Ages these fluent pen-made shapes had become a distinct set of letters, later paired by printers with capitals.

Traces of the miners' pictures survive in plain sight. Alpha and beta mean nothing in Greek; they are simply aleph and bet — the ox and the house — worn smooth by three thousand years of borrowing. The names travelled with the letters, and so did the idea beneath them: that writing can belong to anyone who can speak. Of all the inventions of the ancient world, none has been so thoroughly shared.`,
      questions: [
        { n: 1, type: "gap", prompt: "The earliest writing systems each used many hundreds of ______.", note: "ONE WORD ONLY", answer: "signs", explain: "The second paragraph describes cuneiform and hieroglyphs, the systems that came first, and states directly that each used many hundreds of signs.", evidence: "each used many hundreds of signs" },
        { n: 2, type: "gap", prompt: "The first alphabetic messages were scratched by workers at remote turquoise ______.", note: "ONE WORD ONLY", answer: "mines", explain: "'Scratched' in the question paraphrases 'carved' in the passage: labourers at the Sinai turquoise mines carved short messages on rocks and small stone objects.", evidence: "Egyptian expeditions worked remote turquoise mines", vocab: ["carved", "scratched"] },
        { n: 3, type: "gap", prompt: "Every letter began as a picture of a familiar ______.", note: "ONE WORD ONLY", answer: "object", explain: "The method paragraph explains that each letter was a small picture of a familiar object, standing for the first sound of that object's name.", evidence: "a small picture of a familiar object", vocab: ["drawing", "picture"] },
        { n: 4, type: "gap", prompt: "Phoenician ______ carried the letters to ports around the Mediterranean.", note: "ONE WORD ONLY", answer: "traders", explain: "'Carried' in the question paraphrases 'spread' in the passage: Phoenician traders spread the twenty-two letters to every harbour they visited.", evidence: "Phoenician traders spread the system", vocab: ["spread", "carried"] },
        { n: 5, type: "gap", prompt: "The Greek alphabet was the first to record ______ as well as consonants.", note: "ONE WORD ONLY", answer: "vowels", explain: "The Greeks turned unneeded Phoenician letters into a, e, i, o and u, producing the first alphabet to record vowels as fully as consonants.", evidence: "the first alphabet to record vowels" },
        { n: 6, type: "gap", prompt: "Small letters developed from shapes made quickly with a ______.", note: "ONE WORD ONLY", answer: "pen", explain: "The passage says the stately capitals softened and shrank when written quickly with a pen, and these pen-made shapes became our small letters.", evidence: "written quickly with a pen on papyrus and parchment" },
        { n: 7, type: "tfng", prompt: "Learning to write in early Mesopotamia or Egypt took years of study.", answer: "TRUE", explain: "TRUE: mastering hundreds of signs meant memorising them all, and the passage states plainly that the training lasted years.", evidence: "the training lasted years", vocab: ["lasted years", "years of study"] },
        { n: 8, type: "tfng", prompt: "The alphabet was created by highly educated professional writers.", answer: "FALSE", explain: "FALSE: the inventors were Canaanite labourers at the mines, and the passage says they were not trained scribes and mostly could not read Egyptian.", evidence: "They were not trained scribes", vocab: ["labourers", "workers"] },
        { n: 9, type: "tfng", prompt: "Phoenician writing contained letters for consonants but not for vowels.", answer: "TRUE", explain: "TRUE: the Phoenician set of twenty-two letters was all consonants, because in their language the vowels could be guessed from context.", evidence: "all consonants, since their language allowed the vowels to be guessed" },
        { n: 10, type: "tfng", prompt: "The Greeks changed the traditional order of the letters they borrowed.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage says the letter order was fixed early, but it never says whether the Greeks kept, changed or ignored that order.", evidence: "the sequence of the letters was already fixed" },
        { n: 11, type: "tfng", prompt: "Alphabetic writing has always run from left to right.", answer: "FALSE", explain: "FALSE: early Greek writing ran right to left like Phoenician, and for a time alternated direction line by line; left-to-right won only gradually.", evidence: "Early Greek writing ran right to left" },
        { n: 12, type: "tfng", prompt: "The Romans took their alphabet from the Etruscans rather than directly from Greece.", answer: "TRUE", explain: "TRUE: the letters reached Rome 'not directly but by way of the Etruscans', whose version of the Greek alphabet the Romans reshaped for Latin.", evidence: "reaching Rome not directly but by way of the Etruscans", vocab: ["by way of", "rather than directly"] },
        { n: 13, type: "tfng", prompt: "More people now write with the Latin alphabet than with any other script.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage calls the alphabet widely shared, but it never compares how many people use the Latin script with users of other scripts.", evidence: "none has been so thoroughly shared" },
      ],
    },
    {
      title: "Passage 2",
      instructions: "You should spend about 20 minutes on Questions 14–26, which are based on Reading Passage 2 below.",
      passageTitle: "The return of the night train",
      passage: `A — At a quarter to seven on a winter morning, a blue train slides into a Paris terminus, and a few hundred passengers who went to sleep in Vienna step out into the rush hour, fourteen hundred kilometres from where they boarded. A decade ago the scene looked like history repeating itself for the last time: across Europe, sleeper services were being cancelled year after year, and the night train seemed destined for the railway museum. Instead, it is multiplying. Austria's national operator, which bought up abandoned routes when its neighbours gave up on them, now runs a growing overnight network across the continent; new connections have opened between Berlin and Brussels, between Stockholm and Hamburg, between Prague and Zurich; and several start-up companies are promising further routes as fast as they can find carriages to run them.

B — To understand the revival, it helps to understand the collapse. The transport economist Lena Hoffmann, who has studied three decades of European timetables, lists the pressures that nearly killed the sleeper. From the 1990s, budget airlines rewrote the arithmetic of travel: no overnight train could compete with a twenty-euro fare, and the trains lost money as their passengers defected. At the same time, operators paid access charges for every kilometre their trains ran at night, staff had to be paid through the small hours, and the specialised sleeping carriages — many built in the 1970s — grew old without being replaced, because no operator losing customers would order new ones. Hoffmann adds a quieter reason: expectations changed, and travellers increasingly disliked sharing a compartment with strangers. By 2016, when two of Europe's largest railways scrapped their sleeper fleets entirely, the obituary seemed already written.

C — What reversed the decline was less a transport argument than an environmental one. The climate researcher Alice Moreau has calculated the comparison that now appears on booking sites: for a typical journey between European capitals, the train produces roughly a tenth of the carbon emissions of the equivalent flight — on some electrified routes far less even than that. Figures of this kind gave the night train a new constituency. A movement that began in Sweden made many travellers uneasy about short-haul aviation, and surveys across the continent found large minorities willing to accept longer journeys for a smaller climate cost. Operators noticed that the first new routes sold out within days, and that the passengers filling them were not nostalgic railway enthusiasts but people in their twenties and thirties.

D — The trains themselves are being rethought to remove the discomforts that helped cause the collapse. The engineer Petr Novak, who leads the design team for one operator's new fleet, points out that the traditional couchette — six near-strangers stacked on shelves in one compartment — was designed for a world with different expectations of privacy. The new carriages replace it with single sleeping capsules for solo travellers, small lockable cabins for couples and families, en-suite washrooms in the better cabins, and key cards and luggage lockers throughout. 'The aim,' Novak says, 'is that a passenger who has never taken a night train should find nothing to apologise for — a small hotel that happens to arrive somewhere.'

E — Whether passengers experience it that way interested the sociologist David Osei, who interviewed several hundred overnight travellers for a study of how people value travel time. His finding is that the night train's real product is not movement but time itself: dead time becomes useful, because the hours spent asleep would have been spent asleep anyway. Passengers repeatedly described the same calculation — the ticket replaces a hotel night, and you fall asleep in one city centre and wake in another, without airports, transfers or a dawn alarm. The complaints were just as consistent: sleep is thinner than at home, and a long delay hurts more at seven in the morning than at seven in the evening. Romance, Osei concludes, has little to do with it; the sleeper survives where the arithmetic of time works.

F — The remaining obstacles are less visible to passengers. The policy analyst Ingrid Salo argues that enthusiasm for night trains currently outruns the industry's ability to supply them: only a handful of factories build sleeping carriages, and their order books are full for years ahead. A train that crosses three countries needs crews certified for each network, locomotives approved for different signalling systems, and tickets sold through booking systems that still cooperate poorly across borders. Some governments have begun to subsidise night routes as climate policy, and the European Union has funded pilot connections, but Salo's conclusion is cautious: the night train has been given a second life by public demand, and whether it keeps it will depend on decisions made in ministries, not in dining cars.`,
      questions: [
        { n: 14, type: "match", group: "minfo", letters: "ABCDEF",
          rubric: "Reading Passage 2 has six paragraphs, A–F. Which paragraph contains the following information? Write the correct letter, A–F. NB You may use any letter more than once.",
          prompt: "a comparison of the environmental damage caused by two forms of transport", answer: "C",
          explain: "Paragraph C gives Moreau's calculation: for a typical journey between capitals, the train produces roughly a tenth of the carbon emissions of the flight.",
          evidence: "roughly a tenth of the carbon emissions of the equivalent flight", vocab: ["carbon emissions", "environmental damage"] },
        { n: 15, type: "match", group: "minfo", prompt: "reasons why running night trains stopped being profitable", answer: "B", explain: "Paragraph B lists the economics of the collapse: cheap air fares, night-time track charges, staff costs and ageing carriages meant the trains lost money.", evidence: "the trains lost money as their passengers defected", vocab: ["lost money", "stopped being profitable"] },
        { n: 16, type: "match", group: "minfo", prompt: "a description of newly designed accommodation for overnight passengers", answer: "D", explain: "Paragraph D describes Novak's new carriages: single sleeping capsules, lockable cabins for couples and families, en-suite washrooms and key cards.", evidence: "single sleeping capsules for solo travellers", vocab: ["cabins", "accommodation"] },
        { n: 17, type: "match", group: "minfo", prompt: "examples of cities that have recently been connected by overnight services", answer: "A", explain: "Paragraph A names the new connections — Berlin and Brussels, Stockholm and Hamburg, Prague and Zurich — opened as the night train multiplied again.", evidence: "new connections have opened between Berlin and Brussels", vocab: ["connections have opened", "recently been connected"] },
        { n: 18, type: "match", group: "minfo", prompt: "practical difficulties involved in operating a train through several countries", answer: "F", explain: "Paragraph F explains the cross-border problems: crews certified for each network, locomotives approved for different signalling systems, and incompatible ticket systems.", evidence: "A train that crosses three countries needs crews certified for each network" },
        { n: 19, type: "gap", group: "sum2", note: "ONE WORD ONLY",
          notes: {
            title: "Summary — Why the night train almost disappeared",
            lines: [
              "From the 1990s, night trains lost their passengers to budget {{19}}, whose fares could be as low as twenty euros. Operators also paid access {{20}} for every kilometre their trains ran at night,",
              "while wages ran through the small hours and the old sleeping carriages were never replaced. Travellers themselves were changing too: more and more of them disliked sharing a compartment with {{21}}.",
              "What saved the sleeper was not railway economics but growing public concern about the {{22}} cost of flying.",
            ],
          },
          answer: "airlines",
          explain: "The summary needs the businesses whose twenty-euro fares beat the sleeper: paragraph B says budget airlines rewrote the arithmetic of travel from the 1990s.",
          evidence: "budget airlines rewrote the arithmetic of travel" },
        { n: 20, type: "gap", group: "sum2", answer: "charges", explain: "After 'access', the gap needs the noun from paragraph B: operators paid access charges for every kilometre their trains ran at night.", evidence: "operators paid access charges for every kilometre" },
        { n: 21, type: "gap", group: "sum2", answer: "strangers", explain: "Hoffmann's quieter reason completes the summary: expectations changed, and travellers increasingly disliked sharing a sleeping compartment with strangers.", evidence: "disliked sharing a compartment with strangers", vocab: ["increasingly disliked", "more and more disliked"] },
        { n: 22, type: "gap", group: "sum2", answer: "climate", explain: "The revival came from environmental concern: surveys found travellers willing to accept longer journeys for a smaller climate cost, so 'climate' fills the gap.", evidence: "willing to accept longer journeys for a smaller climate cost", vocab: ["aviation", "flying"] },
        { n: 23, type: "match", group: "people", boxTitle: "List of People",
          box: [
            "Lena Hoffmann",
            "Alice Moreau",
            "Petr Novak",
            "David Osei",
            "Ingrid Salo",
          ],
          rubric: "Look at the following statements (Questions 23–26) and the list of people below. Match each statement with the correct person, A–E. NB There is one more person than you need.",
          prompt: "Night services could not match the prices offered by low-cost flying.", answer: "A",
          explain: "Hoffmann describes the collapse: once budget airlines offered twenty-euro fares, no overnight train could compete, and passengers defected.",
          evidence: "no overnight train could compete with a twenty-euro fare", vocab: ["compete", "match"] },
        { n: 24, type: "match", group: "people", prompt: "Rail journeys harm the environment far less than equivalent flights.", answer: "B", explain: "Moreau calculated the figure now shown on booking sites: the train produces about a tenth of the carbon of the same journey by air.", evidence: "the train produces roughly a tenth of the carbon", vocab: ["a tenth of the carbon", "far less"] },
        { n: 25, type: "match", group: "people", prompt: "Sleeping on a train turns otherwise wasted hours into something useful.", answer: "D", explain: "Osei's study concludes the night train's real product is time: dead time becomes useful because the sleeping hours would have been slept anyway.", evidence: "dead time becomes useful", vocab: ["dead time", "wasted hours"] },
        { n: 26, type: "match", group: "people", prompt: "Demand for night trains is currently greater than the industry's capacity to provide them.", answer: "E", explain: "Salo argues enthusiasm outruns supply: few factories build sleeping carriages, and their order books are already full for years ahead.", evidence: "outruns the industry's ability to supply them", vocab: ["outruns", "greater than"] },
      ],
    },
    {
      title: "Passage 3",
      instructions: "You should spend about 20 minutes on Questions 27–40, which are based on Reading Passage 3 below.",
      passageTitle: "Thirty-eight witnesses",
      passage: `In March 1964, a young woman named Catherine Genovese was attacked and killed near her home in Queens, New York, in the early hours of the morning. Two weeks later, a front-page newspaper article turned the crime into a parable. Thirty-eight respectable citizens, the report claimed, had watched from their windows for over half an hour while the attack continued, and not one of them had called the police until it was too late. The story provoked national anguish. Commentators diagnosed a sickness of modern city life — anonymity, indifference, the death of community — and the phrase 'urban apathy' entered the language. For decades afterwards, the thirty-eight silent witnesses were cited in sermons, editorials and psychology lectures as proof of what crowded living does to the human conscience.

Two young psychologists reacted differently. Instead of moralising, John Darley and Bibb Latané asked a research question: was it possible that nobody helped precisely because so many people were present? Their laboratory experiments, now classics, tested the idea directly. In one, students sat in separate booths, connected by intercom, when one apparent participant — in fact a recording — seemed to suffer a seizure and call for help. Of those who believed they alone could hear the emergency, the great majority left the booth to fetch help within minutes. Among those who believed four other listeners could also hear it, fewer than a third did. Responsibility, the researchers argued, had been diffused: when help can come from many, each individual feels that it need not come from them, and a genuine emergency can fall between bystanders like a dropped ball between fielders who each expect the other to catch it.

A second experiment revealed another mechanism. Participants filling in forms watched a waiting room slowly fill with smoke from under a door. Alone, most people investigated or raised the alarm promptly. Seated with two calm strangers — confederates instructed to ignore everything — most remained where they were, glancing around, dabbing their eyes, saying nothing, even as the smoke thickened. Darley and Latané called this pluralistic ignorance: in an ambiguous situation, each person looks to others to decide whether anything is wrong, and reads their apparent calm as information. Since everyone is performing composure while privately doubting it, a room full of worried people can reassure itself into inaction. Add the fear of overreacting in public — nobody wants to be the person who called the fire brigade about a faulty kettle — and inaction becomes, for each individual, the safest-looking choice.

The findings replicated reliably, and the 'bystander effect' entered every introductory textbook. The founding story, however, did not survive scrutiny. Decades later, researchers re-examined the court records and press archive of the Genovese case, and found the famous article wrong on almost every important point. Far fewer than thirty-eight people witnessed anything; the attack was mostly out of sight of the windows, and most of those who heard something interpreted it as a quarrel. At least one neighbour shouted at the attacker and drove him off temporarily; there is evidence that more than one person telephoned the police; and a neighbour held the dying woman in her arms while waiting for the ambulance. The parable of urban indifference, in short, was largely a construction of journalism — yet textbooks continued to repeat the tale for decades after the corrections were published.

What, then, happens in real emergencies? For most of the field's history nobody could say, because real emergencies cannot be staged. The spread of security-camera footage changed that. In one large study, researchers analysed recordings of hundreds of aggressive public confrontations captured by street cameras in three countries. In roughly nine incidents out of ten, at least one bystander — usually several — stepped in to calm the aggressor, separate the parties or comfort the victim. More strikingly, the more people were present, the more likely it was that the victim received help from someone, for the simple reason that every additional witness is one more potential helper. The laboratory effect is real — each individual, taken alone, is somewhat less likely to act in a crowd — but at the level of the person on the ground, a busy street is considerably safer than an empty one.

The honest conclusion is not that the bystander effect is a myth, but that it is conditional. It is strongest when a situation is ambiguous, when the people present are strangers to each other, and when the cost of a mistake seems high; it weakens sharply, and often disappears, when danger is unmistakable. The practical lessons are correspondingly simple. First-aid trainers now teach that a caller for help should never address a crowd, but should single out one person — 'you, in the grey jacket, call an ambulance' — because a named individual cannot diffuse responsibility onto anyone else. And the textbooks, one might add, owe their readers a rewritten chapter: the interesting question about that night in 1964 was never why thirty-eight people did nothing, because they did not exist. It is what turns the hesitation of real, worried, watching people into action — and that question, at least, psychology can now begin to answer.`,
      questions: [
        { n: 27, type: "mcq", prompt: "According to the writer, the 1964 newspaper article", options: ["A described the attack completely accurately", "B claimed that dozens of neighbours watched without acting", "C was ignored by the public when it appeared", "D blamed the police for arriving too slowly"], answer: "B", explain: "The article's claim was that thirty-eight citizens watched for half an hour and did nothing; 'dozens... without acting' paraphrases this. Its accuracy is demolished later, ruling out A.", evidence: "not one of them had called the police", vocab: ["thirty-eight", "dozens"] },
        { n: 28, type: "mcq", prompt: "In the seizure experiment, Darley and Latané found that", options: ["A participants refused to believe the emergency was real", "B most people helped whatever the size of the group", "C willingness to act fell as the apparent audience grew", "D students only helped people they already knew"], answer: "C", explain: "Most helped when they thought they were alone, but fewer than a third did when four other listeners could supposedly hear — help fell as the group grew.", evidence: "fewer than a third did", vocab: ["listeners", "audience"] },
        { n: 29, type: "mcq", prompt: "The writer explains 'pluralistic ignorance' as a situation in which", options: ["A people secretly hope someone else will take the blame", "B onlookers fail to notice that anything is happening", "C individuals are too embarrassed to look at one another", "D each person treats the calm of others as proof that nothing is wrong"], answer: "D", explain: "In an ambiguous situation each person reads the apparent calm of the others as information, while performing the same false calm themselves — so the room reassures itself into inaction.", evidence: "reads their apparent calm as information", vocab: ["apparent calm", "calm of others"] },
        { n: 30, type: "mcq", prompt: "The writer cites the security-camera research in order to show that", options: ["A someone intervenes in the great majority of real confrontations", "B cameras discourage members of the public from helping", "C real emergencies confirm the laboratory findings exactly", "D victims are usually helped by police rather than bystanders"], answer: "A", explain: "The footage showed at least one bystander stepping in during roughly nine incidents out of ten — so in most real confrontations somebody does intervene.", evidence: "stepped in to calm the aggressor, separate the parties or comfort the victim", vocab: ["nine incidents out of ten", "great majority"] },
        { n: 31, type: "ynng", prompt: "The famous account of the 1964 murder gave a misleading picture of what happened.", answer: "YES", explain: "YES: re-examination of the court records found the article wrong on almost every important point — fewer witnesses, calls made, and one neighbour who intervened.", evidence: "wrong on almost every important point", vocab: ["wrong", "misleading"] },
        { n: 32, type: "ynng", prompt: "The writer believes laboratory studies of bystander behaviour have no value.", answer: "NO", explain: "NO: the writer states the opposite — the findings replicated reliably and 'the laboratory effect is real'; only its scope and the founding story are questioned.", evidence: "The laboratory effect is real" },
        { n: 33, type: "ynng", prompt: "The writer thinks bystander training should be a compulsory part of school education.", answer: "NOT GIVEN", explain: "NOT GIVEN: first-aid training advice is described, but the writer never expresses any view about schools or about making such training compulsory.", evidence: "First-aid trainers now teach" },
        { n: 34, type: "ynng", prompt: "Textbooks were slow to correct the story of the thirty-eight witnesses.", answer: "YES", explain: "YES: the writer notes that textbooks continued to repeat the tale for decades after the corrections were published, and says they owe readers a rewritten chapter.", evidence: "textbooks continued to repeat the tale for decades", vocab: ["continued to repeat", "slow to correct"] },
        { n: 35, type: "ynng", prompt: "The writer concludes that a victim is less likely to receive help when many people are present.", answer: "NO", explain: "NO: the writer says the opposite of this claim — in the camera studies, the more people present, the more likely the victim was to receive help from someone.", evidence: "the more likely it was that the victim received help" },
        { n: 36, type: "match", group: "ends", boxTitle: "Sentence endings",
          box: [
            "found that several important details in the famous account were untrue.",
            "showed that people help more readily when they know they are being filmed.",
            "often stayed in their seats even as the room filled with smoke.",
            "is real but appears only under particular conditions.",
            "recorded somebody intervening in roughly nine incidents out of ten.",
            "aiming a request for help at one clearly identified person.",
            "proved that people in cities care less about strangers than people in villages.",
          ],
          rubric: "Complete each sentence with the correct ending, A–G, below.",
          prompt: "People waiting with two calm strangers", answer: "C",
          explain: "In the smoke experiment, participants seated with two impassive confederates mostly remained where they were, saying nothing, even as the smoke thickened.",
          evidence: "most remained where they were", vocab: ["remained where they were", "stayed in their seats"] },
        { n: 37, type: "match", group: "ends", prompt: "The later re-examination of the 1964 case", answer: "A", explain: "The archival researchers found far fewer witnesses, an attack mostly out of sight, phone calls made, and a neighbour who intervened — key details of the account were untrue.", evidence: "researchers re-examined the court records" },
        { n: 38, type: "match", group: "ends", prompt: "The analysis of street-camera recordings from three countries", answer: "E", explain: "The study of security-camera footage found at least one bystander stepping in during roughly nine out of ten aggressive public confrontations.", evidence: "In roughly nine incidents out of ten", vocab: ["security-camera", "street-camera"] },
        { n: 39, type: "match", group: "ends", prompt: "First-aid trainers now recommend", answer: "F", explain: "Trainers teach callers to single out one person — 'you, in the grey jacket' — because a named individual cannot pass responsibility to anyone else.", evidence: "should single out one person", vocab: ["single out", "aim at"] },
        { n: 40, type: "match", group: "ends", prompt: "The writer's final position is that the bystander effect", answer: "D", explain: "The conclusion is that the effect is not a myth but conditional: strong in ambiguous, low-stakes situations among strangers, and often absent when danger is clear.", evidence: "not that the bystander effect is a myth, but that it is conditional", vocab: ["conditional", "under particular conditions"] },
      ],
    },
  ],
};
