// Smart LC Pre-IELTS Set 3 — Academic Reading (40 questions, 3 passages).
// Original material authored for Smart LC to the blueprint: P1 factual
// history (completion + TFNG), P2 discursive with lettered paragraphs
// (matching paragraph-information + summary + people matching with one
// extra name), P3 argumentative science (MCQ-4 + YNNG + sentence
// endings). Key quotas: TFNG/YNNG balanced with no runs of three, flat
// letters, unique concrete-noun answers, correct MCQ options paraphrase
// the text while distractors echo its wording.
export const UPSET3_READING = {
  id: "upset3-reading",
  bookId: "upset3",
  title: "Pre-IELTS Set 3 — Reading",
  module: "reading",
  durationMin: 60,
  sections: [
    {
      title: "Passage 1",
      instructions: "You should spend about 20 minutes on Questions 1–13, which are based on Reading Passage 1 below.",
      passageTitle: "Money you could fold",
      passage: `It is easy to forget that money was once a burden in the most literal sense. In imperial China, the standard coin was a small disc of bronze with a square hole at its centre, and coins were carried strung together on cords, a thousand at a time. A single string could weigh several kilograms, and any serious purchase required baskets or carts of them. In the province of Sichuan the situation was worse still, because coins there were made of iron, a metal so cheap that it took a sackful to pay for a length of silk. Merchants who travelled between cities faced a simple, exhausting problem: the value of their goods was easy to move, but the money to pay for them was not.

The solution appeared where the problem was sharpest. During the Tang dynasty, traders and officials had already experimented with "flying money" — paper orders that allowed a merchant to deposit coins in one city and collect their value in another. By the tenth century, merchants in the Sichuan capital, Chengdu, had taken the idea further: a trader could leave his heavy coins with a trusted commercial house and travel instead with a paper receipt, which the house promised to exchange for coins on demand. Before long the receipts themselves began to change hands in the markets, standing in for the metal locked away in the issuers' vaults. In 1024 the government stepped in, took the system over, and began printing notes of its own — the first state paper currency in the world.

Word of this astonishing practice reached Europe through the Venetian traveller Marco Polo, who described it at length in the account of his years in China. The notes, he explained, were made from the bark of mulberry trees, pounded flat, cut to size and stamped with the emperor's bright red seal; anyone who forged them faced the death penalty, and anyone who refused to accept them faced punishment almost as severe. Many of his readers simply refused to believe him. Money that could be created with a stamp, from the inner skin of a tree, sounded less like commerce than like conjuring.

Yet the Chinese had already discovered paper money's central danger: it is far easier to print a note than to mine a coin. Successive governments, pressed by wars and shortfalls, issued more and more paper against the same reserves, and prices climbed until the notes in circulation were worth little more than the mulberry sheets they were printed on. By the middle of the fifteenth century the experiment had been abandoned, and China returned to metal for four hundred years.

Europe came to the banknote independently, and by an equally practical route. Seventeenth-century Sweden had tied its currency to its vast reserves of copper, with predictable results: the largest denomination was a rectangular plate of copper weighing nearly twenty kilograms, and moving any serious sum of money required a horse and cart. In 1661 Johan Palmstruch, the founder of the Stockholms Banco, hit upon the obvious remedy — printed notes that could be exchanged at the bank for the metal itself. The notes were an immediate success; encouraged, Palmstruch's bank lent freely and printed more of them than its vaults could honour, and within a few years the bank had collapsed and its founder had been sentenced to prison. The idea, however, outlived its inventor's disgrace. When the Bank of England was established in 1694, it too issued notes against deposits — elegant documents that were partly printed and partly completed by hand, each one bearing the signature of the bank's cashier.

From the beginning, the banknote's greatest enemy was the forger, and the history of note design is largely the history of that contest. Banks commissioned ever more intricate engraving, on the theory that fine lines defeat crude copying, and paper-makers contributed the watermark — a design formed within the thickness of the paper itself, invisible in a wallet but unmistakable when a note is held up to the light. Later came special inks, embedded metal threads and printing too small for the eye, and in 1988 Australia abandoned paper altogether, issuing the world's first polymer banknotes, printed on a thin plastic film that resists both tearing and imitation.

Strip away the engraving and the security thread, and what remains is a promise. A banknote has almost no value in itself; it works only because a whole society agrees to treat it as valuable, and that agreement, once broken — as Chinese emperors and Swedish bankers both discovered — is remarkably hard to repair. It is worth remembering, as coins and notes give way to cards and phones, that the paper in our pockets was itself once the disruptive newcomer: a seven-hundred-year experiment in trust which may yet prove to have been only an episode in the much longer history of money.`,
      questions: [
        { n: 1, type: "gap", prompt: "In Sichuan, coins were made of ______, a particularly cheap metal.", note: "ONE WORD ONLY", answer: "iron", explain: "The first paragraph singles out Sichuan: its coins were made of iron, a metal so cheap that huge quantities were needed for any purchase.", evidence: "coins there were made of iron" },
        { n: 2, type: "gap", prompt: "Instead of carrying coins, a merchant could travel with a paper ______.", note: "ONE WORD ONLY", answer: "receipt", explain: "A trader left his coins with a commercial house and travelled with a paper receipt, which the house promised to exchange for coins on demand.", evidence: "travel instead with a paper receipt", vocab: ["leave his heavy coins", "instead of carrying coins"] },
        { n: 3, type: "gap", prompt: "Chinese banknotes were produced from the ______ of a type of tree.", note: "ONE WORD ONLY", answer: "bark", explain: "Marco Polo explained that the notes were made from the bark of mulberry trees, beaten flat and stamped with the emperor's seal.", evidence: "made from the bark of mulberry trees" },
        { n: 4, type: "gap", prompt: "Sweden's largest unit of money was a heavy plate of ______.", note: "ONE WORD ONLY", answer: "copper", explain: "Sweden tied its currency to copper, so its biggest denomination was a rectangular copper plate weighing almost twenty kilograms.", evidence: "a rectangular plate of copper weighing nearly twenty kilograms", vocab: ["largest denomination", "largest unit of money"] },
        { n: 5, type: "gap", prompt: "Early Bank of England notes carried the signature of the bank's ______.", note: "ONE WORD ONLY", answer: "cashier", explain: "The Bank of England's early notes were partly handwritten, and each one was signed by the bank's cashier before it was issued.", evidence: "bearing the signature of the bank's cashier" },
        { n: 6, type: "gap", prompt: "The ______ is a design inside the paper that can be seen against the light.", note: "ONE WORD ONLY", answer: "watermark", explain: "Paper-makers contributed the watermark, a design formed within the paper itself which appears only when a note is held up to the light.", evidence: "unmistakable when a note is held up to the light", vocab: ["up to the light", "against the light"] },
        { n: 7, type: "tfng", prompt: "Buying expensive goods with iron coins required a very large quantity of them.", answer: "TRUE", explain: "TRUE: iron was so cheap that it took a whole sackful of coins to pay for a single length of silk — a very large quantity indeed.", evidence: "it took a sackful to pay for a length of silk", vocab: ["a sackful", "a very large quantity"] },
        { n: 8, type: "tfng", prompt: "Marco Polo's description of Chinese paper money was widely accepted by his readers.", answer: "FALSE", explain: "FALSE: the passage says many readers simply refused to believe him, finding money made from tree bark closer to magic than to commerce.", evidence: "Many of his readers simply refused to believe him", vocab: ["refused to believe", "accepted"] },
        { n: 9, type: "tfng", prompt: "Marco Polo brought examples of Chinese banknotes back to Venice.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage says he described the notes in his written account, but nothing about whether he carried any physical examples home.", evidence: "described it at length in the account of his years in China" },
        { n: 10, type: "tfng", prompt: "China stopped using paper money after its value fell sharply.", answer: "TRUE", explain: "TRUE: over-printing made prices climb until notes were nearly worthless, and by the mid-fifteenth century the experiment had been abandoned.", evidence: "the experiment had been abandoned", vocab: ["prices climbed", "its value fell"] },
        { n: 11, type: "tfng", prompt: "The Stockholms Banco printed only as many notes as it could exchange for metal.", answer: "FALSE", explain: "FALSE: the bank did the opposite — it lent freely and printed more notes than its vaults could honour, which is why it collapsed.", evidence: "printed more of them than its vaults could honour", vocab: ["could honour", "could exchange for metal"] },
        { n: 12, type: "tfng", prompt: "Producing an early Bank of England note involved some work done by hand.", answer: "TRUE", explain: "TRUE: 'work done by hand' paraphrases the passage — each note was only partly printed and partly completed by hand before being signed.", evidence: "partly printed and partly completed by hand", vocab: ["completed by hand", "done by hand"] },
        { n: 13, type: "tfng", prompt: "Australia's polymer notes were cheaper to produce than paper ones.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage says the plastic notes resist tearing and imitation, but it never compares their production costs with paper.", evidence: "printed on a thin plastic film that resists both tearing and imitation" },
      ],
    },
    {
      title: "Passage 2",
      instructions: "You should spend about 20 minutes on Questions 14–26, which are based on Reading Passage 2 below.",
      passageTitle: "The day the traffic stopped",
      passage: `A — On a Sunday morning in November 1973, the motorways of the Netherlands fell silent. The government, faced with an oil embargo, had banned driving on Sundays, and the results were photographed with delight: families picnicking on the tarmac of major roads, children learning to ride bicycles on empty six-lane carriageways, horses trotting past deserted service stations, and, in more than one town, neighbours carrying armchairs onto the warm asphalt to sit and talk in the sun. The historian Ruth Calder, who has collected interviews with people who lived through that winter, finds that the car-free Sundays are remembered "with a fondness that borders on the mythical" — not as hardship but as holiday. The restrictions ended when the oil returned, yet they planted an idea that has never quite gone away: that a city without cars, even briefly, is a different and perhaps better place.

B — The idea found its permanent home not in Europe but in Colombia. Since 1974, Bogotá has closed a network of streets to motor traffic every Sunday and public holiday, an event known as the ciclovía. Around 120 kilometres of roads are given over to people on bicycles, as well as to runners, skaters, dance classes and street vendors, and on a typical Sunday well over a million residents take part. What began as a small protest by cycling enthusiasts has become a civic institution, and the model has since been copied by more than four hundred cities around the world. Paris now empties its centre of cars for one day each autumn, while Jakarta, Mexico City and hundreds of smaller places run weekly versions of their own.

C — What actually changes when the engines stop? The air scientist Ingrid Halvorsen has spent a decade parking her instrument van beside major roads on ordinary days and car-free days alike, and her measurements are strikingly consistent. Along one central avenue she found that levels of nitrogen dioxide, the lung-irritating gas produced above all by diesel engines, fell by roughly forty per cent within a few hours of the roads closing. Noise tells the same story: her sound meters typically record a drop of about half, "which is the difference", she notes, "between shouting to be heard and hearing birdsong in the city centre". The effects vanish when the traffic returns, but for one day the instruments describe a different city.

D — Shopkeepers are the most reliable opponents of such schemes, convinced that customers who cannot park will not come. The economist Samuel Boateng has tested that conviction by pairing surveys of traders with surveys of the people actually walking through their doors, and the two pictures rarely match. In one district, merchants estimated that half of their customers arrived by car; the true figure was below a fifth. His spending data complete the argument: people who arrive on foot or by bicycle spend less on each visit, but they come more often, and over a month they leave more money in local tills than drivers do. The fear of ruin, Boateng concludes, rests on a mistaken picture of who customers really are and how they travel.

E — None of this silences the critics, whose sharpest point concerns not the day itself but the day after. On Monday morning the traffic returns, the nitrogen dioxide climbs back to its usual level, and the city is exactly as it was — which leads some to dismiss the whole exercise as theatre. There is also the problem of displacement: on the day itself, some journeys do not disappear but shift to the ring roads at the edge of the closed zone, where congestion briefly worsens. The transport planner Andrés Vela accepts both objections and turns them into a test. "A car-free day that is followed by nothing is a festival, not a policy," he argues; in his view the events earn their place only when they are used to trial bus corridors, cycle lanes and pedestrian squares that later become permanent.

F — Yet the strongest defence of the car-free day may lie in what it does to imagination rather than to air. The sociologist Chiara Lombardi, who interviews residents before and after such events, finds that a single day is often enough to shift people's sense of what their streets are for: support for permanent traffic restrictions rises measurably among those who have actually walked down the middle of a road they had only ever driven along. She points to the cities that have gone furthest — Pontevedra in Spain, which has removed cars from its centre almost entirely, and Oslo, which stripped out most of its central parking spaces — and notes that in both cases the deciding argument was not a statistic but an experience. A car-free day, on this reading, is not a holiday from the real city. It is a rehearsal for a future one.`,
      questions: [
        { n: 14, type: "match", group: "minfo", letters: "ABCDEF",
          rubric: "Reading Passage 2 has six paragraphs, A–F. Which paragraph contains the following information? Write the correct letter, A–F. NB You may use any letter more than once.",
          prompt: "examples of unusual activities taking place on roads normally full of vehicles", answer: "A",
          explain: "Paragraph A describes families picnicking on the tarmac, children cycling on empty carriageways and horses trotting past service stations during the 1973 Sundays.",
          evidence: "children learning to ride bicycles on empty six-lane carriageways" },
        { n: 15, type: "match", group: "minfo", prompt: "figures showing that shopkeepers misjudge how their customers reach them", answer: "D", explain: "Paragraph D has the figures: merchants estimated half their customers came by car, when the true share was below a fifth.", evidence: "the true figure was below a fifth", vocab: ["arrived by car", "reach them"] },
        { n: 16, type: "match", group: "minfo", prompt: "a claim that one-day events achieve nothing unless lasting changes follow", answer: "E", explain: "Paragraph E carries Vela's claim: a car-free day followed by nothing is a festival, not a policy — it must lead to permanent schemes.", evidence: "is a festival, not a policy", vocab: ["become permanent", "lasting changes"] },
        { n: 17, type: "match", group: "minfo", prompt: "measurements of air quality made during a car-free day", answer: "C", explain: "Paragraph C reports Halvorsen's instrument-van readings: nitrogen dioxide beside a central avenue fell by roughly forty per cent once the roads closed.", evidence: "fell by roughly forty per cent", vocab: ["nitrogen dioxide", "air quality"] },
        { n: 18, type: "match", group: "minfo", prompt: "examples of cities that have permanently restricted cars", answer: "F", explain: "Paragraph F names Pontevedra, which removed cars from its centre almost entirely, and Oslo, which stripped out most central parking spaces.", evidence: "removed cars from its centre almost entirely" },
        { n: 19, type: "gap", group: "sum2", note: "ONE WORD ONLY",
          notes: {
            title: "Summary — Bogotá's weekly experiment",
            lines: [
              "Since 1974, Bogotá has closed a long network of streets to motor traffic every Sunday. Around 120 kilometres of roads are handed over to people on {{19}}, as well as to runners, skaters and dancers,",
              "and the event has now been imitated by more than four hundred {{20}} around the world.",
              "During such closures, scientists have measured sharp falls in {{21}} dioxide beside major roads, while levels of {{22}} typically drop by about half — enough for birdsong to be heard in the centre.",
            ],
          },
          answer: "bicycles",
          explain: "After 'people on', the summary needs the plural noun from paragraph B: the closed roads are given over to people on bicycles.",
          evidence: "given over to people on bicycles", vocab: ["given over to", "handed over to"] },
        { n: 20, type: "gap", group: "sum2", answer: "cities", explain: "'Imitated' in the summary paraphrases 'copied' in the passage: the ciclovía model has been copied by more than four hundred cities worldwide.", evidence: "copied by more than four hundred cities", vocab: ["copied", "imitated"] },
        { n: 21, type: "gap", group: "sum2", answer: "nitrogen", explain: "The gas measured by Halvorsen is nitrogen dioxide, produced above all by diesel engines; only 'nitrogen' fits before 'dioxide' in the summary.", evidence: "levels of nitrogen dioxide" },
        { n: 22, type: "gap", group: "sum2", answer: "noise", explain: "The second measurement is sound: her meters record noise dropping by about half, the difference between shouting and hearing birdsong.", evidence: "her sound meters typically record a drop of about half", vocab: ["sound meters", "levels of noise"] },
        { n: 23, type: "match", group: "people", boxTitle: "List of People",
          box: [
            "Ruth Calder",
            "Ingrid Halvorsen",
            "Samuel Boateng",
            "Andrés Vela",
            "Chiara Lombardi",
          ],
          rubric: "Look at the following statements (Questions 23–26) and the list of people below. Match each statement with the correct person, A–E. NB There is one more person than you need.",
          prompt: "Fears that businesses will suffer rest on a false idea of how customers travel.", answer: "C",
          explain: "Boateng concludes exactly this: the fear of ruin rests on a mistaken picture of who customers are and how they actually travel.",
          evidence: "The fear of ruin, Boateng concludes, rests on a mistaken picture", vocab: ["mistaken picture", "false idea"] },
        { n: 24, type: "match", group: "people", prompt: "Temporary closures are worthless unless permanent measures grow out of them.", answer: "D", explain: "Vela argues that a car-free day followed by nothing is merely a festival: the events count only when trialled changes later become permanent.", evidence: "they are used to trial bus corridors" },
        { n: 25, type: "match", group: "people", prompt: "Car-free days change what residents believe their streets could be like.", answer: "E", explain: "Lombardi's interviews show a single day shifting people's sense of what streets are for, with support for permanent restrictions rising afterwards.", evidence: "enough to shift people's sense of what their streets are for", vocab: ["sense of", "believe"] },
        { n: 26, type: "match", group: "people", prompt: "Pollution beside main roads falls measurably when traffic is kept out.", answer: "B", explain: "Halvorsen's van recorded nitrogen dioxide falling by around forty per cent within hours of closure — a measured fall, matching the statement.", evidence: "within a few hours of the roads closing" },
      ],
    },
    {
      title: "Passage 3",
      instructions: "You should spend about 20 minutes on Questions 27–40, which are based on Reading Passage 3 below.",
      passageTitle: "The anatomy of stage fright",
      passage: `Ask people what frightens them, and public speaking appears with astonishing regularity near the top of the list: surveys of common fears repeatedly place it above heights, flying and even spiders. The dread of performing before others — stage fright, or performance anxiety in the clinical literature — is close to universal, and it is no respecter of talent. Beginners suffer, as everyone expects; less predictably, decades of experience provide no immunity, and some celebrated musicians and actors have struggled with severe stage fright across entire careers, long after their competence had ceased to be in any doubt. Whatever stage fright is, it is not simply a shortage of skill or practice, and understanding it properly means looking first at the body, then at the mind.

The bodily half of the story is quickly told, because it is the same story as every other acute fear. Confronted with an audience, the brain's alarm system fires and adrenaline pours into the bloodstream. The heart pounds, breathing quickens, the palms sweat and the mouth goes dry; blood is diverted towards the large muscles, which is why the hands and knees tremble and the face may turn pale. This is the ancient fight-or-flight response, magnificently engineered over millions of years for escaping predators and surviving sudden danger. The trouble is the mismatch between the machinery and the occasion. The body prepares to fight or flee an audience it cannot fight and should not flee, and the performer is left standing still, flooded with fuel that has nowhere to go.

It would be wrong, though, to treat arousal purely as an enemy. In 1908 the psychologists Robert Yerkes and John Dodson described a relationship that has been confirmed, with refinements, ever since: arousal improves performance — but only up to a point, beyond which more of it makes performance worse. The resulting curve is shaped like an upside-down U. A moderately activated performer is sharper than a relaxed one: attention narrows, reactions speed up, energy rises. The location of the peak, however, depends on the task. Simple or physical activities tolerate very high arousal, while precise manual skills are the first to suffer as it climbs — a trembling hand will ruin a violin passage long before it ruins a lecture. The performer's problem, in this light, is not arousal itself but overshoot.

The mind then makes its own contribution, and a peculiarly cruel one. Anxious performers become intensely self-focused, monitoring their own heartbeat and shaking hands, and they fall victim to what psychologists call the illusion of transparency: the conviction that these inner storms are plainly visible to everyone watching. Experiments find otherwise, with remarkable consistency. Audiences asked to assess nervous speakers judged them to be calmer than the speakers expected, often by a wide margin; the pounding heart is simply not on display. Better still, the illusion loses much of its power once it is named. Speakers who were told about the effect before performing — who knew that their anxiety would be largely invisible — were rated as more composed and more persuasive than those left to their imaginations.

If the fear cannot be hidden, can it be re-described? The standard advice, endlessly repeated, is to calm down, and it turns out to be poor advice: full arousal cannot be switched off on command, and struggling to do so is one more task for an overloaded mind. A more promising route exploits an odd fact: anxiety and excitement are physically almost identical — the same racing heart, the same alertness — and differ mainly in interpretation. In studies of singing, public speaking and mathematics, participants instructed to say "I am excited" outperformed those instructed to relax: simply relabelling the feeling improved performance, at no cost and with no training. Suppression, by contrast, fails reliably. Performers who concentrated on hiding their symptoms did worst of all, because concealment consumes attention the performance itself needs.

There is also a chemical answer, and in one profession it is quietly widespread. Beta blockers, drugs developed for heart conditions, blunt adrenaline's effects on the body — steadier hands, a slower heartbeat — without dulling the mind, and surveys suggest a substantial minority of orchestral musicians have used them before auditions or concerts. Their limits, however, are instructive: the drugs control the symptoms while leaving the performer's thinking untouched, so the dread itself returns for every performance, and some musicians report that a chemically becalmed performance loses a little of its fire. A pill can quiet the body's alarm; it cannot teach the mind a different relationship with the stage.

That different relationship is, in the end, the real cure. Stage fright is not a malfunction to be engineered away but a miscalibration of a useful system: the surge that makes the heart pound also sharpens attention and raises energy, and seasoned performers describe learning to re-read the same sensations as readiness rather than danger. The task is not to switch the response off but to put its energy to use. The performer who walks on stage with a racing heart is not broken. They are, in the oldest sense of the word, roused — and the difference between panic and presence lies less in the body's chemistry than in the story the performer tells about it.`,
      questions: [
        { n: 27, type: "mcq", prompt: "In the first paragraph, what does the writer say about stage fright?", options: ["A It affects mainly those who are new to performing", "B Surveys exaggerate how widespread it really is", "C It can persist despite long professional experience", "D It is most severe among musicians and actors"], answer: "C", explain: "Experience gives no immunity: some celebrated performers struggled across entire careers. Options A and D echo the passage's words while distorting its point.", evidence: "decades of experience provide no immunity", vocab: ["no immunity", "can persist"] },
        { n: 28, type: "mcq", prompt: "According to the second paragraph, the physical symptoms of stage fright occur because", options: ["A the body reacts to an audience as though to physical danger", "B the brain's alarm system operates too slowly", "C performers misinterpret their own breathing", "D blood is prevented from reaching the large muscles"], answer: "A", explain: "The fight-or-flight system evolved for predators, so it treats an audience like a threat. Option D reverses the passage: blood is diverted towards the muscles.", evidence: "prepares to fight or flee an audience it cannot fight", vocab: ["fight-or-flight", "physical danger"] },
        { n: 29, type: "mcq", prompt: "What point is made about arousal in the third paragraph?", options: ["A It damages performance at any level", "B Precise manual skills are the last to be affected", "C The 1908 findings have since been rejected", "D It helps performance up to a certain level"], answer: "D", explain: "The inverted-U curve means moderate arousal sharpens performance and only excess harms it. Option B reverses the text: precise skills suffer first.", evidence: "arousal improves performance — but only up to a point", vocab: ["up to a point", "a certain level"] },
        { n: 30, type: "mcq", prompt: "The writer cites the research on excitement in order to show that", options: ["A trying to relax is the most effective strategy", "B the label given to arousal can change its effect", "C excitement produces a different physical state from fear", "D relabelling works only for experienced performers"], answer: "B", explain: "Saying 'I am excited' beat trying to relax, because the two states differ mainly in interpretation. Option C contradicts 'physically almost identical'.", evidence: "simply relabelling the feeling improved performance", vocab: ["relabelling", "the label given"] },
        { n: 31, type: "ynng", prompt: "The body's reaction to an audience is badly suited to the situation.", answer: "YES", explain: "YES: the writer calls it a mismatch between machinery and occasion — the body prepares for fighting or fleeing, neither of which is possible.", evidence: "the mismatch between the machinery and the occasion", vocab: ["mismatch", "badly suited"] },
        { n: 32, type: "ynng", prompt: "Concealing the signs of nervousness is an effective approach.", answer: "NO", explain: "NO: performers who concentrated on hiding their symptoms did worst of all, because concealment uses up attention the performance needs.", evidence: "concealment consumes attention the performance itself needs", vocab: ["hiding their symptoms", "concealing the signs"] },
        { n: 33, type: "ynng", prompt: "Stage fright has become more common in recent years.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage says the fear is widespread and near universal, but it never compares present levels with the past.", evidence: "surveys of common fears repeatedly place it above heights" },
        { n: 34, type: "ynng", prompt: "Medication can reduce the physical signs of performance anxiety.", answer: "YES", explain: "YES: beta blockers blunt adrenaline's bodily effects, giving steadier hands and a slower heartbeat, though they leave the performer's thinking unchanged.", evidence: "steadier hands, a slower heartbeat", vocab: ["blunt", "reduce"] },
        { n: 35, type: "ynng", prompt: "The aim should be to remove the fear response completely.", answer: "NO", explain: "NO: the writer's conclusion is the opposite — the task is not to switch the response off but to use its energy well.", evidence: "not to switch the response off but to put its energy to use" },
        { n: 36, type: "match", group: "ends", boxTitle: "Sentence endings",
          box: [
            "judged speakers to be calmer than the speakers expected.",
            "proves that experience gradually eliminates anxiety.",
            "believe their nervousness is far more visible than it really is.",
            "found that audiences enjoy watching nervous performers.",
            "control their symptoms without changing how they think.",
            "performed better than those who tried to calm down.",
            "can be put to use rather than fought.",
          ],
          rubric: "Complete each sentence with the correct ending, A–G, below.",
          prompt: "Performers under the illusion of transparency", answer: "C",
          explain: "The illusion of transparency is the conviction that inner storms are plainly visible; in reality the pounding heart is not on display.",
          evidence: "the conviction that these inner storms are plainly visible", vocab: ["inner storms", "nervousness"] },
        { n: 37, type: "match", group: "ends", prompt: "In experiments, members of the audience", answer: "A", explain: "Audiences asked to assess nervous speakers rated them as calmer than the speakers themselves expected, often by a wide margin.", evidence: "judged them to be calmer than the speakers expected" },
        { n: 38, type: "match", group: "ends", prompt: "Participants who described their nerves as excitement", answer: "F", explain: "In singing, speaking and mathematics studies, people told to say 'I am excited' outperformed those told to relax — calming down was the weaker strategy.", evidence: "outperformed those instructed to relax", vocab: ["outperformed", "performed better than"] },
        { n: 39, type: "match", group: "ends", prompt: "Musicians who use beta blockers", answer: "E", explain: "The drugs steady the body but leave the performer's thinking untouched, so the dread itself returns before every performance.", evidence: "control the symptoms while leaving the performer's thinking untouched" },
        { n: 40, type: "match", group: "ends", prompt: "The writer argues that the energy of stage fright", answer: "G", explain: "The conclusion reframes the surge as a resource: rather than fighting the response, performers should direct its energy into the performance.", evidence: "put its energy to use" },
      ],
    },
  ],
};
