// Smart LC Pre-IELTS Set 4 — Academic Reading (40 questions, 3 passages).
// Original material authored for Smart LC to the blueprint: P1 factual
// history (completion + TFNG), P2 discursive with lettered paragraphs
// (matching paragraph-information + summary + people matching with one
// extra name), P3 argumentative psychology (MCQ-4 + YNNG + summary from
// a wordlist box). Key quotas: TFNG/YNNG balanced with no runs of three,
// flat letters, unique concrete-noun answers, correct MCQ options
// paraphrase the text while distractors echo its wording.
export const UPSET4_READING = {
  id: "upset4-reading",
  bookId: "upset4",
  title: "Pre-IELTS Set 4 — Reading",
  module: "reading",
  durationMin: 60,
  sections: [
    {
      title: "Passage 1",
      instructions: "You should spend about 20 minutes on Questions 1–13, which are based on Reading Passage 1 below.",
      passageTitle: "The invention of cold",
      passage: `For most of human history, keeping food fresh meant borrowing whatever cold nature happened to offer. Meat and fish were salted, smoked or dried; milk was turned into cheese or butter within hours of leaving the cow; and vegetables were pickled in vinegar or buried in sand-filled cellars. Where winters were dependable, there was ice. Great estates maintained ice houses — brick-lined pits, half underground, packed each January with blocks cut from frozen lakes and insulated with thick layers of straw. Managed carefully, such a store could last deep into August, chilling wine and setting elaborate desserts. But ice houses were costly to build and to fill, and they belonged almost entirely to the properties of the rich. For ordinary families, the only refrigeration was a cool cellar, a bucket lowered into the well, or a north-facing windowsill, and a week of warm weather turned every larder into a race against decay.

The scientific principle behind artificial cold was demonstrated long before anyone imagined a use for it. In 1748, the Scottish physician William Cullen showed an audience in Glasgow that when ether, a light and fast-evaporating liquid, was made to evaporate under a partial vacuum, it absorbed so much heat from its surroundings that a small quantity of ice formed inside the apparatus. The effect is familiar to any swimmer who shivers in a warm breeze: a liquid, as it evaporates, drinks heat from whatever it touches. Cullen's demonstration was admired as an elegant curiosity, and then, for the better part of a century, nothing whatever was done with it.

The man who turned the curiosity into a machine was Jacob Perkins, an American inventor who had settled in London. In 1834 he patented an apparatus in which ether travelled continuously around a closed cycle: evaporating in one chamber, where it soaked up heat and chilled the surrounding brine, then being squeezed by a pump and condensed back into liquid in a second chamber, where it released that heat to the outside air, ready to evaporate all over again. This is, in essence, the same loop that hums at the back of every domestic refrigerator today. A working model was built, and it made ice; the patent, however, attracted almost no commercial attention, and Perkins, by then an elderly man, took the idea no further.

It was money, not wonder, that finally drove the technology forward — and much of the pressure came from hot countries. James Harrison, a Scottish-born printer who had emigrated to Australia, noticed how sharply ether chilled the metal surfaces he cleaned with it, and by the late 1850s he had built full-scale ice-making machines; his first paying customers were breweries, whose beer spoiled quickly in the Australian summer. In France, Ferdinand Carré designed a machine that used ammonia rather than ether — a far more efficient refrigerant, and one still found in industrial plants today. The greatest prize, though, was meat. In 1876 the steamship Frigorifique carried chilled beef from Argentina to France; the voyage proved that the idea could work, although part of the cargo spoiled on the way. Six years later the Dunedin sailed from New Zealand to London carrying thousands of frozen lamb carcasses, and landed them in near-perfect condition after ninety-eight days at sea. A world trade in frozen food had begun, and the grasslands of distant continents could now feed the crowded cities of Europe.

The refrigerator entered the home far more slowly. Early domestic machines, on sale from the 1910s, were expensive, unreliable and genuinely dangerous: they circulated gases such as ammonia, sulphur dioxide and methyl chloride, and a leaking pipe in a closed kitchen could be — and in several recorded cases was — fatal. The answer arrived in 1930, when the American chemist Thomas Midgley unveiled a new synthetic refrigerant, later sold under the name Freon. To advertise its safety, Midgley theatrically inhaled a lungful of the gas and used it to blow out a candle: it was neither poisonous nor flammable. Freon transformed the industry. Refrigerators became compact, quiet and trustworthy; by the 1950s they were standard equipment in American kitchens, and much of the rest of the world followed within a generation.

The triumph carried a hidden cost. In the 1970s and 1980s, atmospheric scientists established that the chlorine compounds in Freon and its chemical relatives, drifting slowly upwards for decades, were destroying the ozone layer that shields the Earth from ultraviolet radiation. In 1987 the world's governments agreed, under the Montreal Protocol, to phase the chemicals out, and refrigeration engineers were sent back to their drawing boards to find gentler gases. It is a neat irony: the compound celebrated for making the refrigerator safe turned out to be quietly dangerous on a planetary scale. Yet the machine itself has never mattered more. An unbroken cold chain of refrigerated ships, lorries, warehouses and shop cabinets now moves fresh food and temperature-sensitive vaccines across the globe, and the technology conceived in a Glasgow lecture theatre decides, every single day, what much of humanity is able to eat.`,
      questions: [
        { n: 1, type: "gap", prompt: "Cullen produced ice by evaporating ether under a partial ______.", note: "ONE WORD ONLY", answer: "vacuum", explain: "The first scientific demonstration is in paragraph two: Cullen made ether evaporate under a partial vacuum, and the process absorbed enough heat to form ice.", evidence: "made to evaporate under a partial vacuum" },
        { n: 2, type: "gap", prompt: "In Perkins's machine, ether moved constantly around a closed ______.", note: "ONE WORD ONLY", answer: "cycle", explain: "'Moved constantly' in the question paraphrases 'travelled continuously' in the passage: the ether went round a closed cycle of evaporation and condensation.", evidence: "ether travelled continuously around a closed cycle", vocab: ["travelled continuously", "moved constantly"] },
        { n: 3, type: "gap", prompt: "Harrison's earliest customers were ______ trying to protect their product from the heat.", note: "ONE WORD ONLY", answer: "breweries", explain: "Harrison built ice-making machines in Australia, and the passage names his first paying customers directly: breweries, whose beer spoiled in summer.", evidence: "his first paying customers were breweries", vocab: ["spoiled quickly", "protect from the heat"] },
        { n: 4, type: "gap", prompt: "Carré's design replaced ether with ______, which worked far more efficiently.", note: "ONE WORD ONLY", answer: "ammonia", explain: "'Replaced' in the question paraphrases 'used... rather than' in the passage: Carré's machine used ammonia instead of ether, a more efficient refrigerant.", evidence: "used ammonia rather than ether", vocab: ["rather than", "replaced"] },
        { n: 5, type: "gap", prompt: "In 1882 the Dunedin delivered frozen ______ from New Zealand in excellent condition.", note: "ONE WORD ONLY", answer: "lamb", explain: "Six years after the Frigorifique's 1876 voyage — so in 1882 — the Dunedin carried thousands of frozen lamb carcasses and landed them nearly perfect.", evidence: "carrying thousands of frozen lamb carcasses", vocab: ["near-perfect condition", "excellent condition"] },
        { n: 6, type: "gap", prompt: "Escapes of gas from early domestic refrigerators were sometimes ______.", note: "ONE WORD ONLY", answer: "fatal", explain: "'Escapes of gas' paraphrases 'a leaking pipe': the early gases were so dangerous that a leak in a closed kitchen was, in recorded cases, fatal.", evidence: "in several recorded cases was — fatal", vocab: ["a leaking pipe", "escapes of gas"] },
        { n: 7, type: "gap", prompt: "Freon's chlorine compounds were found to be damaging the ozone ______.", note: "ONE WORD ONLY", answer: "layer", explain: "The final paragraph explains the hidden cost: the chlorine compounds drifted upwards and were destroying the ozone layer that blocks ultraviolet radiation.", evidence: "destroying the ozone layer that shields the Earth", vocab: ["destroying", "damaging"] },
        { n: 8, type: "tfng", prompt: "Ice houses were mainly found on the land of wealthy families.", answer: "TRUE", explain: "TRUE: the passage says ice houses were costly and belonged almost entirely to the properties of the rich — 'wealthy families' paraphrases 'the rich'.", evidence: "belonged almost entirely to the properties of the rich", vocab: ["the rich", "wealthy families"] },
        { n: 9, type: "tfng", prompt: "Cullen's experiment was quickly developed into useful machines.", answer: "FALSE", explain: "FALSE: the demonstration was admired only as a curiosity, and for the better part of a century nothing whatever was done with it — the opposite of quickly.", evidence: "for the better part of a century, nothing whatever was done with it" },
        { n: 10, type: "tfng", prompt: "Perkins moved to London in order to sell his refrigeration machine.", answer: "NOT GIVEN", explain: "NOT GIVEN: we learn Perkins was an American inventor who had settled in London, but the passage never explains why he moved there.", evidence: "an American inventor who had settled in London" },
        { n: 11, type: "tfng", prompt: "The Frigorifique's cargo arrived in France without any losses.", answer: "FALSE", explain: "FALSE: the 1876 voyage proved the idea could work, but the passage states plainly that part of the cargo spoiled on the way — so there were losses.", evidence: "part of the cargo spoiled on the way", vocab: ["spoiled", "losses"] },
        { n: 12, type: "tfng", prompt: "Freon was presented as less dangerous than the gases used before it.", answer: "TRUE", explain: "TRUE: Midgley advertised its safety by inhaling it and blowing out a candle, showing it was neither poisonous nor flammable, unlike the earlier gases.", evidence: "it was neither poisonous nor flammable", vocab: ["advertise its safety", "less dangerous"] },
        { n: 13, type: "tfng", prompt: "Engineers had to look for replacement gases after an international agreement.", answer: "TRUE", explain: "TRUE: after governments agreed under the Montreal Protocol to phase the chemicals out, engineers were sent back to their drawing boards to find gentler gases.", evidence: "sent back to their drawing boards to find gentler gases", vocab: ["gentler gases", "replacement gases"] },
      ],
    },
    {
      title: "Passage 2",
      instructions: "You should spend about 20 minutes on Questions 14–26, which are based on Reading Passage 2 below.",
      passageTitle: "Bringing back the dunes",
      passage: `A — Ask an engineer how to defend a low-lying coast and the traditional answer is concrete: sea walls, groynes and blocks of imported stone. Yet along thousands of kilometres of shoreline, the best defence was built free of charge by the wind. A healthy belt of sand dunes behaves like a shock absorber, soaking up the fury of winter storms and then quietly repairing itself as the wind returns sand to the beach face. The coastal economist Amara Diallo has compared the accounts of towns that rely on each approach, and her conclusion is blunt: keeping a dune system healthy costs a small fraction of the price of building and endlessly repairing a sea wall, which, once cracked, protects nobody. Unlike concrete, she notes, a dune that is damaged in one storm can rebuild itself before the next.

B — A dune begins with an obstacle — a line of seaweed, a piece of driftwood — that slows the wind and makes it drop its cargo of dry sand. What turns that first ridge into a hill is a plant. Marram grass thrives where almost nothing else survives, and it has one extraordinary talent: burial makes it stronger. Each time fresh sand covers its shoots, the grass grows up through the new layer and sends out more roots, knitting the loose surface together. Metre by metre, over decades, the partnership of wind, sand and marram raises dunes that can stand ten storeys high. The relationship works in only one direction, however. Where fresh sand stops arriving, the grass is no longer buried, its vigour fades, and within a few seasons the plant that built the dune begins to die back on the very hill it made.

C — Dunes are also easily destroyed. Some are dug away for building land; many more are starved when harbour walls and river dams cut off the supply of fresh sand that every dune system needs. Trampling does quieter damage: a single well-worn path through the marram can widen into a bare scar that the wind then tears open, and a footpath abandoned by walkers may take twenty years to green over again. And some wounds were inflicted with good intentions. The ecologist Grace Muller has catalogued the shrubs and trees that managers planted on dunes over the last century to hold the sand still — sea buckthorn, garden roses, plantations of pines. Freed from their natural enemies, several of these introductions now smother whole dune systems, shading out the low, sun-loving plants that belong there.

D — The deeper problem, researchers now argue, is the very idea that a good dune is a motionless one. Dunes fixed under a complete carpet of vegetation — so-called grey dunes — grow stale, and surveys show that they support fewer species than coasts where bare sand still moves. In the Netherlands, the ecologist Marieke Visser leads teams that do what earlier managers would have considered vandalism: they cut wide notches through the grassy front line of dunes so that the wind can pour through and carry sand inland once again. The results have startled her critics. The warm, open surfaces created by the moving sand are precisely the habitat that rare insects and sand lizards require, and species unseen for decades have returned within a few years of the first cut.

E — Restoration does not always need bulldozers. On the coast of north Wales, project officer Owen Prichard has spent a decade showing what volunteers can achieve with the simplest of tools. His teams hammer in lines of chestnut-paling fences to slow the wind, plant marram by hand through the bare patches, and lay boardwalks so that visitors can cross the dunes without cutting new paths. Each January, lorries deliver thousands of used Christmas trees, which are buried in rows along the eroding front of the dunes; the dead branches trap blowing sand just as driftwood once did, and a waste product becomes a sea defence. Schools, anglers and retired farmers turn out for the winter working parties, and Prichard argues that this local army is the project's real achievement.

F — How do we know any of it works? In southern Spain, the geographer Lucia Ortega has flown drone surveys over restored dunes every three months for eight years, building centimetre-accurate maps of how each ridge grows, shifts and heals. Her records show that recovery is real but slow, and that a project judged after a single summer will almost always be judged a failure; commitment, she writes, has to be measured in decades. Her maps also carry a warning. A dune belt cut off from its beach will starve however carefully it is planted, and where the natural supply has been interrupted, sand sometimes has to be added artificially through beach nourishment — pumping dredged sand onshore for the wind to redistribute. A dune, Ortega concludes, is not a wall to be built once but a process to be kept running: stop feeding it, and even the greenest, best-loved hills of sand will slowly step backwards into the sea.`,
      questions: [
        { n: 14, type: "match", group: "minfo", letters: "ABCDEF",
          rubric: "Reading Passage 2 has six paragraphs, A–F. Which paragraph contains the following information? Write the correct letter, A–F. NB You may use any letter more than once.",
          prompt: "an explanation of how a plant enables dunes to gain height", answer: "B",
          explain: "Paragraph B describes marram grass, which grows up through each new layer of sand and knits the surface together, raising dunes storey by storey.",
          evidence: "burial makes it stronger", vocab: ["raises dunes", "gain height"] },
        { n: 15, type: "match", group: "minfo", prompt: "examples of species planted deliberately that now cause damage", answer: "C", explain: "Paragraph C lists sea buckthorn, garden roses and pines, planted to hold sand still, which now smother whole dune systems — harm done with good intentions.", evidence: "some wounds were inflicted with good intentions", vocab: ["introductions", "species planted deliberately"] },
        { n: 16, type: "match", group: "minfo", prompt: "a comparison of the costs of two different coastal defences", answer: "A", explain: "Paragraph A contains Diallo's comparison: maintaining a dune system costs a small fraction of the price of building and endlessly repairing a sea wall.", evidence: "costs a small fraction of the price", vocab: ["defence", "coastal defences"] },
        { n: 17, type: "match", group: "minfo", prompt: "an account of a waste product being reused to protect a coast", answer: "E", explain: "Paragraph E describes the used Christmas trees buried along the eroding dune front, where the dead branches trap sand — a waste product becomes a defence.", evidence: "a waste product becomes a sea defence", vocab: ["used Christmas trees", "waste product"] },
        { n: 18, type: "gap", group: "sum2", note: "ONE WORD ONLY",
          notes: {
            title: "Summary — The case for letting dunes move",
            lines: [
              "Managers long assumed that a good dune was a stable one. In fact, dunes fixed under complete vegetation support fewer {{18}} than coasts where bare sand still blows.",
              "Dutch restoration teams therefore cut wide {{19}} through the front line of dunes, letting the wind carry {{20}} inland once again.",
              "The warm, open ground this creates is exactly the habitat that rare {{21}} and sand lizards need.",
              "Even so, a dune system cut off from its beach will starve, and the supply sometimes has to be topped up artificially through beach {{22}}.",
            ],
          },
          answer: "species",
          explain: "After 'fewer', the gap needs a plural noun; the passage says surveys show grey dunes support fewer species than coasts with moving sand.",
          evidence: "they support fewer species", vocab: ["motionless", "stable"] },
        { n: 19, type: "gap", group: "sum2", answer: "notches", explain: "Visser's teams cut wide notches through the grassy front line of the dunes so that wind can pour through — the summary repeats the passage's own noun.", evidence: "they cut wide notches through the grassy front line" },
        { n: 20, type: "gap", group: "sum2", answer: "sand", explain: "The purpose of the notches is stated directly: the wind pours through and carries sand inland once again, so sand is the concrete noun the gap needs.", evidence: "carry sand inland once again" },
        { n: 21, type: "gap", group: "sum2", answer: "insects", explain: "'Need' in the summary paraphrases 'require' in the passage: the warm, open surfaces are precisely the habitat that rare insects and sand lizards require.", evidence: "rare insects and sand lizards require", vocab: ["require", "need"] },
        { n: 22, type: "gap", group: "sum2", answer: "nourishment", explain: "Where the natural sand supply is interrupted, sand is added artificially through beach nourishment — pumping dredged sand onshore for the wind to spread.", evidence: "added artificially through beach nourishment", vocab: ["added artificially", "topped up artificially"] },
        { n: 23, type: "match", group: "people", boxTitle: "List of People",
          box: [
            "Amara Diallo",
            "Grace Muller",
            "Marieke Visser",
            "Owen Prichard",
            "Lucia Ortega",
          ],
          rubric: "Look at the following statements (Questions 23–26) and the list of people below. Match each statement with the correct person, A–E. NB There is one more person than you need.",
          prompt: "Deliberately damaging a dune can improve its condition.", answer: "C",
          explain: "Visser's teams cut notches through dunes — what earlier managers would have called vandalism — and rare species returned within a few years.",
          evidence: "earlier managers would have considered vandalism", vocab: ["vandalism", "deliberately damaging"] },
        { n: 24, type: "match", group: "people", prompt: "Natural coastal defences are far cheaper to keep up than built ones.", answer: "A", explain: "Diallo compared the accounts of towns using each approach: a healthy dune system costs a small fraction of the price of a sea wall and repairs itself.", evidence: "keeping a dune system healthy costs a small fraction", vocab: ["keeping healthy", "keep up"] },
        { n: 25, type: "match", group: "people", prompt: "The success of a restoration project can only be judged over many years.", answer: "E", explain: "Ortega's eight years of drone maps show recovery is real but slow: a project judged after one summer looks like a failure, so commitment is measured in decades.", evidence: "commitment, she writes, has to be measured in decades", vocab: ["measured in decades", "over many years"] },
        { n: 26, type: "match", group: "people", prompt: "Ordinary residents can restore dunes using very simple methods.", answer: "D", explain: "Prichard's volunteers — schools, anglers, retired farmers — use hand tools, fences, boardwalks and old trees, and he calls this local army the real achievement.", evidence: "what volunteers can achieve with the simplest of tools", vocab: ["volunteers", "ordinary residents"] },
      ],
    },
    {
      title: "Passage 3",
      instructions: "You should spend about 20 minutes on Questions 27–40, which are based on Reading Passage 3 below.",
      passageTitle: "The urge to collect",
      passage: `Somewhere in almost every home there is a shelf, a drawer or a box that has quietly become a collection: teapots, vinyl records, seashells, football programmes, ticket stubs from long-forgotten journeys. Surveys suggest that around a third of adults in wealthy countries collect something deliberately, and the habit respects no boundaries of income, age or education. A hedge-fund manager hunting a rare wristwatch and a child trading picture cards in a playground are, psychologically speaking, engaged in much the same project. The interesting question is not who collects — almost anyone, given the chance — but why the gathering of objects we do not strictly need should be so widespread, so absorbing, and at times so difficult to stop.

One family of explanations looks to the machinery of valuation in the mind. People consistently price an object higher the moment it becomes theirs — the endowment effect, demonstrated in hundreds of experiments with coffee mugs, chocolate and lottery tickets — and a collection is, in one sense, the endowment effect given a shelf of its own. But ownership turns out to be only half the story. The consumer researcher Helena Voss has spent years interviewing and observing collectors, and her data point to an awkward conclusion: the peak of pleasure comes not from possession but from pursuit. Collectors in her studies described the moment of finding a longed-for item — in a market stall, an online auction, a relative's attic — as the emotional summit of the hobby, after which the object itself often went into a cupboard, scarcely looked at again. The chase, not the catch, is what the hobby reliably delivers, and a completed collection is as much an ending as a triumph; some of Voss's collectors admitted to deliberately leaving one gap unfilled.

A second explanation concerns control. Life is large, untidy and mostly beyond our influence; a collection is small, bounded and utterly obedient. Within its boundaries the collector decides what belongs and what does not, what is displayed and what is stored, and how the whole is to be arranged — by date, by colour, by country, by size. Psychologists who study the hobby note how much of its satisfaction lies not in acquiring objects but in cataloguing them: the quiet evenings spent sorting, labelling and imposing order are described by many collectors as the most restful part of the week. It is often claimed that this appetite is planted in childhood, and that adult collectors are simply continuing their earliest games of sorting and hoarding treasure. The claim is repeated in almost every popular article on the subject; the evidence for it, however, is surprisingly thin, resting on memory and anecdote rather than on any systematic study.

Collections also do social work. What we gather advertises what we are: the collection becomes part of the owner's identity, a biography told in objects, and collectors' clubs, fairs and online forums turn a private habit into a shared language. The grandest version of this impulse shaped our public institutions. The cabinets of curiosities assembled by Renaissance princes and scholars — rooms crammed with fossils, coins, corals and carvings — were private hoards of wonder, yet catalogued, studied and shown to visitors; several of them, handed on and enlarged, became the founding cores of Europe's great public museums. The private urge to accumulate, given time and generosity, built institutions that now belong to everyone.

It is precisely this organising, meaning-making character that separates collecting from its clinical shadow. Hoarding disorder, recognised by psychiatrists as a distinct condition, can look superficially similar — objects accumulate, rooms fill — but the psychologist Joanna Pell, who has worked with sufferers for two decades, insists the resemblance is misleading. Her patients do not select, arrange or display what they keep; possessions pile up unsorted, every discard feels dangerous. And where a collection brings its owner pride and company, hoarding brings shame, isolation and real distress. Confusing the two, Pell argues, insults the healthy hobby and trivialises the illness. A collector curates a world; a hoarder is buried by one.

What, finally, of the money? Popular coverage of collecting is dominated by auction records and lucky attic finds, and a minority of collectors do frame the hobby as investment. But studies of collectors' own accounts repeatedly find financial motives near the bottom of the list, well below pleasure, knowledge and belonging, and most collections never come to market at all; they are given away, inherited, or dispersed unsold. The persistence of collecting in the digital age makes the same point. People now assemble playlists, photograph libraries and museum-sized sets of items in video games — collections with no resale value and, often, no physical existence whatever. The urge evidently does not depend on the objects' worth, nor even on the objects. Collecting endures because it converts the world's overwhelming abundance into something ordered, personal and finishable — a game with rules of one's own making, in which anyone, for the price of a shoebox, can be curator, historian and heir at once.`,
      questions: [
        { n: 27, type: "mcq", prompt: "In the first paragraph, the writer's main point about collecting is that", options: ["A it respects no boundaries of income", "B it is a puzzlingly common activity", "C it is most absorbing in childhood", "D it involves objects we strictly need"], answer: "B", explain: "The paragraph's real question is why gathering unneeded objects is 'so widespread, so absorbing'. Option A echoes the passage's exact words but is a detail, not the point.", evidence: "should be so widespread, so absorbing", vocab: ["widespread", "common"] },
        { n: 28, type: "mcq", prompt: "According to Voss's research, collectors gain the greatest enjoyment from", options: ["A displaying items on a shelf of their own", "B the moment an object becomes theirs", "C searching for and finding wanted items", "D completing a collection at last"], answer: "C", explain: "Voss found the peak of pleasure comes from pursuit, not possession — 'searching for and finding' paraphrases 'the chase'. Options B and D echo the passage's wording.", evidence: "the peak of pleasure comes not from possession but from pursuit", vocab: ["pursuit", "searching"] },
        { n: 29, type: "mcq", prompt: "The writer mentions cabinets of curiosities in order to show that", options: ["A Renaissance princes collected fossils, coins and corals", "B private collections were rarely shown to visitors", "C early collectors refused to catalogue their objects", "D personal collections helped create public institutions"], answer: "D", explain: "The point is that private hoards of wonder, handed on and enlarged, became the founding cores of public museums. Option A merely repeats a supporting detail.", evidence: "became the founding cores of Europe's great public museums", vocab: ["public institutions", "public museums"] },
        { n: 30, type: "mcq", prompt: "According to Pell, hoarding differs from collecting because hoarders", options: ["A keep everything and organise nothing", "B accumulate objects until rooms fill", "C feel pride in what they possess", "D collect items of little market value"], answer: "A", explain: "Pell's patients do not select, arrange or display; possessions pile up unsorted and every discard feels dangerous. Option B echoes the passage but describes both groups.", evidence: "possessions pile up unsorted, every discard feels dangerous", vocab: ["unsorted", "organise nothing"] },
        { n: 31, type: "ynng", prompt: "Owning an object increases the value a person places on it.", answer: "YES", explain: "YES: the endowment effect means people consistently price an object higher the moment it becomes theirs, shown in hundreds of experiments.", evidence: "price an object higher the moment it becomes theirs", vocab: ["price higher", "increases the value"] },
        { n: 32, type: "ynng", prompt: "There is strong evidence that collecting always begins in childhood.", answer: "NO", explain: "NO: the writer says this claim is repeated everywhere but the evidence for it is surprisingly thin, resting on memory and anecdote rather than systematic study.", evidence: "the evidence for it, however, is surprisingly thin", vocab: ["surprisingly thin", "strong evidence"] },
        { n: 33, type: "ynng", prompt: "Collecting is more popular among older people than younger ones.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage says the habit respects no boundaries of age, but it never compares how popular collecting is across different age groups.", evidence: "no boundaries of income, age or education" },
        { n: 34, type: "ynng", prompt: "Treating collecting and hoarding as the same thing is a mistake.", answer: "YES", explain: "YES: the writer presents Pell's argument approvingly — confusing the two insults the healthy hobby and trivialises the illness; the resemblance is misleading.", evidence: "Confusing the two, Pell argues, insults the healthy hobby", vocab: ["confusing the two", "treating as the same"] },
        { n: 35, type: "ynng", prompt: "Most collectors are chiefly motivated by the hope of profit.", answer: "NO", explain: "NO: studies of collectors' own accounts repeatedly place financial motives near the bottom of the list, well below pleasure, knowledge and belonging.", evidence: "financial motives near the bottom of the list", vocab: ["financial motives", "hope of profit"] },
        { n: 36, type: "gap", group: "wl",
          box: ["boundaries", "childhood", "display", "identity", "money", "order", "pleasure", "sets", "distress"],
          boxTitle: "List of Words",
          notes: {
            title: "Summary — What a collection gives its owner",
            lines: [
              "A collection offers a miniature world with clear {{36}}, inside which the collector alone decides what belongs.",
              "Many collectors say that imposing {{37}} on their objects — sorting and labelling them — is the calmest part of their week.",
              "The hobby also delivers {{38}}, which research locates in the hunt rather than in ownership.",
              "Beyond that, a collection expresses its owner's {{39}}, telling a life story through objects.",
              "Hoarding, by contrast, involves no selection or arrangement and brings genuine {{40}} rather than pride.",
            ],
          },
          answer: "A",
          explain: "The passage contrasts untidy life with a collection that is small and bounded: within its boundaries the collector decides everything, so A fits the gap.",
          evidence: "Within its boundaries the collector decides", vocab: ["bounded", "clear boundaries"] },
        { n: 37, type: "gap", group: "wl", answer: "F", explain: "Collectors describe the evenings spent sorting, labelling and imposing order as the most restful part of the week — 'imposing order' is repeated in the summary.", evidence: "sorting, labelling and imposing order" },
        { n: 38, type: "gap", group: "wl", answer: "G", explain: "Voss located the peak of pleasure in pursuit rather than possession, so the word the summary needs for what the hobby delivers is pleasure, letter G.", evidence: "The chase, not the catch, is what the hobby reliably delivers", vocab: ["the chase", "the hunt"] },
        { n: 39, type: "gap", group: "wl", answer: "D", explain: "The passage says what we gather advertises what we are: the collection becomes part of the owner's identity, a biography told in objects — letter D.", evidence: "the collection becomes part of the owner's identity", vocab: ["a biography told in objects", "a life story"] },
        { n: 40, type: "gap", group: "wl", answer: "I", explain: "Where collecting brings pride and company, hoarding brings shame, isolation and real distress — so the summary's final gap needs distress, letter I.", evidence: "hoarding brings shame, isolation and real distress", vocab: ["real distress", "genuine distress"] },
      ],
    },
  ],
};
