// Smart LC Pre-IELTS Set 1 — Academic Reading (40 questions, 3 passages).
// Original material authored for Smart LC to the blueprint: P1 factual
// history (completion + TFNG), P2 discursive with lettered paragraphs
// (matching paragraph-information + summary + people matching with one
// extra name), P3 argumentative psychology (MCQ-4 + YNNG + sentence
// endings). Key quotas: TFNG/YNNG balanced with no runs of three, flat
// letters, unique concrete-noun answers, correct MCQ options paraphrase
// the text while distractors echo its wording. Enrichment authored in.
export const UPSET1_READING = {
  id: "upset1-reading",
  bookId: "upset1",
  title: "Pre-IELTS Set 1 — Reading",
  module: "reading",
  durationMin: 60,
  sections: [
    {
      title: "Passage 1",
      instructions: "You should spend about 20 minutes on Questions 1–13, which are based on Reading Passage 1 below.",
      passageTitle: "Striking a light",
      passage: `For almost the whole of human history, fire was easy to keep but remarkably hard to start. A household that let its hearth go out faced a tedious ritual. A piece of flint was struck again and again against a steel until a spark fell onto a scrap of burnt cloth, which glowed rather than burned and had to be coaxed, with dry straw and gentle breathing, into a true flame. The equipment lived in a small metal tinderbox beside the fireplace, and in practised hands the whole operation might take three or four minutes. In damp weather it could take half an hour, and it frequently failed altogether — which is why many people found it simpler to walk to a neighbour's house and carry home a burning coal.

Chemistry promised something better. Phosphorus, first isolated in Germany in 1669, would ignite with the gentlest warmth, but it was costly, poisonous and alarmingly unpredictable, and for more than a century it remained a scientific curiosity rather than a household tool. The first commercial "instant lights", sold in Paris from 1805, were hardly more practical: thin sticks tipped with a chemical paste that burst into flame when the tip was dipped into a little bottle of acid. They delighted wealthy buyers as a novelty, but carrying a glass bottle of acid in a coat pocket was never likely to become a popular habit, and more than one customer was badly burned when a bottle broke.

The true match was born by accident. In 1826, in the north of England, a pharmacist named John Walker was preparing a batch of combustible paste, of a kind then used in sporting guns, in the room behind his shop. When the mixture was ready, a dried blob remained on the end of the wooden stick he had used for stirring, and Walker scraped the stick against the stone floor to clean it. The blob burst instantly into flame. Walker understood at once what he had found: fire produced by nothing but friction, with no acid, no sunshine and no skill required. From 1827 he sold his "friction lights" in tins of fifty, each tin supplied with a piece of folded sandpaper through which a match was drawn sharply to light it. Yet he refused to patent the invention, telling friends that something so useful to the public should be free for anyone to copy.

Copied it duly was. A London businessman, Samuel Jones, brought out his own version under the memorable name "Lucifers", and sales grew quickly in spite of the product's obvious faults: the early matches lit with a small explosion, showering sparks across the room, and gave off a smell so unpleasant that the boxes carried a printed warning to persons with delicate lungs. In the 1830s, makers found the improvement the public wanted — a head containing white phosphorus, which struck silently and smoothly on any rough surface. Yet the convenience carried a hidden danger, for matches that will light on anything will sometimes light on one another: loose matches rubbing together in a pocket, or shaken about in a cart on a cobbled street, started countless small fires, and insurance companies came to dread them.

The heaviest price, however, was paid in the match factories. Dipping the matches was work done mainly by women and girls, bent all day over trays of warm phosphorus paste, and the vapour rising from the trays attacked the bones of the face. The disease began as toothache, moved on to painful swelling, and ended in the decay of the jaw itself; sufferers were left disfigured, and some died. A safe alternative — red phosphorus, a harmless form of the same element — had been known since the 1840s, yet manufacturers continued using the white kind for decades, because it was cheaper and their customers were used to it. Reform came only under pressure, driven by newspaper campaigns and by a famous strike of London match workers in 1888, and an international agreement finally prohibited white phosphorus in matches in 1906.

The remedy had existed all along. As early as 1844, the Swedish chemist Gustaf Erik Pasch had proposed a simple separation: remove the dangerous ingredient from the match head altogether, and paint a strip containing red phosphorus onto the side of the box instead. A match built this way lights only when the two prepared surfaces meet; scraped against a wall, a boot or a table, it does nothing at all. Pasch's idea was perfected in the 1850s by the brothers Johan and Carl Lundström, whose factory turned the "safety match" into a product that could be made by the million, and Sweden dominated the world match trade for the rest of the century.

The twentieth century slowly made the match unnecessary. The petrol lighter, the gas cooker with electric ignition and finally the push-button spark reduced it to an occasional convenience, and the old factories closed one by one. Yet the small wooden stick refuses to disappear entirely: it needs no fuel, costs almost nothing, and lights candles, camp stoves and birthday cakes as well as it ever did. In Walker's home town, a plaque marks the shop where a careless scrape on a stone floor ended several thousand years of striking flint against steel — and put fire, for the first time, in everyone's pocket.`,
      questions: [
        { n: 1, type: "gap", prompt: "Before matches, a spark had to land on a piece of burnt ______ before a flame could be made.", note: "ONE WORD ONLY", answer: "cloth", explain: "The first paragraph describes the tinderbox routine: the spark fell onto burnt cloth, which only glowed and then had to be coaxed into flame.", evidence: "a spark fell onto a scrap of burnt cloth" },
        { n: 2, type: "gap", prompt: "Walker's discovery began with dried paste left on a wooden ______ he had used for mixing.", note: "ONE WORD ONLY", answer: "stick", explain: "'Mixing' in the question paraphrases 'stirring' in the passage: the dried blob remained on the wooden stick Walker had stirred the paste with.", evidence: "the wooden stick he had used for stirring", vocab: ["stirring", "mixing"] },
        { n: 3, type: "gap", prompt: "Each tin of friction lights was supplied with a piece of folded ______ for striking.", note: "ONE WORD ONLY", answer: "sandpaper", explain: "The passage states this directly: every tin of fifty came with folded sandpaper, and the match was drawn sharply through it to light.", evidence: "each tin supplied with a piece of folded sandpaper" },
        { n: 4, type: "gap", prompt: "From the 1830s, match heads containing white ______ would light on any rough surface.", note: "ONE WORD ONLY", answer: "phosphorus", explain: "The improvement the public wanted was a head of white phosphorus, which struck silently and smoothly anywhere — the 'strike-anywhere' match.", evidence: "a head containing white phosphorus, which struck silently and smoothly" },
        { n: 5, type: "gap", prompt: "Factory vapour caused a disease that ended in the decay of the sufferer's ______.", note: "ONE WORD ONLY", answer: "jaw", explain: "The disease progressed in stages — toothache, then swelling, then decay of the jaw itself — so the gap needs the bone the vapour destroyed.", evidence: "ended in the decay of the jaw itself" },
        { n: 6, type: "gap", prompt: "A safety match can only be lit on the treated strip on the side of its ______.", note: "ONE WORD ONLY", answer: "box", explain: "Pasch moved the red phosphorus onto the box: only when match head and prepared strip meet does the match light, so 'box' completes the sentence.", evidence: "paint a strip containing red phosphorus onto the side of the box", vocab: ["prepared surfaces", "treated strip"] },
        { n: 7, type: "tfng", prompt: "Attempts to start a fire in damp conditions were often unsuccessful.", answer: "TRUE", explain: "TRUE: 'often unsuccessful' paraphrases 'frequently failed altogether' — in damp weather the tinderbox could take half an hour or fail completely.", evidence: "it frequently failed altogether", vocab: ["frequently failed", "often unsuccessful"] },
        { n: 8, type: "tfng", prompt: "Walker took out a patent to protect his invention.", answer: "FALSE", explain: "FALSE: the passage says the opposite — he refused to patent it, believing something so useful should be free for anyone to copy.", evidence: "he refused to patent the invention" },
        { n: 9, type: "tfng", prompt: "Walker became wealthy from the sale of his friction lights.", answer: "NOT GIVEN", explain: "NOT GIVEN: we learn how the matches were sold and that Walker refused a patent, but nothing at all about how much money he made.", evidence: "something so useful to the public should be free" },
        { n: 10, type: "tfng", prompt: "Early strike-anywhere matches sometimes caught fire without being struck deliberately.", answer: "TRUE", explain: "TRUE: matches that light on anything sometimes lit on each other — rubbing together in pockets or shaken in carts, they started countless fires.", evidence: "loose matches rubbing together in a pocket", vocab: ["started countless small fires", "caught fire"] },
        { n: 11, type: "tfng", prompt: "Match manufacturers stopped using white phosphorus soon after a safer form became available.", answer: "FALSE", explain: "FALSE: red phosphorus was known from the 1840s, yet makers kept using the white kind for decades because it was cheaper — the opposite of 'soon'.", evidence: "manufacturers continued using the white kind for decades" },
        { n: 12, type: "tfng", prompt: "Swedish factories led the world's match industry in the late nineteenth century.", answer: "TRUE", explain: "TRUE: after the Lundström brothers industrialised the safety match in the 1850s, Sweden dominated the world match trade for the rest of the century.", evidence: "Sweden dominated the world match trade", vocab: ["dominated", "led"] },
        { n: 13, type: "tfng", prompt: "Walker's design was copied by manufacturers in countries outside Britain.", answer: "NOT GIVEN", explain: "NOT GIVEN: the only copier named is Samuel Jones of London, and the Swedish match was a new design. Foreign copies of Walker's match are never mentioned.", evidence: "A London businessman, Samuel Jones, brought out his own version" },
      ],
    },
    {
      title: "Passage 2",
      instructions: "You should spend about 20 minutes on Questions 14–26, which are based on Reading Passage 2 below.",
      passageTitle: "Solar farms take to the water",
      passage: `A — In 2007, engineers in the Japanese prefecture of Aichi fastened a small raft of solar panels to the surface of a reservoir and connected it to the electricity grid. The installation produced just twenty kilowatts — enough for a handful of houses — and attracted little notice outside the trade press. Within fifteen years, that modest experiment had grown into an industry measured in gigawatts. China has built floating farms that cover entire lakes, including one moored on a stretch of water that appeared when an abandoned coal mine collapsed and flooded; Singapore, which has sunshine to spare but hardly any spare ground, has carpeted a drinking-water reservoir with one of the largest arrays on Earth; and hundreds of smaller schemes now float on reservoirs, irrigation ponds and flooded quarries from the Netherlands to India. "Floatovoltaics", as the technology is inelegantly known, has moved from curiosity to serious energy policy in less than two decades.

B — The first attraction is space. On land, a solar farm of any size must compete for land with farmers, builders and conservationists, and in crowded countries that competition is fierce and expensive. A reservoir, by contrast, is a surface nobody else is queuing to use. But water offers a second, less obvious gift. Solar panels dislike heat: the hotter a panel becomes, the less of the light falling on it is turned into electricity. Floating panels, cooled from below by the water they sit on, run several degrees cooler than identical panels in a field. Henrik Dahl, an engineer who has installed floating systems in six countries, has measured the difference repeatedly. "Over water, the same panel gives an output five to ten per cent higher than it manages on land," he says. "The reservoir is, in effect, a free cooling system that never switches off."

C — Some of the technology's strongest arguments have nothing to do with electricity at all. Amina Rashid, who advises water authorities in several hot, dry countries, points out that an open reservoir is a leaking one: under a fierce sun, a worrying share of the water stored for cities and farms simply vanishes into the sky. "Evaporation steals water that somebody has already paid to collect," she says. "A floating array is a lid as well as a power station." Measurements on covered reservoirs suggest the panels can cut that loss substantially, and the shade they cast brings a second benefit: by keeping sunlight off the water, the panels discourage the growth of algae, which flourish in warm, bright water and can clog filters and raise the cost of treating drinking water.

D — There is also a marriage of convenience on offer with an older technology. Hydroelectric dams already possess the slowest and most expensive parts of any power project: transmission lines, substations and a connection to the grid. Beatriz Costa, an energy analyst who has studied hybrid schemes on three continents, notes that this equipment often sits half-used for much of the year. "A floating farm on a hydropower reservoir can plug straight into infrastructure that has already been built and paid for," she says. The two sources also keep conveniently different hours: the panels generate through the day and through the dry season, while the dam's stored water can be saved for the evening peak and for the months when the rains come and the skies darken.

E — Not everyone is eager to carpet lakes with plastic and silicon. Sunlight is the energy source for nearly everything that lives in a lake, and a solar panel is, by design, a shadow. Lena Vogel, a freshwater ecologist, argues that the industry is expanding faster than the science that ought to guide it. Most floating farms are less than a decade old, she notes, and studies of their effects on plants, fish and water chemistry remain short-term and few. "We are attaching a new industry to living systems we only partly understand," she says. Until longer records exist, she recommends covering only a modest fraction of any single lake, avoiding ecologically sensitive waters altogether, and treating every large installation as an experiment to be measured, season after season, rather than a finished product.

F — The remaining obstacle is money. A floating farm needs floats, anchors, waterproof cabling and metalwork that can survive years of damp, and it therefore costs more to build than the same capacity in a field. That premium, however, is shrinking. Grace Ampofo, an economist who tracks the industry's costs, calculates that the gap has narrowed year by year as manufacturers standardise their floats and installation crews learn the work, and that where land is scarce or dear, floating projects are already the cheaper choice once the price of ground is counted in. The next frontier is the sea itself, where waves and salt punish equipment far more brutally than any reservoir; trial platforms are riding out storms off the Dutch coast. For a technology that began as a twenty-kilowatt curiosity on a quiet Japanese reservoir, the water ahead looks anything but calm — and anything but empty.`,
      questions: [
        { n: 14, type: "match", group: "minfo", letters: "ABCDEF",
          rubric: "Reading Passage 2 has six paragraphs, A–F. Which paragraph contains the following information? Write the correct letter, A–F. NB You may use any letter more than once.",
          prompt: "a way floating solar can share facilities built for another kind of power station", answer: "D",
          explain: "Paragraph D describes the marriage with hydropower: dams already own the transmission lines, substations and grid connection that a floating farm can use.",
          evidence: "transmission lines, substations and a connection to the grid", vocab: ["plug straight into", "share"] },
        { n: 15, type: "match", group: "minfo", prompt: "figures showing how much the technology has grown", answer: "A", explain: "Paragraph A gives the growth figures: from a twenty-kilowatt raft in 2007 to an industry measured in gigawatts within fifteen years.", evidence: "grown into an industry measured in gigawatts" },
        { n: 16, type: "match", group: "minfo", prompt: "a call for more research into the technology's environmental effects", answer: "E", explain: "Paragraph E is the ecologist's warning: studies are short-term and few, so coverage should stay modest until longer records exist.", evidence: "studies of their effects on plants, fish and water chemistry remain short-term", vocab: ["short-term and few", "more research"] },
        { n: 17, type: "match", group: "minfo", prompt: "an explanation of why panels perform better over water than on land", answer: "B", explain: "Paragraph B explains the cooling effect: panels lose efficiency as they heat, and water cools them, raising output five to ten per cent.", evidence: "The reservoir is, in effect, a free cooling system", vocab: ["gives an output", "perform"] },
        { n: 18, type: "match", group: "minfo", prompt: "examples of benefits that are unrelated to generating electricity", answer: "C", explain: "Paragraph C opens by saying some arguments have nothing to do with electricity, then gives two: less evaporation and less algae.", evidence: "have nothing to do with electricity at all", vocab: ["nothing to do with", "unrelated to"] },
        { n: 19, type: "gap", group: "sum2", note: "ONE WORD ONLY",
          notes: {
            title: "Summary — Why put solar panels on water?",
            lines: [
              "On land, solar farms must compete with farmers and builders for {{19}}, which in crowded countries is costly. A reservoir surface, by contrast, has no other users waiting for it.",
              "Water also keeps panels cool, so a panel's {{20}} is five to ten per cent higher than on land.",
              "Floating arrays protect the water too: they cut the amount lost through {{21}} under a hot sun,",
              "and their shade limits the growth of {{22}}, which can block filters and make treatment more expensive.",
            ],
          },
          answer: "land",
          explain: "The summary repeats paragraph B's point: on land a farm must compete for land with farmers, builders and conservationists, and competition is expensive.",
          evidence: "must compete for land with farmers, builders and conservationists" },
        { n: 20, type: "gap", group: "sum2", answer: "output", explain: "Dahl's measurement supplies the noun: over water the same panel gives an output five to ten per cent higher, because water cools it.", evidence: "the same panel gives an output five to ten per cent higher", vocab: ["gives", "is"] },
        { n: 21, type: "gap", group: "sum2", answer: "evaporation", explain: "Rashid's point is that open reservoirs leak into the sky: evaporation steals stored water, and a floating cover cuts that loss substantially.", evidence: "Evaporation steals water that somebody has already paid to collect", vocab: ["vanishes into the sky", "lost"] },
        { n: 22, type: "gap", group: "sum2", answer: "algae", explain: "By shading the surface, panels discourage algae, which need warm bright water; the summary's 'block filters' paraphrases the passage's 'clog filters'.", evidence: "the panels discourage the growth of algae", vocab: ["clog", "block"] },
        { n: 23, type: "match", group: "people", boxTitle: "List of People",
          box: [
            "Henrik Dahl",
            "Amina Rashid",
            "Beatriz Costa",
            "Lena Vogel",
            "Grace Ampofo",
          ],
          rubric: "Look at the following statements (Questions 23–26) and the list of people below. Match each statement with the correct person, A–E. NB There is one more person than you need.",
          prompt: "Floating farms can make use of expensive equipment that already exists.", answer: "C",
          explain: "Costa, the energy analyst, says a floating farm on a hydropower reservoir plugs straight into infrastructure that has already been built and paid for.",
          evidence: "already been built and paid for", vocab: ["infrastructure", "equipment"] },
        { n: 24, type: "match", group: "people", prompt: "Panels generate more electricity because of where they are placed.", answer: "A", explain: "Dahl the engineer measured it: the same panel gives five to ten per cent more output over water, thanks to the free cooling below.", evidence: "five to ten per cent higher than it manages on land" },
        { n: 25, type: "match", group: "people", prompt: "Too little is known about the technology's long-term effects on lakes.", answer: "D", explain: "Vogel the ecologist warns that the industry is outrunning its science: farms are young and the studies of their effects are short-term and few.", evidence: "living systems we only partly understand", vocab: ["only partly understand", "too little is known"] },
        { n: 26, type: "match", group: "people", prompt: "The extra cost of building on water is becoming smaller.", answer: "E", explain: "Ampofo the economist tracks prices: the premium for floating construction has narrowed year by year as floats are standardised and crews gain experience.", evidence: "the gap has narrowed year by year", vocab: ["premium", "extra cost"] },
      ],
    },
    {
      title: "Passage 3",
      instructions: "You should spend about 20 minutes on Questions 27–40, which are based on Reading Passage 3 below.",
      passageTitle: "The hidden logic of the queue",
      passage: `Waiting in line is one of the small taxes of modern life, paid at supermarkets, airports, bus stops and, invisibly, in the electronic holding pens of telephone helplines. The obvious way to think about a queue is arithmetical: the badness of a wait equals its length in minutes, so the way to make customers happier is to serve them faster. Managers with stopwatches have followed that logic for a century. Yet several decades of research into waiting has arrived at a more awkward conclusion: the clock is a poor measure of the experience. Two waits of identical length can feel utterly different, and satisfaction depends surprisingly little on actual duration. What fills the time, what people believe about it, and how it ends usually matter more than how long it is.

The classic illustration comes from an office tower in the years after the Second World War. Tenants complained bitterly about the slowness of the lifts, and the engineers' remedies — faster motors, new machinery — carried an enormous cost. Then someone proposed something cheaper: full-length mirrors beside the lift doors on every floor. The complaints almost entirely stopped, although the lifts were not one second faster. People straightened their ties, checked their hair and quietly inspected each other; the wait had not shrunk, but it was no longer empty. The finding has been repeated in soberer settings ever since: occupied time feels far shorter than empty time. One American airport, plagued by complaints about slow baggage delivery, simply moved its arrival gates further from the carousels; passengers who had once stood fuming for six minutes now walked for most of that time, collected their bags almost at once, and the complaints faded away.

A second principle concerns information. Waits feel longest when they are unexplained and open-ended. A caller kept on hold with no idea whether the silence will last one minute or forty suffers in a way that has little to do with the minutes themselves; it is the uncertainty that corrodes patience. In studies, people who are told the expected length of a delay judge the same wait shorter and rate the service higher, and an explanation — the flight is late because of fog, the clinic is dealing with an emergency — calms them further still. This is why buses now carry countdown boards at their stops and why recorded voices announce your position in the telephone queue: the information changes nothing about the wait and almost everything about how it is endured.

The third principle is the one organisations ignore at their peril: fairness. A queue is a small social contract — whoever arrives first is served first — and people police it with an intensity out of all proportion to the minutes at stake. Research on waiting lines finds that being overtaken provokes sharper irritation than simple slowness: a wait grows suddenly intolerable when a neighbouring lane races ahead or a latecomer slips in front. Hence the quiet spread of the serpentine queue, the single winding line that feeds a row of counters, adopted by banks and airports almost everywhere. It barely changes the average wait, but it makes it impossible to be beaten by someone who arrived later, and that is the point. Experiments suggest people will happily accept a longer wait in a system that is fair over a quicker one that permits queue-jumping.

Queues also stage a quieter drama: the decision to stay or to give up. Researchers distinguish between refusing to join a line at all and abandoning it partway, and the second decision follows a curious rule. The best predictor of whether a person gives up is not the number of people ahead of them but the number behind. A long tail forming at our backs reassures us: we compare ourselves with those worse off, our place acquires value, and the more people stand behind us, the less likely we are to surrender our position. The queue, once joined, becomes an investment that people are reluctant to write off.

Commerce has learned all of this thoroughly. Theme parks post waiting times that are deliberately generous, so that the real wait beats the promise; restaurants hand out pagers so that waiting happens in comfort rather than in a doorway; call centres fill the line with menus and announcements less to inform than to occupy. Psychologists add one further refinement, borrowed from the study of memory: an experience is remembered largely through its most intense moment and its final moments, not through its average. A wait that ends briskly — the queue suddenly accelerating, a staff member opening a new counter with an apology — is remembered far more kindly than its length deserves.

There is something faintly uncomfortable in all this, and it deserves saying plainly. If feelings about waiting can be managed so cheaply, an organisation may be tempted to polish the perception and neglect the service: mirrors, after all, cost less than lifts. That temptation should be resisted, and not only for honesty's sake — no mirror redeems a queue that is genuinely chaotic, endless or unjust, and customers eventually notice the difference. The sensible conclusion is narrower: shorten what can be shortened, and design the experience of what cannot. Keep people informed, keep them occupied, keep the line visibly fair, and end the wait well. The minutes may be the same; the memory will not be.`,
      questions: [
        { n: 27, type: "mcq", prompt: "The writer tells the story of the office tower in order to show that", options: ["A replacing lift machinery is usually too expensive", "B a complaint about waiting can be cured without shortening the wait", "C mirrors are the cheapest way to decorate a lobby", "D engineers rarely listen to psychologists"], answer: "B", explain: "The mirrors ended the complaints although the lifts were no faster: the wait was unchanged but no longer empty. Options A and C echo details, not the point.", evidence: "although the lifts were not one second faster", vocab: ["complaints almost entirely stopped", "cured"] },
        { n: 28, type: "mcq", prompt: "According to the passage, a wait feels longest when people", options: ["A know exactly how long it will last", "B have been given a reason for the delay", "C are listening to recorded announcements", "D cannot tell when or why it will end"], answer: "D", explain: "Unexplained, open-ended waits corrode patience — the caller on hold suffers from uncertainty, not minutes. Options A and B describe what makes waits feel shorter.", evidence: "Waits feel longest when they are unexplained and open-ended", vocab: ["unexplained and open-ended", "cannot tell when or why"] },
        { n: 29, type: "mcq", prompt: "Banks and airports adopted the single winding queue because it", options: ["A ensures that customers are served in order of arrival", "B reduces the average time each customer waits", "C allows staff to serve more people every hour", "D gives customers something interesting to watch"], answer: "A", explain: "The serpentine line barely changes the average wait — B repeats the passage's words while reversing them. Its virtue is fairness: no latecomer can be served first.", evidence: "impossible to be beaten by someone who arrived later", vocab: ["arrives first is served first", "order of arrival"] },
        { n: 30, type: "mcq", prompt: "In the final paragraph, the writer argues that psychological techniques", options: ["A are an acceptable substitute for faster service", "B should be abandoned because they deceive customers", "C should accompany real improvements, not replace them", "D are too costly for most organisations to use"], answer: "C", explain: "The writer warns against polishing perception while neglecting service, then concludes: shorten what can be shortened and design the experience of what cannot — both together.", evidence: "shorten what can be shortened, and design the experience of what cannot" },
        { n: 31, type: "ynng", prompt: "The measured length of a wait is an unreliable guide to how it is experienced.", answer: "YES", explain: "YES: the writer says this directly — the clock is a poor measure of the experience, and identical waits can feel utterly different.", evidence: "the clock is a poor measure of the experience", vocab: ["poor measure", "unreliable guide"] },
        { n: 32, type: "ynng", prompt: "Customer satisfaction depends mainly on how long people actually wait.", answer: "NO", explain: "NO: the passage states the opposite — satisfaction depends surprisingly little on actual duration; what fills the time and how it ends matter more.", evidence: "satisfaction depends surprisingly little on actual duration" },
        { n: 33, type: "ynng", prompt: "Attitudes towards queuing vary from one country to another.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage discusses queues in shops, airports and phone lines, but never compares countries or national attitudes to queuing.", evidence: "paid at supermarkets, airports, bus stops" },
        { n: 34, type: "ynng", prompt: "People may prefer a fair queue even when it is slower.", answer: "YES", explain: "YES: experiments suggest people happily accept a longer wait in a fair system over a quicker one that lets others jump the queue.", evidence: "accept a longer wait in a system that is fair", vocab: ["permits queue-jumping", "unfair"] },
        { n: 35, type: "ynng", prompt: "The people behind a queuer have no influence on whether that person stays.", answer: "NO", explain: "NO: the passage contradicts this — the number behind is the best predictor of giving up, and a long tail behind makes people stay.", evidence: "the less likely we are to surrender our position", vocab: ["surrender our position", "stays"] },
        { n: 36, type: "match", group: "ends", boxTitle: "Sentence endings",
          box: [
            "makes the time seem to pass more quickly.",
            "persuades most people to leave and come back later.",
            "reduces the worry caused by not knowing.",
            "has a strong influence on how the whole experience is remembered.",
            "means no one can be served before someone who arrived earlier.",
            "makes people more determined to keep their place.",
            "shows that queues move faster than people expect.",
          ],
          rubric: "Complete each sentence with the correct ending, A–G, below.",
          prompt: "Giving people something to do during a wait", answer: "A",
          explain: "The mirrors and the longer airport walk both worked the same way: occupied time feels far shorter than empty time, so filled waits pass more quickly.",
          evidence: "occupied time feels far shorter than empty time", vocab: ["occupied", "something to do"] },
        { n: 37, type: "match", group: "ends", prompt: "Being told how long a delay is expected to last", answer: "C", explain: "Information calms: people told the expected length judge the same wait shorter, because uncertainty — not the minutes — is what corrodes patience.", evidence: "judge the same wait shorter and rate the service higher", vocab: ["uncertainty", "not knowing"] },
        { n: 38, type: "match", group: "ends", prompt: "A single line feeding a row of counters", answer: "E", explain: "The serpentine queue's whole purpose is order: it makes it impossible for a latecomer to overtake, so service follows arrival exactly.", evidence: "the single winding line that feeds a row of counters" },
        { n: 39, type: "match", group: "ends", prompt: "The sight of a lengthening queue behind them", answer: "F", explain: "A long tail behind reassures queuers and raises the value of their place, so the more people behind, the less likely anyone is to give up.", evidence: "the more people stand behind us, the less likely we are to surrender", vocab: ["long tail", "lengthening queue"] },
        { n: 40, type: "match", group: "ends", prompt: "The way a period of waiting finishes", answer: "D", explain: "Memory follows the peak-end rule: an experience is remembered through its most intense and final moments, so a brisk ending is remembered kindly.", evidence: "its most intense moment and its final moments", vocab: ["final moments", "finishes"] },
      ],
    },
  ],
};
