// Smart LC Upper-Inter Set 6 — Academic Reading (40 questions, 3 passages).
// Original material authored for Smart LC to the blueprint: P1 factual
// history (completion + TFNG), P2 discursive with lettered paragraphs
// (matching paragraph-information + summary + people matching with one
// extra name), P3 argumentative psychology (MCQ-4 + YNNG + wordlist
// summary). Key quotas: TFNG/YNNG balanced with no runs of three, flat
// letters, unique concrete-noun answers, correct MCQ options paraphrase
// the text while distractors echo its wording.
export const UPSET6_READING = {
  id: "upset6-reading",
  bookId: "upset6",
  title: "Upper-Inter Set 6 — Reading",
  module: "reading",
  durationMin: 60,
  sections: [
    {
      title: "Passage 1",
      instructions: "You should spend about 20 minutes on Questions 1–13, which are based on Reading Passage 1 below.",
      passageTitle: "The needle that knew the way",
      passage: `For most of human history, finding the way at sea meant looking up. Sailors steered by the sun during the day and by the pole star at night, and whenever possible they kept within sight of familiar headlands and river mouths. The weakness of the system was the weather: under a grey sky there was nothing to steer by, and a ship out of sight of land was, quite simply, lost. A small instrument that pointed the same way in fog, cloud and darkness would eventually solve the problem — yet that instrument began its career far from the ocean, in the hands of people who had no interest in ships at all.

The story starts with the lodestone, a naturally magnetised piece of iron ore which, allowed to turn freely, always comes to rest in the same alignment. Chinese texts were describing its curious powers more than two thousand years ago. The earliest known direction-finder was not a needle but a spoon: carved from lodestone and balanced on a polished bronze plate, it could be set spinning, and when it stopped, its handle pointed south. This "south-pointer", however, had nothing to do with travel. It belonged to diviners, who used it in ceremonies to decide the most favourable position for a new house, a city gate or a tomb, so that buildings would sit in harmony with the unseen forces of the earth.

The device that sailors would one day trust grew out of a simpler discovery: an ordinary iron needle, stroked repeatedly with a lodestone, becomes magnetic itself. Writing in the eleventh century, the Chinese scholar Shen Kuo described several ways of mounting such a needle, including hanging it from a single thread of silk, and he recorded something remarkable: the needle did not point exactly south, but always a little to one side. The gap between magnetic and true direction, which would puzzle navigators for centuries, was noticed before the instrument ever went to sea. When it finally did, the arrangement was wonderfully crude. The needle was floated in a bowl of water, where it swung slowly until it settled. A Chinese handbook written around 1119 remarks that on clear nights sailors steered by the stars, but in thick weather they relied on the floating needle — the first written record, anywhere in the world, of a compass used for navigation.

Europeans were describing the same instrument within a century. The first European account appeared in 1190, when Alexander Neckam, an English monk, noted matter-of-factly that sailors touched a needle with a magnet and let it show them the way when sun and stars were hidden. Whether the idea had travelled from China along the trade routes, or had been discovered separately in Europe, is a question historians cannot settle: the records are too thin, and the two traditions mounted their needles differently, which some scholars read as a sign of independent invention.

It was in the Mediterranean that the compass grew into a precision instrument. The floating bowl gave way to the dry compass: a needle balanced on a fine pin inside a small box and — the crucial refinement — fixed beneath a circular card marked with the directions of the winds. Because the card turned with the needle, a helmsman could read his heading at a glance instead of judging the angle of a bare sliver of metal. Tradition credits the improvement to the Italian port of Amalfi, though the man the town celebrates as the inventor probably never existed. What is certain is the effect on trade. Winter voyages had once been abandoned because thick cloud hid the sun and stars for weeks at a time; with the new instrument, Italian merchant fleets began sailing almost the whole year round, and a galley could now make two return trips to Egypt each year where one had been possible before.

The compass, however, has never been quite as honest as it looks. The needle points to the magnetic pole, not the geographic one, and the size of the difference changes from place to place. Crossing the Atlantic in 1492, Columbus recorded the needle's behaviour altering as he sailed west, to the alarm of his pilots. A worse problem arrived in the nineteenth century, when wooden ships gave way to metal ones: a hull full of iron pulls the needle towards itself, and early steamship navigators found their compasses misleading them by several degrees, with wrecks to prove it. The navigator Matthew Flinders, who studied the errors on his own voyages, proposed standing a vertical iron bar near the compass to cancel much of the disturbance — a device still fitted today, and still called a Flinders bar. Later ships housed the compass in a binnacle, a wooden stand containing small correcting magnets and a pair of iron spheres, adjusted until the needle told the truth again.

Modern vessels navigate by gyrocompass and by satellite, and a telephone will name your heading. Yet international regulations still require every large ship to carry a magnetic compass, and the reason is its stubborn simplicity: it needs no electricity, contains almost nothing that can break, and no storm or power failure can switch it off. Nine centuries after a needle first bobbed in a bowl of water, the instrument it became still waits on every bridge, quietly pointing, for everything newer to go wrong.`,
      questions: [
        { n: 1, type: "gap", prompt: "The earliest Chinese direction-finder was a spoon that turned on a bronze ______.", note: "ONE WORD ONLY", answer: "plate", explain: "The second paragraph describes the lodestone spoon balanced on a polished bronze plate; when it stopped spinning, its handle pointed south.", evidence: "balanced on a polished bronze plate" },
        { n: 2, type: "gap", prompt: "A needle could be made magnetic by rubbing it with a ______.", note: "ONE WORD ONLY", answer: "lodestone", explain: "'Rubbing' in the question paraphrases 'stroked' in the passage: an iron needle stroked repeatedly with a lodestone becomes magnetic itself.", evidence: "stroked repeatedly with a lodestone, becomes magnetic itself", vocab: ["stroked", "rubbing"] },
        { n: 3, type: "gap", prompt: "At sea, the first Chinese compasses were needles floating in a ______ of water.", note: "ONE WORD ONLY", answer: "bowl", explain: "The passage says the needle was floated in a bowl of water, where it swung slowly until it settled — the crude arrangement first used at sea.", evidence: "The needle was floated in a bowl of water" },
        { n: 4, type: "gap", prompt: "The first European description of the compass was written by an English ______.", note: "ONE WORD ONLY", answer: "monk", explain: "Alexander Neckam, who wrote the first European account in 1190, is identified in the passage as an English monk.", evidence: "Alexander Neckam, an English monk", vocab: ["account", "description"] },
        { n: 5, type: "gap", prompt: "In the dry compass, the needle was fixed under a circular ______ showing the winds.", note: "ONE WORD ONLY", answer: "card", explain: "The crucial refinement of the dry compass was the circular card marked with wind directions, which turned together with the needle.", evidence: "fixed beneath a circular card marked with the directions of the winds" },
        { n: 6, type: "gap", prompt: "Winter sailing had been given up because thick ______ hid the sun and stars.", note: "ONE WORD ONLY", answer: "cloud", explain: "Voyages stopped each winter because thick cloud covered the sky for weeks, leaving sailors with nothing in the heavens to steer by.", evidence: "thick cloud hid the sun and stars for weeks", vocab: ["abandoned", "given up"] },
        { n: 7, type: "gap", prompt: "On nineteenth-century ships, the needle was pulled off course by the ______ in the hull.", note: "ONE WORD ONLY", answer: "iron", explain: "When metal ships replaced wooden ones, a hull full of iron attracted the needle, and compasses misled navigators by several degrees.", evidence: "a hull full of iron pulls the needle towards itself", vocab: ["misleading them", "pulled off course"] },
        { n: 8, type: "tfng", prompt: "The south-pointer was used to choose where buildings should stand.", answer: "TRUE", explain: "TRUE: diviners used the spoon in ceremonies to decide the most favourable position for a new house, a city gate or a tomb.", evidence: "the most favourable position for a new house", vocab: ["favourable position", "where buildings should stand"] },
        { n: 9, type: "tfng", prompt: "Shen Kuo believed the needle pointed exactly towards the south.", answer: "FALSE", explain: "FALSE: Shen Kuo recorded the opposite — the needle did not point exactly south, but always a little to one side.", evidence: "the needle did not point exactly south" },
        { n: 10, type: "tfng", prompt: "Alexander Neckam had used a compass on sea journeys of his own.", answer: "NOT GIVEN", explain: "NOT GIVEN: Neckam described sailors using the needle, but the passage says nothing about whether he ever travelled by sea himself.", evidence: "sailors touched a needle with a magnet" },
        { n: 11, type: "tfng", prompt: "The dry compass allowed Mediterranean fleets to trade during more of the year.", answer: "TRUE", explain: "TRUE: once the new instrument existed, Italian fleets sailed almost the whole year round, doubling the possible voyages to Egypt.", evidence: "began sailing almost the whole year round", vocab: ["the whole year round", "more of the year"] },
        { n: 12, type: "tfng", prompt: "Matthew Flinders's method of correcting compass errors has been abandoned.", answer: "FALSE", explain: "FALSE: the vertical iron bar he proposed is still fitted today and is still known as a Flinders bar, so the method survives.", evidence: "a device still fitted today, and still called a Flinders bar" },
        { n: 13, type: "tfng", prompt: "A magnetic compass costs less to make than a gyrocompass.", answer: "NOT GIVEN", explain: "NOT GIVEN: the final paragraph praises the magnetic compass for needing no electricity, but never compares the cost of making the two instruments.", evidence: "still require every large ship to carry a magnetic compass" },
      ],
    },
    {
      title: "Passage 2",
      instructions: "You should spend about 20 minutes on Questions 14–26, which are based on Reading Passage 2 below.",
      passageTitle: "The return of the cranes",
      passage: `A — Standing well over a metre tall, with a bugling call that carries for kilometres, the common crane was once a familiar sight across the wetlands of northern Europe. In Britain its memory survives in dozens of place names — Cranfield, Cranmore, Cranbrook — each recording a marsh or meadow where the birds once gathered to perform their extravagant spring dances. Travellers' journals from the sixteenth century still describe flocks feeding in the eastern fens. By around 1600, however, the crane had vanished from the country entirely. Two pressures combined to remove it: the great drainage schemes that turned fens and marshes into farmland destroyed its nesting grounds, while roasted crane was a prized centrepiece at noble feasts, and the birds were hunted without restraint. The species did not merely decline; for four centuries it was simply gone.

B — Recovery began without any human plan. In 1979 a small group of wild cranes, blown across the sea on migration, settled in a quiet corner of eastern England, and a tiny population clung on there under discreet protection. Its growth, though, was painfully slow — a pair rarely raises more than one chick a year — and the birds showed no sign of spreading to the many restored wetlands elsewhere in the country. Conservationists therefore decided to give the species a second foothold. The method was already proven: carefully managed reintroductions had brought back red kites and white-tailed eagles, and there was no biological reason it should not work for cranes. Over five years, eggs were collected from large, healthy crane populations abroad, and the chicks hatched from them were reared by hand, then released into restored marshes in the west of the country.

C — Hand-rearing a bird that must remain wild presented an unusual problem. "The one thing a crane chick must never learn is that food comes from people," says Ingrid Halvorsen, the ecologist who led the rearing team. To stop the birds treating humans as parents, her keepers wore hooded grey costumes that disguised the human outline, and offered food with a puppet shaped like an adult crane's head. The chicks exercised on daily walks, following the grey figures through wet grassland as they would have followed their real parents. Before release, the young birds were even taught to fear predators such as foxes, so that their first encounter with danger would not be their last.

D — Once the birds were free, attention turned to following them. Every released crane was fitted with a small GPS tag, solar-powered and light enough for the bird to ignore, and the biologist Marcus Adeyemi has spent years reading the results. "We assumed the young birds would scatter across the whole region," he says. "In fact they are far more faithful to the release area than anyone predicted — most feed and roost within a few kilometres of the marsh where they first flew." The tags also reveal how hard the first years of adulthood are. Early nesting attempts usually fail: inexperienced pairs choose poor sites, eggs are taken by foxes, and sudden spring floods can drown a nest in a night. Success, when it comes, comes with age and practice.

E — Not everyone welcomed the newcomers. Cranes feed in open fields, and a flock can pull up newly sown grain or trample young potatoes, so the project's neighbours watched the growing population with unease. The social researcher Sofia Petrova spent two seasons interviewing farmers around the release site. Her finding was blunt: goodwill could not be assumed, but it could be arranged. Once a compensation scheme paid promptly for damaged crops, and the project sowed special plots of grain to draw the flocks away from commercial fields, hostility faded with remarkable speed. Several farmers, she notes, now describe the birds to visitors with something close to pride.

F — The cranes have also acquired an economic case. The economist Liam O'Donnell tracked visitor spending around two wetland reserves after breeding cranes arrived, and measured a steady rise in overnight stays, café takings and guided-walk bookings. The money matters, he argues, because it funds work far beyond one species: reed beds cut for cranes shelter bitterns and water voles, and pools dug for cranes fill with dragonflies. In his surveys, visitors themselves said the chance of seeing a crane was what had brought them to the reserve. Others are unconvinced. The conservation writer Ruth Calloway accepts that the birds are magnificent, but points out that the programme has cost millions, and argues that the same sum spent directly on wetland restoration might have achieved more for more species. The projects reply that the cranes are precisely what attracts that money in the first place. The argument will be settled by the birds themselves: the test of a reintroduction is not the releasing but the breeding, and each summer's count of wild-hatched chicks is watched like an examination result.`,
      questions: [
        { n: 14, type: "match", group: "minfo", letters: "ABCDEF",
          rubric: "Reading Passage 2 has six paragraphs, A–F. Which paragraph contains the following information? Write the correct letter, A–F. NB You may use any letter more than once.",
          prompt: "a description of special clothing worn by people caring for young birds", answer: "C",
          explain: "Paragraph C describes the rearing method: keepers wore hooded grey costumes that disguised the human outline and fed the chicks with a puppet.",
          evidence: "her keepers wore hooded grey costumes", vocab: ["disguised the human outline", "special clothing"] },
        { n: 15, type: "match", group: "minfo", prompt: "evidence in place names of where cranes used to live", answer: "A", explain: "Paragraph A lists names such as Cranfield, Cranmore and Cranbrook, each recording a marsh or meadow where the birds once gathered.", evidence: "its memory survives in dozens of place names" },
        { n: 16, type: "match", group: "minfo", prompt: "reasons why the birds' first attempts at breeding usually fail", answer: "D", explain: "Paragraph D explains the failures: inexperienced pairs choose poor sites, foxes take the eggs, and spring floods can drown a nest.", evidence: "Early nesting attempts usually fail", vocab: ["nesting attempts", "attempts at breeding"] },
        { n: 17, type: "match", group: "minfo", prompt: "details of how farmers were persuaded to accept the birds", answer: "E", explain: "Paragraph E describes the arrangements: prompt compensation for damaged crops and special plots of grain that drew flocks away from commercial fields.", evidence: "a compensation scheme paid promptly for damaged crops" },
        { n: 18, type: "gap", group: "sum2", note: "ONE WORD ONLY",
          notes: {
            title: "Summary — Preparing young cranes for the wild",
            lines: [
              "Chicks hatched from eggs collected abroad are reared by keepers who wear hooded grey {{18}}, so that the young birds never come to regard humans as {{19}}.",
              "Food is offered with a {{20}} made to look like an adult crane's head, and before being set free the birds are taught to fear {{21}} such as foxes.",
              "After release, each bird carries a small {{22}} so that researchers can follow its movements.",
            ],
          },
          answer: "costumes",
          explain: "The keepers wore hooded grey costumes to disguise the human outline; the summary repeats 'hooded grey', so the missing noun is costumes.",
          evidence: "hooded grey costumes that disguised the human outline" },
        { n: 19, type: "gap", group: "sum2", answer: "parents", explain: "'Come to regard humans as' in the summary paraphrases 'treating humans as' in the passage: the costumes stop the birds seeing people as parents.", evidence: "To stop the birds treating humans as parents", vocab: ["treating", "regard as"] },
        { n: 20, type: "gap", group: "sum2", answer: "puppet", explain: "Food was offered with a puppet shaped like an adult crane's head, so the chicks associated feeding with cranes rather than with people.", evidence: "offered food with a puppet shaped like an adult crane's head" },
        { n: 21, type: "gap", group: "sum2", answer: "predators", explain: "Before release the young birds were taught to fear predators such as foxes; the summary keeps the phrase 'such as foxes' as your locator.", evidence: "taught to fear predators such as foxes" },
        { n: 22, type: "gap", group: "sum2", answer: "tag", explain: "Every released crane was fitted with a small GPS tag; 'carries' in the summary paraphrases 'was fitted with' in the passage.", evidence: "fitted with a small GPS tag", vocab: ["fitted with", "carries"] },
        { n: 23, type: "match", group: "people", boxTitle: "List of People",
          box: [
            "Ingrid Halvorsen",
            "Marcus Adeyemi",
            "Sofia Petrova",
            "Liam O'Donnell",
            "Ruth Calloway",
          ],
          rubric: "Look at the following statements (Questions 23–26) and the list of people below. Match each statement with the correct person, A–E. NB There is one more person than you need.",
          prompt: "The released birds stay closer to their first flying ground than was expected.", answer: "B",
          explain: "Adeyemi's tag data showed the opposite of the team's assumption: the birds are far more faithful to the release area than anyone predicted.",
          evidence: "far more faithful to the release area than anyone predicted", vocab: ["faithful to", "stay closer to"] },
        { n: 24, type: "match", group: "people", prompt: "Money brought in by the birds pays for work that benefits other species.", answer: "D", explain: "O'Donnell measured visitor spending and argues it funds work far beyond one species — reed beds and pools that help bitterns, voles and dragonflies.", evidence: "it funds work far beyond one species" },
        { n: 25, type: "match", group: "people", prompt: "The sum spent on one spectacular species might do more good used another way.", answer: "E", explain: "Calloway argues the millions spent on the programme, if used directly on wetland restoration, might have achieved more for more species.", evidence: "spent directly on wetland restoration might have achieved more", vocab: ["magnificent", "spectacular"] },
        { n: 26, type: "match", group: "people", prompt: "Opposition to the birds faded once payments were introduced.", answer: "C", explain: "Petrova found hostility faded with remarkable speed after a compensation scheme began paying farmers promptly for damaged crops.", evidence: "hostility faded with remarkable speed", vocab: ["hostility", "opposition"] },
      ],
    },
    {
      title: "Passage 3",
      instructions: "You should spend about 20 minutes on Questions 27–40, which are based on Reading Passage 3 below.",
      passageTitle: "The price of possession",
      passage: `Ask anyone who is trying to sell a flat what it is worth, and then ask the buyers who have viewed it, and two different numbers come back. Estate agents see the pattern every week: owners set prices the market will not pay, and they do so not out of greed but in complete sincerity, because to them the flat genuinely seems worth more. Psychologists and economists have a name for this gap: the endowment effect — the tendency to value a thing more highly simply because it is ours. In experiment after experiment, the lowest price at which owners will part with an object comfortably exceeds the highest price that non-owners will pay for the identical item, though nothing about the object itself has changed.

The classic demonstrations used, of all things, coffee mugs. In a series of studies at North American universities, researchers handed decorated mugs to half the students in a room, chosen at random, and then invited the two halves to trade with each other. Standard economic theory makes a clean prediction: since the mugs were distributed by chance, about half of them should quickly change hands, moving to the people who happened to want them most. Nothing of the kind occurred. Sellers asked, on average, roughly twice what buyers were prepared to offer, and only a fraction of the predicted trades took place. The detail that made the result famous was the timescale: the students had owned their mugs for a few minutes. There had been no time to build memories or associations; possession alone had moved the price.

The best-known explanation looks to the psychology of losses. A long line of research shows that losses weigh more heavily on us than gains of the same size — roughly twice as heavily, on most measures. For an owner, parting with the mug is a loss; for a buyer, acquiring it is merely a gain. If losses loom about twice as large as gains, sellers should demand about twice what buyers offer, and that is strikingly close to what the experiments find. On this account, the endowment effect is not a separate oddity of markets at all; it is simply loss aversion showing itself in prices.

Others suspect that ownership works on the self rather than on any ledger of gains and losses. Once a thing is mine, it joins the circle of objects that help define me — my books, my desk, my street — and giving it up means surrendering a small piece of that self. In support, brain-imaging studies find that when owners think about their possessions, regions associated with thinking about oneself become more active; and merely imagining ownership for a moment can nudge an object's value upwards. The two explanations are not really rivals: an object can be both a potential loss and a fragment of identity, and the effect may draw strength from each.

The effect also has boundaries, and they are revealing. People who trade for a living barely show it: professional dealers in collectors' markets, tested with the same procedures as students, show little or no gap between buying and selling prices, as though years of practice had taught them to treat goods as passing through their hands rather than belonging to them. Goods held purely for exchange behave the same way — nobody demands extra compensation to part with a banknote. Yet the effect appears remarkably early and remarkably widely: it has been observed in young children and even in apes, which cling to food already in hand rather than trade it for more. That reach suggests origins far older than shops: in a world without enforceable promises, holding on to what you already possess may simply have been the safer strategy.

Not everyone is persuaded. A determined group of sceptical economists argues that much of the laboratory evidence reflects confusion rather than valuation: participants misunderstand the trading rules, treat their answers as opening moves in a negotiation, and when the task is explained with sufficient care, the gap between buying and selling prices shrinks — in some studies, to nothing. Defenders reply that the world outside the laboratory keeps producing the pattern: house sellers hold out for prices pegged to what they once paid rather than to what the market now says, and motorists value their ageing cars above any dealer's offer. After four decades of argument, the effect refuses either to disappear or to behave, which is itself a kind of answer.

Whatever its mechanism, commerce discovered the effect long before the journals did. Free trials, no-questions-asked returns policies, weekend test drives — all invite the same quiet trick: get the product into the customer's home, let it briefly become theirs, and let ownership finish the sale, because sending the thing back will now feel like a loss rather than a cancelled purchase. The lesson runs deeper than marketing. Value, the endowment effect suggests, is not a fixed property of objects; it flows from the relationship between objects and their owners — which is why the surest way to want something is to be told that it is already yours.`,
      questions: [
        { n: 27, type: "mcq", prompt: "What point does the writer make with the example of people selling flats?", options: ["A Estate agents encourage sellers to ask for too much", "B Owners sincerely believe their property is worth more than buyers will pay", "C Flats are more difficult to price than other possessions", "D Sellers deliberately open negotiations with a high figure"], answer: "B", explain: "The owners are not greedy or bargaining: to them the flat genuinely seems worth more. Options A and D invent motives the passage denies.", evidence: "to them the flat genuinely seems worth more", vocab: ["in complete sincerity", "sincerely believe"] },
        { n: 28, type: "mcq", prompt: "The mug experiments were striking because they showed that", options: ["A students preferred money to mugs", "B the mugs had been distributed unfairly", "C trading between the groups was brisker than predicted", "D a few minutes of ownership was enough to raise an object's value"], answer: "D", explain: "The famous detail was the timescale: possession alone moved the price after only minutes. Option C reverses the result — trade was far below prediction.", evidence: "the students had owned their mugs for a few minutes", vocab: ["possession alone", "ownership was enough"] },
        { n: 29, type: "mcq", prompt: "According to the passage, people who trade professionally", options: ["A display the endowment effect weakly or not at all", "B refuse to take part in laboratory studies", "C value their stock roughly twice as highly as buyers do", "D suffer financially because of the effect"], answer: "A", explain: "Dealers tested with the same procedures show little or no gap between buying and selling prices; practice teaches them to treat goods as passing through.", evidence: "show little or no gap between buying and selling prices", vocab: ["barely show it", "weakly or not at all"] },
        { n: 30, type: "mcq", prompt: "The sceptical economists mentioned in the sixth paragraph believe that", options: ["A the effect exists only for coffee mugs", "B researchers have dishonestly reported their results", "C part of the evidence may be an artefact of how experiments are run", "D the effect disappears in every real market"], answer: "C", explain: "The critics blame confusion about the trading rules: explained with sufficient care, the gap shrinks. They question the method, not the researchers' honesty.", evidence: "reflects confusion rather than valuation", vocab: ["misunderstand the trading rules", "how experiments are run"] },
        { n: 31, type: "ynng", prompt: "The endowment effect appears only after someone has owned an object for a long time.", answer: "NO", explain: "NO: the mug studies showed the opposite — a few minutes of possession was enough, with no time to build memories or associations.", evidence: "possession alone had moved the price" },
        { n: 32, type: "ynng", prompt: "Loss aversion offers a credible explanation of the endowment effect.", answer: "YES", explain: "YES: the writer notes that the sellers' doubled prices are strikingly close to what loss aversion predicts, and calls it the best-known explanation.", evidence: "that is strikingly close to what the experiments find", vocab: ["best-known explanation", "credible explanation"] },
        { n: 33, type: "ynng", prompt: "The endowment effect is equally strong in every culture.", answer: "NOT GIVEN", explain: "NOT GIVEN: the passage mentions children, apes and professional dealers, but it never compares the effect's strength across different cultures.", evidence: "the effect appears remarkably early and remarkably widely" },
        { n: 34, type: "ynng", prompt: "Evidence from animals is relevant to understanding where the effect comes from.", answer: "YES", explain: "YES: the effect's appearance in apes suggests to the writer origins far older than shops — an evolutionary reading of where it comes from.", evidence: "suggests origins far older than shops", vocab: ["origins", "where the effect comes from"] },
        { n: 35, type: "ynng", prompt: "The writer believes the endowment effect matters only inside laboratories.", answer: "NO", explain: "NO: the writer cites house sellers, car owners, free trials and returns policies — the world outside the laboratory keeps producing the pattern.", evidence: "the world outside the laboratory keeps producing the pattern" },
        { n: 36, type: "gap", group: "wl",
          box: ["losses", "apes", "trials", "bargains", "exchange", "confusion", "gains", "habits", "prices"],
          boxTitle: "List of Words",
          notes: {
            title: "Summary — The endowment effect",
            lines: [
              "Owners typically demand more for an object than buyers will pay, apparently because giving something up is felt as one of the {{36}} that people weight so heavily.",
              "The effect does not appear with goods held purely for {{37}}, such as money,",
              "yet it has been observed in young children and even in {{38}}, which points to very ancient origins.",
              "Retailers exploit it by offering free {{39}} and easy returns, betting that giving goods back will feel like losing them.",
              "Critics, however, argue that some laboratory results reflect nothing deeper than {{40}} about the rules of the trading task.",
            ],
          },
          answer: "A",
          explain: "Parting with a possession is processed as a loss, and losses weigh roughly twice as heavily as gains — the word the summary needs is 'losses'.",
          evidence: "losses weigh more heavily on us than gains", vocab: ["parting with", "giving something up"] },
        { n: 37, type: "gap", group: "wl", answer: "E", explain: "Goods held purely for exchange, like banknotes, show no endowment effect; 'exchange' fits both the grammar and the passage's example of money.", evidence: "Goods held purely for exchange behave the same way" },
        { n: 38, type: "gap", group: "wl", answer: "B", explain: "The passage says the effect has been observed in young children and even in apes, so 'apes' completes the summary's claim about ancient origins.", evidence: "observed in young children and even in apes" },
        { n: 39, type: "gap", group: "wl", answer: "C", explain: "The free trial is the writer's first example of commerce exploiting the effect: temporary ownership makes returning the product feel like a loss.", evidence: "The free trial, the no-questions-asked returns policy", vocab: ["no-questions-asked returns", "easy returns"] },
        { n: 40, type: "gap", group: "wl", answer: "F", explain: "The sceptics claim the laboratory evidence reflects confusion rather than valuation — participants misunderstand the trading rules of the task.", evidence: "participants misunderstand the trading rules" },
      ],
    },
  ],
};
