// Smart LC Pre-IELTS Set 7 — Academic Reading (40 questions, 3 passages).
// Original material authored for Smart LC to the blueprint: P1 factual
// history (completion + TFNG), P2 discursive with lettered paragraphs
// (matching paragraph-information + summary + people matching with one
// extra name), P3 argumentative science (MCQ-4 + YNNG + sentence
// endings). Key quotas: TFNG/YNNG balanced with no runs of three, flat
// letters, unique concrete-noun answers, correct MCQ options paraphrase
// the text while distractors echo its wording. Enrichment (explain /
// evidence / vocab) authored with the content.
export const UPSET7_READING = {
  id: "upset7-reading",
  bookId: "upset7",
  title: "Pre-IELTS Set 7 — Reading",
  module: "reading",
  durationMin: 60,
  sections: [
    {
      title: "Passage 1",
      instructions: "You should spend about 20 minutes on Questions 1–13, which are based on Reading Passage 1 below.",
      passageTitle: "Thirteen metres of sawdust: how the circus began",
      passage: `The circus feels ancient. Its name is Latin, and its admirers like to trace it back to the chariot races of ancient Rome. Yet the entertainment we would recognise — a ring, acrobats, clowns, music and a smell of sawdust — is younger than the piano. It was born in London in 1768, on a patch of open ground south of the River Thames, and its creator was not a showman by training but a soldier. Philip Astley, a former cavalry sergeant famous for his horsemanship, had left the army with a white charger, a sword and very little else. To earn a living he began giving public displays of trick riding, standing upright on the back of a moving horse while spectators watched from the grass and, he hoped, dropped coins into a hat.

Astley's decisive discovery was geometrical. Earlier trick riders had performed in straight lines, galloping past their audience and then trudging back to begin again. Astley found that it was far easier to keep his feet on a horse moving in a circle of the right size: the constant turn produced a force that pressed the standing rider gently outwards, and by leaning against it he could balance with confidence even at speed. After long experiment he settled on a ring about thirteen metres across — wide enough for a comfortable canter, small enough for every seat to be close to the action. That diameter became, and remains, the standard size of circus rings all over the world, so that a horse or an acrobat trained in one ring can perform in any other.

Astley invented almost none of the acts he presented. Rope-dancers, tumblers, jugglers and performing dogs had entertained crowds at fairs for centuries. His talent was for combination: he gathered these scattered performers into a single programme, with his own riding as the centrepiece. He engaged clowns to amuse the audience between the riding displays, added a strongman and a band, and wrapped the whole evening in military showmanship. The public responded so warmly that he soon replaced his open field with a roofed amphitheatre, complete with painted scenery and an orchestra, and in the decades that followed he established nineteen riding amphitheatres in cities across Europe.

Curiously, Astley never called his show a circus; his buildings were always 'amphitheatres'. The word was introduced by a rival. In 1782 Charles Hughes, a flamboyant rider who had once worked for Astley, opened a competing venue in London and named it the Royal Circus, borrowing the Latin term for the chariot-racing arenas of Rome. Hughes's business eventually collapsed, but his name for the entertainment survived, and in time it attached itself to the very kind of show his old employer had invented.

It was in the United States that the circus changed its shape. American distances were too great, and most towns too small, to support permanent buildings, and hauling timber from place to place consumed time and money. In 1825 the showman Joshua Purdy Brown found the answer, replacing the wooden walls with a canvas tent. The 'big top', as it became known, could be raised in a morning and taken down the same night, which meant a circus could now visit a small town for a single day and move on. From the 1870s the largest companies travelled by railway, in trains of dozens of carriages carrying performers, animals, canvas and kitchens. Arrival itself became advertising: the whole company would parade down the main street, and by evening half the county had bought tickets. The greatest shows performed in three rings at once, before crowds of ten thousand and more.

The twentieth century slowly withdrew those crowds. First cinema and then television offered spectacle without the journey or the ticket queue, and audiences began to drain away. Costs climbed, skilled labour grew scarce and, most damaging of all, public feeling about the use of performing animals changed. Acts with elephants and big cats, once the pride of the programme, came to strike many spectators as cruelty rather than wonder; laws in many countries restricted or banned wild-animal performances, and several of the world's most famous companies closed their doors.

Yet the circus did not die; it changed its skin. From the 1970s a movement often called 'new circus' began to build shows around human skill alone, borrowing freely from theatre and dance. Its most spectacular product appeared in 1984, when a troupe of street performers from Montreal founded Cirque du Soleil, which built its spectacles entirely around human performers — no animals of any kind — and grew into an entertainment company with audiences in the millions. Contemporary circus is now taught in dedicated schools on every continent, some of which award university degrees in circus arts. Two and a half centuries after a cavalry sergeant first stood on a cantering horse beside the Thames, the costumes have changed, the animals have largely gone — and the ring is still thirteen metres across.`,
      questions: [
        { n: 1, type: "gap", prompt: "Astley found that a rider could stay upright more easily when the horse travelled in a ______.", note: "ONE WORD ONLY", answer: "circle", explain: "'Stay upright' in the question paraphrases 'keep his feet' in the passage: riding in a circle of the right size made balancing far easier.", evidence: "far easier to keep his feet on a horse moving in a circle", vocab: ["keep his feet", "stay upright"] },
        { n: 2, type: "gap", prompt: "The traditional circus ring is about thirteen ______ in diameter.", note: "ONE WORD ONLY", answer: "metres", explain: "'In diameter' in the question paraphrases 'across' in the passage: Astley settled on a ring about thirteen metres across, still the standard size today.", evidence: "a ring about thirteen metres across", vocab: ["across", "in diameter"] },
        { n: 3, type: "gap", prompt: "Astley hired ______ to entertain the audience between the riding acts.", note: "ONE WORD ONLY", answer: "clowns", explain: "'Hired' and 'entertain' paraphrase 'engaged' and 'amuse': clowns filled the gaps between riding displays in Astley's programme.", evidence: "He engaged clowns to amuse the audience", vocab: ["amuse", "entertain"] },
        { n: 4, type: "gap", prompt: "From 1825, American circuses performed inside a canvas ______ instead of a building.", note: "ONE WORD ONLY", answer: "tent", explain: "Joshua Purdy Brown replaced the wooden walls of circus buildings with a canvas tent, later known as the 'big top'.", evidence: "replacing the wooden walls with a canvas tent" },
        { n: 5, type: "gap", prompt: "From the 1870s, the biggest companies moved between towns by ______.", note: "ONE WORD ONLY", answer: ["railway", "rail", "train"], explain: "'Moved between towns' paraphrases 'travelled': the largest companies travelled by railway, in trains of dozens of carriages.", evidence: "the largest companies travelled by railway", vocab: ["travelled", "moved"] },
        { n: 6, type: "gap", prompt: "Circus performance can now be studied at special ______, some offering degrees.", note: "ONE WORD ONLY", answer: "schools", explain: "'Special' in the question paraphrases 'dedicated' in the passage: contemporary circus is taught in dedicated schools, some awarding university degrees.", evidence: "taught in dedicated schools on every continent", vocab: ["dedicated", "special"] },
        { n: 7, type: "tfng", prompt: "Most of the acts in Astley's shows already existed before he presented them.", answer: "TRUE", explain: "TRUE: the passage says Astley invented almost none of the acts — rope-dancers, tumblers and jugglers had entertained fair crowds for centuries.", evidence: "Astley invented almost none of the acts he presented", vocab: ["invented almost none", "already existed"] },
        { n: 8, type: "tfng", prompt: "Astley was the first person to use the word 'circus' for this kind of show.", answer: "FALSE", explain: "FALSE: Astley never called his show a circus; the word was introduced by his rival Charles Hughes, who opened the Royal Circus in 1782.", evidence: "Astley never called his show a circus" },
        { n: 9, type: "tfng", prompt: "Astley made a large fortune from his European amphitheatres.", answer: "NOT GIVEN", explain: "NOT GIVEN: we learn he established nineteen amphitheatres across Europe, but the passage says nothing about how much money they earned him.", evidence: "he established nineteen riding amphitheatres in cities across Europe" },
        { n: 10, type: "tfng", prompt: "The tent made it possible for circuses to perform in places with small populations.", answer: "TRUE", explain: "TRUE: because the big top could be raised and taken down in a day, a circus could visit a small town for a single day and move on.", evidence: "a circus could now visit a small town for a single day", vocab: ["small town", "small populations"] },
        { n: 11, type: "tfng", prompt: "Television encouraged more people to attend circus performances.", answer: "FALSE", explain: "FALSE: the opposite happened — cinema and television offered spectacle at home, and circus audiences began to drain away during the twentieth century.", evidence: "audiences began to drain away", vocab: ["drain away", "fewer people"] },
        { n: 12, type: "tfng", prompt: "Some contemporary circus companies stage shows without any animal acts.", answer: "TRUE", explain: "TRUE: Cirque du Soleil built its spectacles entirely around human performers, with no animals of any kind — the model of the 'new circus' movement.", evidence: "built its spectacles entirely around human performers", vocab: ["human performers", "without animals"] },
        { n: 13, type: "tfng", prompt: "Cirque du Soleil is the most profitable circus company in history.", answer: "NOT GIVEN", explain: "NOT GIVEN: the company grew large, with audiences in the millions, but the passage never compares its profits with those of any other company.", evidence: "grew into an entertainment company with audiences in the millions" },
      ],
    },
    {
      title: "Passage 2",
      instructions: "You should spend about 20 minutes on Questions 14–26, which are based on Reading Passage 2 below.",
      passageTitle: "Packaging that grows",
      passage: `A — Take almost any fragile object you have ever received by post — a laptop, a jar, a lamp — and the odds are it arrived cradled in expanded polystyrene. As packaging, the white foam is close to perfect: feather-light, mouldable, shock-absorbing and very cheap. As a material to share a planet with, it is a disaster. Made from oil, it is typically used for a few days and then discarded, whereupon it can persist in soil or water for centuries, gradually crumbling into beads that drift, scatter and are all but impossible to recover. Recycling is technically possible but rarely economic, since the foam is mostly air and transporting it costs more than it is worth. A young industry now proposes a strange solution: stop manufacturing packaging, and start growing it. Its raw material is mycelium — the mass of fine white threads that a fungus spreads through soil or rotting wood, and of which the mushroom is merely the visible fruit. Grown around a core of plant fibre, those threads knit themselves into a light, springy solid — a foam, in effect, produced by biology rather than by chemistry.

B — The technique owes much to Thomas Aldren, an engineering graduate who grew his first samples on a shelf in his student flat and spent the next two years learning, mostly through failure, what fungi will and will not do. The method he eventually arrived at is disarmingly simple. Production starts with agricultural waste — corn stalks, hemp fibre, seed husks — which is cleaned and briefly heated so that no wild organisms survive to compete. The fragments are then mixed with mycelium spawn and packed into a mould shaped like the finished product: a protective corner block, a bottle sleeve, a tray. The mould sits in a dark room for about a week while the threads spread through the fragments, digesting their surfaces and binding them into a single solid piece. Finally the piece is dried with heat, which kills the fungus and stops the growth; the result is firm, dry, odourless and ready to use.

C — How good is the material? Sofia Brandt, a materials engineer who has spent five years testing grown packaging for manufacturers, is careful not to oversell it, but her central finding is blunt: for cushioning fragile goods it performs as well as polystyrene, absorbing the knocks and vibration a parcel actually meets in transit. It also insulates well, and unlike plastic foam it is naturally resistant to fire, charring slowly rather than melting. Its most striking property, though, appears at the end of its life. Buried in a garden compost heap, a mycelium block disappears in about six weeks, feeding the soil as it breaks apart — a disposal route no plastic can offer.

D — Commerce has begun to take notice. A Scandinavian furniture retailer now ships some of its glassware in grown corner blocks; computer manufacturers, cosmetics brands and wine merchants have run trials; and a British supermarket has tested mycelium trays for its gift ranges. For the brands involved the appeal goes beyond ecology: a box that can promise to vanish harmlessly in a customer's garden is itself a piece of advertising. The obstacle is price: grown packaging still costs roughly two to three times as much as the foam it replaces. Marcus Yeo, an analyst who follows the packaging industry, regards the premium as temporary. The ingredients are agricultural leftovers with almost no market value, he points out, and the real costs lie in buildings and time. 'Polystyrene has had seventy years of scale,' he says. 'The gap narrows with every new facility that opens.'

E — There are more stubborn problems than price. Ingrid Halvorsen, a packaging scientist at a Norwegian research institute, lists them without embarrassment. In a damp warehouse the material slowly absorbs moisture, and as it does so it softens and loses strength, so coatings or careful storage are needed in humid climates. It is heavier than foam, which matters when freight is charged by weight. And because it is produced by a living organism, no two batches are ever quite identical; a fungus does not read specifications. Until the industry agrees on standards for testing and certifying grown materials, she argues, cautious sectors such as electronics will keep most of their orders with plastic.

F — None of these difficulties has discouraged the mycologist Daniel Reyes, who has spent his career persuading companies that fungi are a technology. Packaging, he argues, is simply the easiest first market: quick to certify, quickly replaced, forgiving of small flaws. In laboratories and start-ups, mycelium is already being pressed into insulation panels for buildings, sound-absorbing tiles for offices, and a leather-like fabric for bags and shoes; one Dutch designer has grown an entire chair in a single mould. 'Packaging is only the first chapter,' Reyes says. 'We are learning to grow objects the way we once learned to fire clay.'`,
      questions: [
        { n: 14, type: "match", group: "minfo", letters: "ABCDEF",
          rubric: "Reading Passage 2 has six paragraphs, A–F. Which paragraph contains the following information? Write the correct letter, A–F. NB You may use any letter more than once.",
          prompt: "a description of the stages by which the material is made", answer: "B",
          explain: "Paragraph B walks through production step by step: cleaning the waste, mixing in spawn, a week in a mould in the dark, then drying with heat.",
          evidence: "packed into a mould shaped like the finished product" },
        { n: 15, type: "match", group: "minfo", prompt: "examples of businesses that have tried the material", answer: "D", explain: "Paragraph D lists the adopters: a Scandinavian furniture retailer, computer manufacturers, cosmetics brands, wine merchants and a British supermarket.", evidence: "computer manufacturers, cosmetics brands and wine merchants have run trials", vocab: ["run trials", "tried"] },
        { n: 16, type: "match", group: "minfo", prompt: "a problem that arises when the material is stored in humid conditions", answer: "E", explain: "Paragraph E explains that in a damp warehouse the material absorbs moisture, softens and loses strength, so it needs coatings or careful storage.", evidence: "In a damp warehouse the material slowly absorbs moisture", vocab: ["damp", "humid"] },
        { n: 17, type: "match", group: "minfo", prompt: "an estimate of how long the material takes to decompose", answer: "C", explain: "Paragraph C gives the figure: buried in a garden compost heap, a mycelium block disappears in about six weeks, feeding the soil as it goes.", evidence: "a mycelium block disappears in about six weeks", vocab: ["disappears", "decompose"] },
        { n: 18, type: "match", group: "minfo", prompt: "uses for mycelium other than packaging", answer: "F", explain: "Paragraph F looks beyond packaging: insulation panels, sound-absorbing tiles, leather-like fabric and even a chair grown whole in a single mould.", evidence: "insulation panels for buildings, sound-absorbing tiles for offices" },
        { n: 19, type: "gap", group: "sum2", note: "ONE WORD ONLY",
          notes: {
            title: "Summary — Growing a package",
            lines: [
              "Production begins with agricultural {{19}}, such as corn stalks or seed husks, which is cleaned and briefly heated.",
              "The fragments are mixed with fungal spawn and packed into a {{20}} the shape of the final product, where the threads bind them together over about a week.",
              "The piece is then dried using {{21}}, which stops the fungus growing.",
              "Unlike plastic foam, which can survive for centuries, a buried block breaks down in ordinary {{22}} in around six weeks.",
            ],
          },
          answer: "waste",
          explain: "The summary keeps the passage's own phrase: production starts with agricultural waste — corn stalks, hemp fibre and seed husks with almost no market value.",
          evidence: "Production starts with agricultural waste", vocab: ["leftovers", "waste"] },
        { n: 20, type: "gap", group: "sum2", answer: ["mould", "mold"], explain: "'The shape of the final product' paraphrases 'shaped like the finished product': the mixture is packed into a mould, such as a corner block or tray.", evidence: "packed into a mould shaped like the finished product", vocab: ["finished", "final"] },
        { n: 21, type: "gap", group: "sum2", answer: "heat", explain: "The final stage is drying with heat, which kills the fungus and stops the growth, leaving the piece firm, dry and ready to use.", evidence: "the piece is dried with heat" },
        { n: 22, type: "gap", group: "sum2", answer: "compost", explain: "'Breaks down' paraphrases 'disappears': buried in a garden compost heap, the block is gone in about six weeks, unlike foam that persists for centuries.", evidence: "Buried in a garden compost heap", vocab: ["garden", "ordinary"] },
        { n: 23, type: "match", group: "people", boxTitle: "List of People",
          box: [
            "Thomas Aldren",
            "Sofia Brandt",
            "Marcus Yeo",
            "Ingrid Halvorsen",
            "Daniel Reyes",
          ],
          rubric: "Look at the following statements (Questions 23–26) and the list of people below. Match each statement with the correct person, A–E. NB There is one more name than you need.",
          prompt: "The extra cost of grown packaging will shrink as production expands.", answer: "C",
          explain: "Yeo calls the price premium temporary: polystyrene has seventy years of scale behind it, and the gap narrows with every new facility that opens.",
          evidence: "The gap narrows with every new facility that opens", vocab: ["facility", "factory"] },
        { n: 24, type: "match", group: "people", prompt: "Packaging is just the start of what the material will be used for.", answer: "E", explain: "Reyes sees packaging as merely the easiest first market and says 'packaging is only the first chapter' — mycelium will grow many other objects.", evidence: "Packaging is only the first chapter", vocab: ["first chapter", "start"] },
        { n: 25, type: "match", group: "people", prompt: "The material protects delicate goods as effectively as plastic foam.", answer: "B", explain: "Brandt's central finding after five years of testing: for cushioning fragile goods, the grown material performs as well as polystyrene in transit conditions.", evidence: "for cushioning fragile goods it performs as well as polystyrene", vocab: ["polystyrene", "plastic foam"] },
        { n: 26, type: "match", group: "people", prompt: "Differences between batches stand in the way of wider acceptance.", answer: "D", explain: "Halvorsen notes that a living organism never produces identical batches, so cautious sectors will stay with plastic until testing standards exist.", evidence: "no two batches are ever quite identical", vocab: ["not identical", "differences"] },
      ],
    },
    {
      title: "Passage 3",
      instructions: "You should spend about 20 minutes on Questions 27–40, which are based on Reading Passage 3 below.",
      passageTitle: "Little and often: the spacing effect",
      passage: `Every examination season produces the same scene: a student, a desk, a tower of notes, and one heroic night in which everything will finally be learned. Cramming has obvious attractions — it is dramatic, it is sociable in its misery, and it visibly fills the hours before the deadline. It also feels effective, in the moment, in a way that quieter methods do not. Yet on one point the research record is unusually clear: for making knowledge last, massed study of this kind is among the least efficient methods ever examined. The efficient alternative is almost insultingly simple. Take the same material and the same total number of hours, but cut the studying into shorter sessions separated by days or weeks. The improvement in long-term memory that results is called the spacing effect, and it may be the closest thing the psychology of learning has to a law.

The effect was measured before psychology had proper laboratories. In the 1880s the German researcher Hermann Ebbinghaus spent years memorising lists of invented syllables — deliberately meaningless, so that no prior knowledge could help him — and then testing his own recall at intervals. Two results emerged. His famous forgetting curve showed that newly learned material fades most quickly in the hours immediately after learning, the losses slowing as time passes. And a quieter observation sat beside it: repetitions spread across three days did more for his memory than the same number of repetitions packed into one. The second finding attracted little attention for decades, which is a pity, because a century of later work has done nothing but confirm it.

Hundreds of experiments have now found the effect in children and adults, in laboratories and classrooms, and in material as different as foreign vocabulary, surgical technique and school mathematics. The spacing effect is regarded today as one of the most dependable findings in the study of learning. None of this means cramming achieves nothing. Massed practice can deliver a perfectly respectable performance in tomorrow morning's test; what it cannot do is make the knowledge stay. Re-test the crammers a month later and most of their advantage has evaporated, while learners who spaced the same hours hold on to far more.

Why should a gap improve memory? The leading explanation turns on effort. In a massed session, each repetition arrives while the memory is still warm; the material is processed smoothly, and the smoothness is misread. Learners routinely take the fluent feeling of massed practice as evidence of mastery, when it is really evidence of recency. After a spacing interval, by contrast, the memory has partly faded and must be effortfully rebuilt — and that struggle to retrieve is precisely what deepens the trace. Some psychologists file spacing among the 'desirable difficulties': study conditions that make practice feel slower and harder while making its results stronger. Spaced practice, in short, builds stronger memories even though it feels less effective, and human intuition copes badly with that combination.

The principle long ago escaped the laboratory. Language learners have used spaced flashcards for a century, at first in wooden boxes whose compartments were reviewed at different intervals, the cards migrating backwards with each success. Software has now automated the ritual: an algorithm tracks every item and schedules it for review just before it would slip away, so that the intervals stretch from a day, to a week, to months as an item becomes secure. Tens of millions of people now learn vocabulary, scripts and even anatomy this way, a few minutes at a time. The same logic has begun to reach classrooms, where some teachers now weave short reviews of older material into every lesson rather than closing a topic and never returning to it.

One question has no single answer: how long should the gaps be? The best gap depends on how far ahead the test lies. For an exam next week, sessions a day or two apart serve well; for knowledge that must survive into next year, the research favours intervals of weeks or months. One well-known review proposed a rough rule of thumb — a gap of roughly ten to twenty per cent of the time you hope to remember for — but its authors were the first to admit that the figure is a guide, not a law.

Which returns us to the all-night student. If spacing costs nothing and roughly doubles retention, why does cramming survive? Timetables share the blame, since courses that assess everything at the end invite a sprint. But the deeper obstacle is psychological: we judge our own learning by how it feels while we are doing it, and spacing feels worse — slower, more forgetful, less complete. A method that feels inefficient and works will always struggle against one that feels efficient and fails. The spacing effect asks learners to do something genuinely difficult: to trust the evidence over the experience — and to open the books a little earlier.`,
      questions: [
        { n: 27, type: "mcq", prompt: "What does the writer say about Ebbinghaus?", options: ["A He founded the first psychology laboratory", "B His experiments on himself showed how rapidly new learning is lost", "C He used familiar words to test his memory", "D His finding about spacing was immediately influential"], answer: "B", explain: "Ebbinghaus tested his own recall and his forgetting curve showed rapid early loss. Options C and D reverse the passage: syllables were meaningless, and the spacing finding was ignored for decades.", evidence: "newly learned material fades most quickly in the hours immediately after learning", vocab: ["fades most quickly", "rapidly lost"] },
        { n: 28, type: "mcq", prompt: "According to the writer, massed practice", options: ["A cannot produce a good result in a test the next day", "B feels less fluent than spaced practice", "C requires more hours of study in total", "D gives learners a false sense of how much they have mastered"], answer: "D", explain: "The smooth, fluent feeling of massed practice is misread as mastery when it is really recency. Option A contradicts the passage, which says cramming can pass tomorrow's test.", evidence: "the fluent feeling of massed practice as evidence of mastery", vocab: ["evidence of mastery", "false sense"] },
        { n: 29, type: "mcq", prompt: "The writer mentions 'desirable difficulties' in order to", options: ["A explain why practice that feels harder can produce stronger learning", "B argue that examinations should be made more difficult", "C show that psychologists disagree about the spacing effect", "D warn against making study sessions too unpleasant"], answer: "A", explain: "Desirable difficulties are conditions that make practice feel slower and harder while making its results stronger — exactly the paradox spacing illustrates.", evidence: "make practice feel slower and harder while making its results stronger" },
        { n: 30, type: "mcq", prompt: "In the final paragraph, the writer suggests that the greatest obstacle to spaced learning is", options: ["A the cost of suitable software", "B a lack of scientific evidence", "C the way learners judge progress by how studying feels", "D teachers' refusal to change their courses"], answer: "C", explain: "Timetables share the blame, but the deeper obstacle is psychological: we judge our learning by how it feels, and spacing feels worse than cramming.", evidence: "we judge our own learning by how it feels", vocab: ["how it feels", "by feeling"] },
        { n: 31, type: "ynng", prompt: "The spacing effect is among the most reliable results in research on learning.", answer: "YES", explain: "YES: 'reliable' paraphrases 'dependable' — after hundreds of experiments, the writer calls it one of the most dependable findings in the study of learning.", evidence: "one of the most dependable findings in the study of learning", vocab: ["dependable", "reliable"] },
        { n: 32, type: "ynng", prompt: "Cramming gives no benefit at all, even in a test the following day.", answer: "NO", explain: "NO: the writer explicitly concedes the opposite — massed practice can deliver a perfectly respectable performance in tomorrow morning's test; it just fades fast.", evidence: "Massed practice can deliver a perfectly respectable performance", vocab: ["respectable performance", "benefit"] },
        { n: 33, type: "ynng", prompt: "Spaced study tends to feel less effective than it really is.", answer: "YES", explain: "YES: the writer states that spaced practice builds stronger memories even though it feels less effective — a combination intuition handles badly.", evidence: "builds stronger memories even though it feels less effective" },
        { n: 34, type: "ynng", prompt: "Flashcard software produces better results than boxes of paper cards.", answer: "NOT GIVEN", explain: "NOT GIVEN: both wooden card boxes and scheduling software are described, but the writer never compares their results or says one works better.", evidence: "Software has now automated the ritual" },
        { n: 35, type: "ynng", prompt: "Researchers have identified one ideal interval that suits every learning goal.", answer: "NO", explain: "NO: the passage says this question has no single answer — the best gap depends on the goal, and even the rule of thumb is only a guide.", evidence: "One question has no single answer", vocab: ["no single answer", "no one ideal"] },
        { n: 36, type: "match", group: "ends", boxTitle: "Sentence endings",
          box: [
            "disappears fastest soon after it has been studied.",
            "was rejected by Ebbinghaus as unscientific.",
            "depends on how distant the test or deadline is.",
            "may bring success the next day but little lasting knowledge.",
            "strengthens memory despite feeling less effective.",
            "only works for learning language vocabulary.",
            "presents each item again shortly before it would be forgotten.",
          ],
          rubric: "Complete each sentence with the correct ending, A–G, below.",
          prompt: "Ebbinghaus discovered that recently memorised material", answer: "A",
          explain: "'Disappears fastest' paraphrases 'fades most quickly': the forgetting curve shows the steepest losses in the hours immediately after learning.",
          evidence: "fades most quickly in the hours immediately after learning", vocab: ["fades", "disappears"] },
        { n: 37, type: "match", group: "ends", prompt: "A student who crams immediately before an exam", answer: "D", explain: "Cramming can produce a respectable mark the next morning, but a month later most of the advantage has evaporated — success without lasting knowledge.", evidence: "a month later and most of their advantage has evaporated", vocab: ["respectable performance", "success"] },
        { n: 38, type: "match", group: "ends", prompt: "Practice divided into separate spaced sessions", answer: "E", explain: "'Strengthens memory' paraphrases 'builds stronger memories': the struggle to retrieve partly faded material deepens the trace, despite feeling less effective.", evidence: "that struggle to retrieve is precisely what deepens the trace", vocab: ["builds", "strengthens"] },
        { n: 39, type: "match", group: "ends", prompt: "Flashcard software with a scheduling algorithm", answer: "G", explain: "'Shortly before it would be forgotten' paraphrases 'just before it would slip away': the algorithm times each review to catch the fading memory.", evidence: "schedules it for review just before it would slip away", vocab: ["slip away", "be forgotten"] },
        { n: 40, type: "match", group: "ends", prompt: "The most effective length for a spacing interval", answer: "C", explain: "'How distant the test is' paraphrases 'how far ahead the test lies': gaps of days suit next week's exam, while gaps of weeks suit next year's.", evidence: "depends on how far ahead the test lies", vocab: ["far ahead", "distant"] },
      ],
    },
  ],
};
